### ISSUE TITLE
CPU load not reported correctly

### ISSUE THREAD

**Issue by lukaszsobala** [Joshua-Riek/ubuntu-rockchip#1001]
### What happened?

On Rock 5B, the CPU load should be (usually) between 0 and 8 because there are 8 cores. But the load is between 17 and 25, as if it was offset by +17.

On Orange Pi 3b, the load is between 1 and 5, as if it was offset by +1.

### Kernel version

6.1.0-23-rockchip

### SBC model

Rock 5B, Orange Pi 3B v1.1.1

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

**Comment by watou** [comment]
Which tool reports these incorrect numbers?  I am using 6.1.0-1023-rockchip #23 on Rock5B and I get correct-seeming numbers are shown in tload and htop. I also installed rtop graphical barcharts for resource usage and they shown correct percentages.
