### ISSUE TITLE
Bug Report:  one USB 3.0 becomes to USB 2.0

### ISSUE THREAD

**Issue by mario-huang** [Joshua-Riek/ubuntu-rockchip#1008]
### What happened?

There should be two USB 3.0 ports. 
![image](https://github.com/user-attachments/assets/bf3775ca-ddd5-43c4-a7c1-be181bc65226)

Bus 004 should be USB 3.0.
$ lsusb -t
/:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 480M
/:  Bus 002.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 5000M
/:  Bus 003.Port 001: Dev 001, Class=root_hub, Driver=ehci-platform/1p, 480M
/:  Bus 004.Port 001: Dev 001, Class=root_hub, Driver=ehci-platform/1p, 480M
    |__ Port 001: Dev 002, If 0, Class=Mass Storage, Driver=uas, 480M
/:  Bus 005.Port 001: Dev 001, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 006.Port 001: Dev 001, Class=root_hub, Driver=ohci-platform/1p, 12M

### Kernel version

6.1.0-1023-rockchip

### SBC model

Orange Pi 5

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

**Comment by Joshua-Riek** [comment]
There is only one USB 3.0 port. The rest are USB 2.0.

**Comment by mario-huang** [comment]
> There is only one USB 3.0 port. The rest are USB 2.0.

What? I see there are two in the document, one is 3.0, one is 3.1. Am I wrong?
![image](https://github.com/user-attachments/assets/5887762f-3896-4826-9ebc-eb738611b50c)

**Comment by Joshua-Riek** [comment]
The 3.1 USB port is shared between USB-C and the white USB 2.0 port.

**Comment by mario-huang** [comment]
$ lsusb -t
/:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 480M
/:  Bus 002.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 5000M
/:  Bus 003.Port 001: Dev 001, Class=root_hub, Driver=ehci-platform/1p, 480M
/:  Bus 004.Port 001: Dev 001, Class=root_hub, Driver=ehci-platform/1p, 480M
/:  Bus 005.Port 001: Dev 001, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 006.Port 001: Dev 001, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 007.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 480M
/:  Bus 008.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 5000M

**Comment by mario-huang** [comment]
> The 3.1 USB port is shared between USB-C and the white USB 2.0 port.

Yes, that's true, but I think there are two blue USB  ports. The up one is 3.0 and the down one is 2.0.
Sorry for the newbie questions.😀

**Comment by Joshua-Riek** [comment]
I see nothing wrong here, as stated previously. If you believe there is, you are welcome to investigate.
