### ISSUE TITLE
Bug Report: Cannot access to sudo orangepi-config in pi 5 after installing ubuntu 24.04

### ISSUE THREAD

**Issue by TayyabAsim047** [Joshua-Riek/ubuntu-rockchip#1019]
### What happened?

I am unable to access the orangepi-config so that I can enable HDMI input (hdmirx) on my device. is there any method please guide

### Kernel version

6.1.0-1025-rockchip

### SBC model

Orange Pi 5 Plus

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

**Comment by TayyabAsim047** [comment]
so how to enable hdmirx for orange pi 5 plus using this os?

**Comment by Joshua-Riek** [comment]
Read the wiki.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Ubuntu-24.04-LTS#using-a-device-tree-overlay
