### ISSUE TITLE
Bug Report: Kworker eats 100% CPU

### ISSUE THREAD

**Issue by MoskalenkoM** [Joshua-Riek/ubuntu-rockchip#1023]
### What happened?

After upgrading Ubuntu from 22.04 to 24.04 nothing works. The processor is 100% consumed by Kworker.

### Kernel version

6.8.0-41-generic

### SBC model

Dell laptop

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

**Comment by Joshua-Riek** [comment]
This is completely invalid.
