### ISSUE TITLE
Bug Report: Chromium doesn't work in v2.3.2 release

### ISSUE THREAD

**Issue by Singular112** [Joshua-Riek/ubuntu-rockchip#1036]
### What happened?

Hello.

I've just installed the new version of Ubuntu 24.02 ([v2.3.2](https://github.com/Joshua-Riek/ubuntu-rockchip/releases/tag/v2.3.2)) on my Orange Pi 5 device.

After the installation was completed I tried to open Chromium and it didn't work. It spins the loading clock on the icon of Chromium and nothing is happening.

### Kernel version

6.1.0-1025-rockchip

### SBC model

Orange Pi 5

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

**Comment by Bluesmanuk** [comment]
I just wrote the image to an SD card and Chromium works just fine on my Orange Pi 5.
