### ISSUE TITLE
Feature Request: updates and additional dto for mcp251x SPI CAN driver

### ISSUE THREAD

**Issue by jobafr** [Joshua-Riek/ubuntu-rockchip#1054]
### Feature Description

Hi,

thank you so much for this project! We'd like to use the [linux-rockchip](https://github.com/Joshua-Riek/linux-rockchip) kernel with an mcp2515 CAN adapter connected to our Radxa Rock 5b on the spi0-m2-cs0 interface.

We'd like to use an up-to-date kernel as well, because there have been some nasty bugs in the old kernel version we got from Radxa's original Ubuntu 20.04 image. Your kernel has most of what we need, except for

- the [rk3588-spi0-m2-cs0-mcp2515-8mhz](https://github.com/radxa/overlays/blob/56dabd510fef878cd3a1320cf8d7dcbf493b2524/arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m2-cs0-mcp2515-8mhz.dts) device tree overlay (this configuration is officially supported according to [Radxa's pinout](https://wiki.radxa.com/Rock5/hardware/5b/gpio), but the dts file was added to their kernel at some later point at our request, so it probably wasn't in whatever version you pulled in here).
- the [latest bugfix to mcp251x in the upstream kernel](https://github.com/torvalds/linux/commit/7dd9c26bd6cf679bcfdef01a8659791aa6487a29)

Would it be possible to pull these in here?

Side note, is it possible to build the kernel without cleaning the entire build directory? I've been using
```bash
sudo ./build.sh -ko --board=rock-5b -v -s jammy
```
so far and it takes ages. (I did change the kernel branch in `config/suites/jammy.sh` to `noble` so I can use the newest kernel on 22.04, which seems to work fine).

**Comment by Joshua-Riek** [comment]
Can you please open a pull request?


Compiling the kernel is the same as upstream Ubuntu.
```bash
# shellcheck disable=SC2046
export $(dpkg-architecture -aarm64)
export CROSS_COMPILE=aarch64-linux-gnu-
export CC=aarch64-linux-gnu-gcc
export LANG=C

# Compile the kernel into a deb package
fakeroot debian/rules clean binary-headers binary-rockchip do_mainline_build=true
```

**Comment by Joshua-Riek** [comment]
I'm trying to take a much needed break. Please send a pull request if you would like these changes incorporated into the kernel.
