### ISSUE TITLE
about OrangePi-5-Max M.2 PCIe Gen3 4Lane init failed

### ISSUE THREAD

**Issue by akioolin** [Joshua-Riek/ubuntu-rockchip#1071]
Hi, All:

I met the M.2 PCIe Gen3 4Lane initial problem  on OrangePi 5 Max + M.2 FPGA board.
Current Linux image is based on V 2.3.1, 1023. 
https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.3.1/ubuntu-24.04-preinstalled-server-arm64-orangepi-5-max.img.xz

Compare the output of kernel massage, pcie@fe150000 and pcie@fe180000, as showing below.

dw-pcie fe150000.pcie: invalid resource
dw-pcie fe150000.pcie: Failed to initialize host
dw-pcie: probe of fe150000.pcie failed with error -22
rk-pcie fe150000.pcie: invalid prsnt-gpios property in node
rk-pcie fe150000.pcie: Looking up vpcie3v3-supply from device tree
rk-pcie fe150000.pcie: host bridge /pcie@fe150000 ranges:
rk-pcie fe150000.pcie:       IO 0x00f0100000..0x00f01fffff -> 0x00f0100000
rk-pcie fe150000.pcie:      MEM 0x00f0200000..0x00f0ffffff -> 0x00f0200000
rk-pcie fe150000.pcie:      MEM 0x0900000000..0x093fffffff -> 0x0900000000
rk-pcie fe150000.pcie: iATU unroll: enabled
rk-pcie fe150000.pcie: iATU regions: 8 ob, 8 ib, align 64K, limit 8G
rk-pcie fe150000.pcie: PCIe Linking... LTSSM is 0x3
rk-pcie fe150000.pcie: PCIe Linking... LTSSM is 0x1
rk-pcie fe150000.pcie: PCIe Linking... LTSSM is 0xa
rk-pcie fe150000.pcie: PCIe Link Fail, LTSSM is 0xa, hw_retries=0
rk-pcie fe150000.pcie: PCIe Linking... LTSSM is 0x1
rk-pcie fe150000.pcie: PCIe Linking... LTSSM is 0xa
rk-pcie fe150000.pcie: PCIe Linking... LTSSM is 0xa
rk-pcie fe150000.pcie: PCIe Link Fail, LTSSM is 0xa, hw_retries=1
rk-pcie fe150000.pcie: failed to initialize host

and 

dw-pcie fe180000.pcie: invalid resource
dw-pcie fe180000.pcie: Failed to initialize host
dw-pcie: probe of fe180000.pcie failed with error -22
rk-pcie fe180000.pcie: invalid prsnt-gpios property in node
rk-pcie fe180000.pcie: Looking up vpcie3v3-supply from device tree
rk-pcie fe180000.pcie: Looking up vpcie3v3-supply property in node /pcie@fe180000 failed
rk-pcie fe180000.pcie: no vpcie3v3 regulator found
rk-pcie fe180000.pcie: host bridge /pcie@fe180000 ranges:
rk-pcie fe180000.pcie:       IO 0x00f3100000..0x00f31fffff -> 0x00f3100000
rk-pcie fe180000.pcie:      MEM 0x00f3200000..0x00f3ffffff -> 0x00f3200000
rk-pcie fe180000.pcie:      MEM 0x09c0000000..0x09ffffffff -> 0x09c0000000
rk-pcie fe180000.pcie: iATU unroll: enabled
rk-pcie fe180000.pcie: iATU regions: 8 ob, 8 ib, align 64K, limit 8G
rk-pcie fe180000.pcie: PCIe Linking... LTSSM is 0x3
rk-pcie fe180000.pcie: PCIe Link up, LTSSM is 0x130011
rk-pcie fe180000.pcie: PCIe Gen.2 x1 link up
rk-pcie fe180000.pcie: PCI host bridge to bus 0003:30

it seems the pcie@fe150000 initial failed. where do I have to adjust??

Many Thanks.

BR, Akio

**Comment by Joshua-Riek** [comment]
Works for me. Try installing your nvme drive or fix the issue yourself.
