### ISSUE TITLE
Feature Request: Support VRR on rockchip (Variable Refresh Rate)

### ISSUE THREAD

**Issue by gehee** [Joshua-Riek/ubuntu-rockchip#1086]
### Feature Description

There seems to be work being done on VRR support for rockchip:
https://lwn.net/Articles/989201/

Running drm-info on rk3588 (orange pi 5) shows that VRR is not enabled on the CRTCs.

Is it possible to enable VRR on ubuntu-rockchip or more work is needed in the kernel ?

**Comment by Joshua-Riek** [comment]
Fucking ask Rockchip.. But good like because I can't even reach them to continue development.
