### ISSUE TITLE
Feature Request: Could RK3566 (Orangepi3b) support ubuntu 22.04 with gnome

### ISSUE THREAD

**Issue by Pines** [Joshua-Riek/ubuntu-rockchip#1095]
### Feature Description

I have seen image running xfce ubuntu 22.04 undher Orangepi 3b.
wonder could ubuntu 22.04 with gnome works under Orangepi 3b

**Comment by nemanjam** [comment]
You have it here:

https://joshua-riek.github.io/ubuntu-rockchip-download/boards/orangepi-3b.html

**Comment by Pines** [comment]
thanks
