### ISSUE TITLE
Bug Report: Can't upgrade from 22.04.5 to 24.04. on a Server-Setup from April

### ISSUE THREAD

**Issue by mircsicz** [Joshua-Riek/ubuntu-rockchip#1103]
### What happened?

While running 'do-release-upgrade' I had to face the following error:

```
/bin/bash: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /bin/bash)
```

### Kernel version

5.10.160-rockchip

### SBC model

Orange Pi5 Plus (32GB)

### What operating system are you seeing this problem on?

Ubuntu 22.04 LTS (Jammy Jellyfish)

**Comment by Joshua-Riek** [comment]
I'll start by saying that from a software standpoint RK3588 is held together by glue and tape, it barely works. With the excessive number of hacks required for some hardware acceleration it's nearly impossible to create an upgrade path. While I can do it, I do not have time or funding, I'm a random person on the internet that does all this work for free. Unless someone wants to pay me to fix this I'm not going to.

Additionally, you are running an older system, I recommend a full re-install, I scrapped the 5.10.160-rockchip kernel.
