### ISSUE TITLE
Feature Request: Orange Pi 5 Pro SATA support

### ISSUE THREAD

**Issue by Falagard** [Joshua-Riek/ubuntu-rockchip#1121]
### Feature Description

First, thanks for your hard work. 

I have an Orange Pi 5 Pro that I'm trying to get to recognize an M2 SATA SSD. 

I was able to get it to work in Armbian Ubuntu Noble Gnome by using two overlays from here: 

https://github.com/orangepi-xunlong/linux-orangepi/tree/orange-pi-6.1-rk35xx/arch/arm64/boot/dts/rockchip/overlay
rk3588-ssd-sata0.dts and rk3588-ssd-sata2.dts

In Armbian there's a utility for adding overlays, but I'm not sure if those overlays would work in your version of Ubuntu. 

I did try several things: 

Following directions from here https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Ubuntu-24.04-LTS I tried using the orangepi-5-sata overlay to uboot even though the Orange Pi 5 Pro is a different SBC. 

Ack ignore me while I type this out better brb

**Comment by CanadianBaconBoi** [comment]
Hey, sorry to necro this. Do you mind sharing how you got this resolved @Falagard ?

**Comment by Falagard** [comment]
I didn't, I gave up. Sorry.
