### ISSUE TITLE
Fonts appear grey in Chromium (fonts which should appear black)

### ISSUE THREAD

**Issue by martinbone** [Joshua-Riek/ubuntu-rockchip#116]
I've noticed that on a lot of web pages (eg. Google Sheets) fonts that should appear black actually appear as light grey.

![Screenshot from 2023-04-13 17-23-23](https://user-images.githubusercontent.com/1616057/231823610-ec5d8ae4-c8ed-4ba6-9189-d4f4fd084c46.png)

If no-one else has this issue - don't worry. I understand it's early days of development. Thanks.

**Comment by diepquynh** [comment]
A quick fix for this I've found so far is to enable Raw Draw feature in Chromium, either by passing a `--enable-features=RawDraw` or just simply enable it in `chrome://flags`

**Comment by martinbone** [comment]
Excellent, thanks. Will try that.

**Comment by diepquynh** [comment]
There's another solution too if you don't care about 4k decoding, which is commenting out `CHROMIUM_FLAGS` in `/etc/chromium-browser/default`

This way makes Chromium return to default ANGLE renderer with Panfrost backend, and imo it's much more stable than using current EGL renderer, at the  cost of hardware codecs not working at all. Even so, watching a 1080p60 video on YouTube with SW codec looks pretty stable for me

**Comment by hubby4** [comment]
> A quick fix for this I've found so far is to enable Raw Draw feature in Chromium, either by passing a `--enable-features=RawDraw` or just simply enable it in `chrome://flags`

This worked for me. Thank you.
