### ISSUE TITLE
Installing "i386" dependencies

### ISSUE THREAD

**Issue by zer0s1x** [Joshua-Riek/ubuntu-rockchip#140]
Getting this error everytime i try to download some x86/x64 apps through box86/box64 since last month, still didn't figure out how to solve this. It's the i386 thing, everytime.

![image](https://github.com/Joshua-Riek/ubuntu-orange-pi5/assets/127637341/b69f9d24-7d09-4098-b1e8-3aa134e980f9)

**Comment by cantalupo555** [comment]
Try this:

`sudo dpkg --remove-architecture i386 && sudo apt-get update
`

https://github.com/Joshua-Riek/ubuntu-orange-pi5/issues/117

**Comment by zer0s1x** [comment]
It worked, lmao. Thanks
