### ISSUE TITLE
X Error of failed request

### ISSUE THREAD

**Issue by cantalupo555** [Joshua-Riek/ubuntu-rockchip#143]
Hello, I'm using version v1.11

I'm run Steam and several games and it still gives me this error:
`X Error of failed request:  BadWindow (invalid Window parameter)
`
In Armbian doesn't show this error.

I'm using box86 and box64.

**Comment by Joshua-Riek** [comment]
I think this is because the default display manager uses Wayland, not X11. Do you know how to switch between the two?

**Comment by cantalupo555** [comment]
> I think this is because the default display manager uses Wayland, not X11. Do you know how to switch between the two?

With X11 this log disappeared.
Thank you, this error log did not prevent box64 from working properly.

I went back to Wayland.
