### ISSUE TITLE
Ubuntu Server stuck in boot loop on SD

### ISSUE THREAD

**Issue by abapst** [Joshua-Riek/ubuntu-rockchip#154]
I'm trying to install Ubuntu server on a Rockchip 5B. After flashing the SD card and plugging in an HDMI display, a bunch of bootloader stuff flashes by really fast and then goes black before restarting. Any thoughts?

**Comment by Joshua-Riek** [comment]
Strange, give me a minute, and ill check on my end.

**Comment by abapst** [comment]
My bad, it was a power problem. Device needed to be plugged into the wall. Power delivered by USB over PC was not enough. Thanks for the quick response!

**Comment by Joshua-Riek** [comment]
Haha i see, glad you got it working!
