### ISSUE TITLE
Will it support the nanopc T6 device?

### ISSUE THREAD

**Issue by 990616682** [Joshua-Riek/ubuntu-rockchip#160]

**Comment by Joshua-Riek** [comment]
I reached out to FriendlyELEC as they were kind enough to send me the NanoPi R6S /R6C. Hopefully, they will be able to send me the T6. If not, it might be a month or two as I'll need to purchase the hardware for testing.

**Comment by Joshua-Riek** [comment]
I have a NanoPC-T6 on the way. It might be a few weeks before I receive it for development.

**Comment by Joshua-Riek** [comment]
I have an image now available for the NanoPC T6!
