### ISSUE TITLE
here is a possible upgrade script to enable updating installs without overwriting user data

### ISSUE THREAD

**Issue by develperbayman** [Joshua-Riek/ubuntu-rockchip#166]
`#!/bin/bash

#Download the custom Ubuntu image
wget -O custom_image.iso <URL_to_custom_image>

#Mount the ISO image
sudo mkdir /mnt/custom_image
sudo mount -o loop custom_image.iso /mnt/custom_image

#Extract the contents of the ISO image
sudo cp -r /mnt/custom_image/* /path/to/destination

#Unmount the ISO image
sudo umount /mnt/custom_image
sudo rm -r /mnt/custom_image

#Perform an upgrade on the installed image
sudo apt update
sudo apt upgrade -y

#Restart the system to apply changes (optional)
sudo reboot`

**Comment by develperbayman** [comment]
apparently thats what github does with #comments ....my bad

**Comment by EvilOlaf** [comment]
https://www.markdownguide.org/cheat-sheet/

**Comment by develperbayman** [comment]
also maybe for ease of install? maybe include zenity? 

`#!/bin/bash

# Prompt the user to select an installation location
echo "Select an installation location:"
echo "1. /dev/sda (HDD/SSD)"
echo "2. /dev/sdb (HDD/SSD)"
echo "3. /dev/sdc (HDD/SSD)"
echo "4. /dev/nvme0n1 (M.2 storage)"
read -p "Enter your choice: " location

case $location in
  1)
    install_location="/dev/sda"
    ;;
  2)
    install_location="/dev/sdb"
    ;;
  3)
    install_location="/dev/sdc"
    ;;
  4)
    install_location="/dev/nvme0n1"
    ;;
  *)
    echo "Invalid choice. Exiting."
    exit 1
    ;;
esac

# Prompt the user to confirm the installation location
read -p "Install Ubuntu image to $install_location? (y/n): " confirm_location

if [[ $confirm_location != "y" ]]; then
  echo "Installation canceled. Exiting."
  exit 1
fi

# Download the custom Ubuntu image
wget -O custom_image.iso <URL_to_custom_image>

# Mount the ISO image
sudo mkdir /mnt/custom_image
sudo mount -o loop custom_image.iso /mnt/custom_image

# Extract the contents of the ISO image to the chosen location
sudo cp -r /mnt/custom_image/* $install_location

# Unmount the ISO image
sudo umount /mnt/custom_image
sudo rm -r /mnt/custom_image

# Prompt the user to select the bootloader installation option
echo "Select bootloader installation option:"
echo "1. Install bootloader to SPI flash"
echo "2. Skip bootloader installation"
read -p "Enter your choice: " bootloader_option

case $bootloader_option in
  1)
    # Add commands to install the bootloader to the SPI flash
    echo "Installing bootloader to SPI flash..."
    ;;
  2)
    echo "Skipping bootloader installation."
    ;;
  *)
    echo "Invalid choice. Skipping bootloader installation."
    ;;
esac

echo "Installation complete."
`

**Comment by develperbayman** [comment]
idk why again .... but piss on it ....anyway i hope it helps spawn ideas

**Comment by EvilOlaf** [comment]
Use triple ` for multiple lines of code
```
Will look
like this
then
```

**Comment by Joshua-Riek** [comment]
Most changes will be in the kernel, bootloader, or firmware. I have a PPA to automatically distribute updates with a simple `apt upgrade` command. Other changes will be related to the pre-installed applications, which I don't see a need to push out to user-installed systems.

**Comment by develperbayman** [comment]
is this PPA operational

**Comment by Joshua-Riek** [comment]
Yes, the PPA is included by default. However, the most recent kernel (5.10.160) will require a new install because there are a lot of changes.

**Comment by Gluk41** [comment]
> Yes, the PPA is included by default. However, the most recent kernel (5.10.160) will require a new install because there are a lot of changes.

How can I update the kernel without reinstalling the system?

**Comment by Joshua-Riek** [comment]
The kernel can be updated with a simple apt update and upgrade.
```bash
sudo apt update
sudo apt upgrade
```

**Comment by Gluk41** [comment]
![Screenshot_20230604-214000](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/17955884/1109e821-72ae-43e8-94b0-e062c027c9fc)

**Comment by Joshua-Riek** [comment]
Oh, updating the kernel from 5.10.110 to 5.10.160 does not work. There were too many changes and installing the new kernel would break the system.

**Comment by Gluk41** [comment]
How to upgrade to a new version of the system without reinstalling?

**Comment by Joshua-Riek** [comment]
Updates will be distributed for the kernel, bootloader, and firmware to bring each install up to the latest version. However, you have an older version which I can no longer distribute kernel updates to.

**Comment by Gluk41** [comment]
I understand it. The question is, how do I update an existing installation without reinstalling? I installed the previous version, configured and launched all the services I needed in it. All this took me about a week of work. After reading the annotation to the system, I was sure that you would update the system with a ppa. What should I do now? Reinstall all services for another week? And where is the guarantee that I won't have to do it again for the next update?

**Comment by Joshua-Riek** [comment]
I do not guarantee anything, and this is a side project that I have invested a lot of time into. I don't get paid for anything done here, and I'm not obligated to do anything. If you are unhappy with something, feel free to contribute.

I'm trying to offer an alternative to the poorly designed vendor Operating Systems and will give users a familiar Ubuntu experience. The PPA is a way to distribute updates, but I made a few errors that do not allow updating from 5.10.110 to 5.10.160.

**Comment by Gluk41** [comment]
You didn't understand - I don't blame you, I really like your work! You are the only one who has done Ubuntu well for Orange Pi and I am happy to use your build! It works great! I just want to find an easy way to upgrade... Is the inability to update related to the Orange PI loader? Can I somehow change it in the EFI build?
