### ISSUE TITLE
USB 2 vertical not working

### ISSUE THREAD

**Issue by zmrasim** [Joshua-Riek/ubuntu-rockchip#168]

**Comment by arun-511** [comment]
Do you have something connected with the USB 3.0 Type C port?

**Comment by Joshua-Riek** [comment]
I double checked and the vertical USB 2.0 port works fine for me. If you are using the USB-C port the USB 2.0 might not work. This is how the hardware was designed.

**Comment by Joshua-Riek** [comment]
You can also try to manually enable the vertical USB 2.0 port with the below command.
```bash
echo host | sudo tee /sys/kernel/debug/usb/fc000000.usb/mode
```
