### ISSUE TITLE
Error: Your GPU may not support OpenGL 4.3

### ISSUE THREAD

**Issue by HairAndCode** [Joshua-Riek/ubuntu-rockchip#170]
![截图 2023-05-30 21-24-30](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/74373458/5139ce76-6d51-49d1-8398-b426093eab24)
My board is OrangePI 5. I compiled citra, and when I open a game, it shows GPU may not support OpenGL 4.3. I have compiled citra on Debian that OrangePI official website provide before, it can run but only 20fps. So, I want to recompile on this Ubuntu, desiring a better performance. What can I do to let GPU support OpenGL 4.3+?

**Comment by Joshua-Riek** [comment]
Try to run Citra with the `MESA_GL_VERSION_OVERRIDE=4.4` and  `MESA_GLSL_VERSION_OVERRIDE=440` env vars. But please note that OpenGL 4.3 is not supported. However, using the above env vars is a hack to work around this.

Run Citra something like this:
```
MESA_GL_VERSION_OVERRIDE=4.4 MESA_GLSL_VERSION_OVERRIDE=440 ./citra-qt
```
