### ISSUE TITLE
Booting from NVME Does not work - Rock5b

### ISSUE THREAD

**Issue by xxxsskxxx** [Joshua-Riek/ubuntu-rockchip#172]
Hi

Thanks for building this.

I installed the Rock5b image to an EMMC and booted absolutely fine

I used the guidance here:-

https://wiki.radxa.com/Rock5/install/nvme

To format the SSD and install your image to the SSD.

I also flashed the SPI:-

https://wiki.radxa.com/Rock5/install/spi

MD5 all checked out fine.

But. Get stuck on a blue LED and it does not boot.

Any ideas on what could be the issue. I've seen other open issue talking about getting it serially connected to grab errors. 

I will try and do this.

I'm using a Samsung 970 Evo Plus 2TB NVME SSD directly connected to the board.

**Comment by Joshua-Riek** [comment]
I have not had time to test booting from an NVMe yet on the Rock 5B. I'll look into this shortly.

**Comment by Joshua-Riek** [comment]
I have no issue booting from an NVMe on my end.

To flash the SPI:
```
sudo dd if=/lib/u-boot-radxa-rk3588/rkspi_loader.img of=/dev/mtdblock0 conv=notrunc
```

Then I created my NVMe like below:
```
wget https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v1.16/ubuntu-22.04.2-preinstalled-desktop-arm64-rock5b.img.xz
xz -dc ubuntu-22.04.2-preinstalled-desktop-arm64-rock5b.img.xz | sudo dd of=/dev/nvme0n1 bs=4k
```

**Comment by Joshua-Riek** [comment]
My guess the SPI image from Radxa might be old/outdated. The SPI image mentioned above is one I compiled.

**Comment by xxxsskxxx** [comment]
Thanks, where can we get your SPI?

**Comment by Joshua-Riek** [comment]
It's included in my ubuntu image and is packaged on my ppa. But here is a direct download. 
[rkspi_loader.zip](https://github.com/Joshua-Riek/ubuntu-rockchip/files/11604737/rkspi_loader.zip)

**Comment by Joshua-Riek** [comment]
I updated the wiki page with more information about this process. I still plan on adding more details, but hopefully, it will help others. 

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Rock-5

**Comment by xxxsskxxx** [comment]
Thanks, all resolved now, just a tip for users, dont follow Radxa guide, simply follow the wiki for the Rock 5B here otherwise you wont be able to boot with an NVME connected until you format the SSD.

Load the Ubuntu image to your SD Card or EMMC
Connect to ROck 5B and power on
Flash the SPI first as per the Wiki (https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Rock-5)
Format the NVME (i did this to ensure my SSD weas clean / https://nvmexpress.org/open-source-nvme-management-utility-nvme-command-line-interface-nvme-cli/ - 2.4 is available as of time of writing)
Run the following to download and install the image to the NVME:-
wget https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v1.16/ubuntu-22.04.2-preinstalled-desktop-arm64-rock5b.img.xz
xz -dc ubuntu-22.04.2-preinstalled-desktop-arm64-rock5b.img.xz | sudo dd of=/dev/nvme0n1 bs=4k

Power Off
Remove EMMC or SD card
Power on ROck 5b and you will boto Ubuntu from the NVME only.

Thanks!

**Comment by 000xxx** [comment]
> It's included in my ubuntu image and is packaged on my ppa. But here is a direct download. [rkspi_loader.zip](https://github.com/Joshua-Riek/ubuntu-rockchip/files/11604737/rkspi_loader.zip)

Thank you for advice!

Please update wiki, there is wrong path:
Wiki info:
```
if=/lib/u-boot-orangepi-rk3588/rkspi_loader.img
```

```
root@ubuntu:~# find / -name rkspi_loader.img
/usr/lib/u-boot-orangepi-rk3588/rkspi_loader.img
```

Might be worth to mention that file is present in Ubuntu image.

**Comment by Joshua-Riek** [comment]
The path `/lib/` is linked to `/usr/lib/`, so both should work. But I see the confusion and will update the path.
