### ISSUE TITLE
cannot build this DKMS driver

### ISSUE THREAD

**Issue by omikron88** [Joshua-Riek/ubuntu-rockchip#174]
Hello,
I have problem to build this DKMS driver, but it works at other aarch64, such as Pi4.
https://github.com/tsduck/hides-drivers.git
It seems like kernel version conflicts.

How can I build it?

To reproduce this error:
sudo apt install build-essential dkms libelf-dev zlib1g-dev git
git https://github.com/tsduck/hides-drivers.git
cd hides-drivers/linux-drivers
make

it creates the ./packages/hides-dkms_version_all.deb

sudo dpkg -i  packages/hides-dkms_18.04.16.2w_all.deb

the compilation ends with error and the report is in /var/lib/dkms/hides/18.04.16.2w/build/make.log

**Comment by Joshua-Riek** [comment]
I took a look at the driver and it will be difficult to port over to the rockchip kernel for a number of reasons. I would recommend using a dongle that is known to work like the one linked below.

https://www.amazon.com/Bluetooth-Adapter-Wireless-External-Receiver/dp/B07YDFZWT8/ref=sr_1_7?crid=2OY84Z5Y4ZX9O&keywords=rtl8811cu&qid=1685736203&sprefix=rtl8811cu+%2Caps%2C121&sr=8-7
