### ISSUE TITLE
DWA-181 AC1300 driver 

### ISSUE THREAD

**Issue by tomdoof** [Joshua-Riek/ubuntu-rockchip#177]
Hello, I have a orange pi 5 with a DWA-181 AC1300 usb wifi adapter and I am having issues getting it to work. It does work with armbian but I would love to get it working on your ubuntu version also, I tried to install the driver but failed(I'm very new to linux sorry) so I hope this will be supported in future releases if you have the time.

**Comment by Joshua-Riek** [comment]
I added the driver to the kernel. However, I don't have that wifi adapter to test if it works. I will close this for now, but please feel free to open it again if there are more issues. You can expect a kernel update distributed through apt with the changes or a new release early next week or over the weekend.
