### ISSUE TITLE
Build instruction on Wiki misses bc package

### ISSUE THREAD

**Issue by juergenpf** [Joshua-Riek/ubuntu-rockchip#182]
I followed the guidance on the Wiki to setup a build environment. I used an x86_64 based Ubuntu-22.04 (actually running in WSL2 on Windows) and all worked fine, I could build the images for orangepi5plus (still waiting for the board).
There was only one minor issue that the first attempt to build failed, because the bc utility was not found. You should add the bc package to the list of required packages.

**Comment by Joshua-Riek** [comment]
Got it, thanks for letting me know!

**Comment by Joshua-Riek** [comment]
Wiki is updated, thanks!
