### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by EvilOlaf** [Joshua-Riek/ubuntu-rockchip#187]
Hey there,

just tried to build an image from most recent commit (https://github.com/Joshua-Riek/ubuntu-rockchip/commit/ddcd11c2b479235cdf653188ac1a5f626b7c084e) but failed.
Started with `./build.sh --board=orangepi5`

resulted in 

```
Error: missing kernel debs, please run build-kernel.sh
Error: in ./build.sh on line 127
```

Tried running `build-kernel.sh` manually which seem to be successful and restarted the whole build but ran into the same message.

Cheers

**Comment by Joshua-Riek** [comment]
I'm in the middle of cleaning up the kernel packaging and sending pull requests to sync with the Armbian rockchip kernel where appropriate. There might be some issues. I had a build run on my server last night with this commit, and it had no problems. Ill start a local build and see if i run into any issues.

**Comment by EvilOlaf** [comment]
Right, will try that asap.

**Comment by EvilOlaf** [comment]
What I noticed during building (FYI):

- there was an error with `camera-engine-rkaiq_rk3588_arm64.deb`. I put the whole build log into a file linked below.

- something in `build-image.sh` failed:

```bash
[...]
Warning: root device  does not exist
4096+0 records in
4096+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.0179716 s, 117 MB/s

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition number (1,2, default 2): Partition type or alias (type L to list all): 
Changed type of partition 'Microsoft basic data' to 'Linux extended boot'.

Command (m for help): Partition number (1,2, default 2): Partition type or alias (type L to list all): 
Changed type of partition 'Linux filesystem' to 'Linux filesystem'.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Invalid argument

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or partx(8).

Error: in ../scripts/build-image.sh on line 119
mkfs.fat 4.2 (2021-01-31)
[...]
```

Had some trouble with common paste services due to the size of ~ 32k lines
https://fi.mirror.armbian.de/.testing/build.log.txt

Had no chance to test the built image. Will do that later.

**Comment by EvilOlaf** [comment]
Image seem to work just fine.

**Comment by EvilOlaf** [comment]
Closing since `--clean` fixed the main issue.
