### ISSUE TITLE
Support MT7921k

### ISSUE THREAD

**Issue by vaaliferov** [Joshua-Riek/ubuntu-rockchip#191]
Is it possible to install driver for MediaTek MT7921k wireless network card ?

**Comment by Joshua-Riek** [comment]
The minimum kernel version that supports the MT7921 is 5.12. Currently, the kernel is stuck at 5.10. So there is not much I can do about this, sadly.

https://wireless.wiki.kernel.org/en/users/drivers/mediatek?s%5B%5D=mediatek&s%5B%5D=mt7921
