### ISSUE TITLE
Why is the www-data user locked?

### ISSUE THREAD

**Issue by iRaizenn** [Joshua-Riek/ubuntu-rockchip#196]
when i run sudo passwd -S www-data
it returns this:
`www-data L 05/04/2023 0 99999 7 -1`

the 'L' means that it is locked, and if i were to unlock it using `sudo usermod -U www-data` then it stays locked

**Comment by Joshua-Riek** [comment]
www-data is not a default user or group from my understanding. Maybe you need to create the user?

**Comment by iRaizenn** [comment]
> www-data is not a default user or group from my understanding. Maybe you need to create the user?

I am using a web server that NEEDS to execute a php file with the www-data user

**Comment by iRaizenn** [comment]
> Try running your php file like this `sudo -u www-data php script.php`, the password should be the same as root.

no it is not.

**Comment by Joshua-Riek** [comment]
I have the same result for the www-data user on my Ubuntu laptop. You need to configure the www-data user yourself. 
```bash
joshua@GS66-Stealth-11UE:~$ uname -a
Linux GS66-Stealth-11UE 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
joshua@GS66-Stealth-11UE:~$ sudo passwd -S www-data
www-data L 08/19/2021 0 99999 7 -1
```

**Comment by iRaizenn** [comment]
www-data is for Apache web servers only. you just created a new user named www-data

**Comment by Joshua-Riek** [comment]
I did not create any www-data user to my knowledge. If there are user permission issues, delete the user and create a new one with the expected permissions you require.
