### ISSUE TITLE
Updated fsck tools?

### ISSUE THREAD

**Issue by craigcarnell** [Joshua-Riek/ubuntu-rockchip#204]
I have plugged an external hard disk to my Orange Pi 5B using a USB enclosure.

The drive is formatted as ext4 using Ubuntu 23.04.

The version of fsck in Ubuntu 23.04 is from util-linux 2.38.1.

When I try to mount the disk automatically on my Orange Pi 5B using /etc/fstab I get the following error:

```
/dev/xxx has unsupported feature(s): FEATURE_C12
```

Is there anyway to update the fsck tool in ubuntu-rockchip?

The version included is fsck from util-linux 2.37.2

**Comment by Joshua-Riek** [comment]
This looks like an issue with Ubuntu and is not something I can assist with. You can try to get the util-linux 2.38.1 source and compile it yourself. Or migrate the data on your hard drive and format it using a Ubuntu 22.04 host system.

**Comment by craigcarnell** [comment]
Thanks
