### ISSUE TITLE
Build fails for orangapi5plus

### ISSUE THREAD

**Issue by juergenpf** [Joshua-Riek/ubuntu-rockchip#205]
I did a
$ sudo ./build.sh --board=orangepi5plus

and this results now in this (last 5 lines of outut):
I: Retrieving zlib1g 1:1.2.11.dfsg-2ubuntu9
I: Validating zlib1g 1:1.2.11.dfsg-2ubuntu9
E: Couldn't download packages: liblz4-1
Error: in ./scripts/build-rootfs.sh on line 40
Error: in ./build.sh on line 126

My environment is a Ubuntu-22.04 under WSL2, the build worked until rename of u-boot packages.

**Comment by juergenpf** [comment]
I can reproduce this, on different build environments, but all on the same network. To me this looks very much like a networking issue as the failure in debootstrap happens on different files in different runs. It could well be then that you can't reproduce because your network requests take a different route than mine.
I fixed this by using the --cache-dir option for debootstrap in the build-rootfs.sh script. So if the call fails due to a networking issue it has populated the cache and when I restart the build it kind of restarts debootstrap where it was interrupted. Not perfect, because it requires more than one run for a successfull build, but it works for me.

**Comment by Joshua-Riek** [comment]
Hmm, it does sound like a network issue. But I can do little about this since I can not reproduce it in a local environment.
