### ISSUE TITLE
USB not working

### ISSUE THREAD

**Issue by awir3** [Joshua-Riek/ubuntu-rockchip#210]
Im using NanoPC T6 , both USB-C and USB-A not working cant use keyboard or mouse

**Comment by Joshua-Riek** [comment]
I'll look at this now.

**Comment by Joshua-Riek** [comment]
On my NanoPC T6 both USB-C and USB-A ports are working and can find my mouse and keyboard. Have you test if the two ports work using another OS?

**Comment by awir3** [comment]
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/81795837/9421161a-6928-4c18-9898-19c5230659f6)

**Comment by awir3** [comment]
> On my NanoPC T6 both USB-C and USB-A ports are working and can find my mouse and keyboard. Have you test if the two ports work using another OS?


Both USB-C and USB-A work just fine with another OS. It seems that both ports are disconnected nothing work

**Comment by Joshua-Riek** [comment]
Both USB-C and USB-A work fine for me. Maybe you have a hardware issue with the NanoPC T6?

**Comment by awir3** [comment]
> Both USB-C and USB-A work fine for me. Maybe you have a hardware issue with the NanoPC T6?

I've tested different types of official FriendlyElec OS and both USB ports work fine.

**Comment by Joshua-Riek** [comment]
I will look at the source code from FriendlyElec and see if I can find any differences. Maybe there are some changes I forgot to add.

**Comment by awir3** [comment]
> changes


I just fix it and it works just fine 

Edit the file ubuntuEnv.txt and change rk3588s-nanopi-r6s.dtb to rk3588-nanopc-t6.dtb

**Comment by Joshua-Riek** [comment]
I'm glad it's working for you now!
