### ISSUE TITLE
How to configure UART to device connected to rx and tx ports

### ISSUE THREAD

**Issue by bulganbaev** [Joshua-Riek/ubuntu-rockchip#212]

**Comment by Joshua-Riek** [comment]
Could you provide some information here? What device are you using, and do you want to get a serial console output?

**Comment by bulganbaev** [comment]
I am using Orange Pi 5 plus,  I have connected device to ports 6,8 and 10. In Raspberry PI previously i just enabled uart in raspi-config. Is there ways to enable it in Orange pi 5 plus using your image?

**Comment by Joshua-Riek** [comment]
You must add a device tree overlay to enable UART for your pins. Please take a look at the wiki below on how to do that.
https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Device-Tree-Overlays

I don't know the pinout of the GPIO, so I don't know which overlay you will need to use. Take a look at the schematics and you should be able to find which overlay you need to use.
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/10427125/464d18bc-5638-402a-9249-af1a1dacf168)
