### ISSUE TITLE
Orange Pi 5B wifi connection issues

### ISSUE THREAD

**Issue by Zartris** [Joshua-Riek/ubuntu-rockchip#217]
Just installed the new v1.18 (have not tested older versions), and i cannot connect to any wifi networks.
I have tried to connect to the wifi with the original android OS and it worked perfectly fine, however after installing this, im getting an the "Authentication required, Password or encryption keys are required to access the wireless network." but I have put in the correct information.

**Comment by Joshua-Riek** [comment]
Did you choose to have your desktop auto-login? You might need to set up the keyring.
