### ISSUE TITLE
Orange Pi 5 Plus: Webcam Video Input Not Detected

### ISSUE THREAD

**Issue by ggdk123** [Joshua-Riek/ubuntu-rockchip#220]
Logitech C922 Pro doesn't show up as video input  device in V4L2 Test Utility, but does appear in audio input device.

**Comment by ggdk123** [comment]
Tried both USB 2 and 3 ports, BTW

**Comment by Joshua-Riek** [comment]
This is not something I can help with. I don't have that webcam; if I did, there are other more critical issues, like trying to work out some audio and HDMI bugs. This project is getting larger than intended so it's hard for me to assist with every issue like this now. 

However, at a quick glance, i found this and it might assist: https://linux-hardware.org/index.php?id=usb:046d-085c

**Comment by ggdk123** [comment]
my apologies
