### ISSUE TITLE
Root

### ISSUE THREAD

**Issue by Gazgiza** [Joshua-Riek/ubuntu-rockchip#226]
Hello, I can't give to my account the rights of root (not sudo, the rights) to execute sudo commands (as sudo apt-get update) without sudo.
Any idea to help me?

**Comment by Joshua-Riek** [comment]
You can't execute arbitrary admin commands without either using sudo or being root.

**Comment by Joshua-Riek** [comment]
But you can add an alias to some commands so you don't need to type sudo yourself.

https://unix.stackexchange.com/questions/276474/how-can-i-execute-any-command-as-a-normal-user-without-sudo#:~:text=Short%20answer%3A%20You%20can%27t%20execute%20arbitrary%20admin%20commands,add%20a%20line%20username%20ALL%3D%20%28ALL%29%20NOPASSWD%3A%20ALL
