### ISSUE TITLE
Crashes in chromium

### ISSUE THREAD

**Issue by cantalupo555** [Joshua-Riek/ubuntu-rockchip#230]
Problem encountered when switching to X11, chromium has constant crashes, very slow.
Any open video becomes stop motion.

Is X11 no longer supported efficiently?

**Comment by Joshua-Riek** [comment]
X11 has a lot of issues with the current GPU drivers, wayland is both more stable and performs better overall.  However, wayland does have its quirks like your other issue with armcord remote sharing. There is not much I can do here.

**Comment by cantalupo555** [comment]
I completely understand, I hope that Discord will support Wayland in the future.

I flew to Wayland and got the best performance.

Thanks.
