### ISSUE TITLE
Any support for PREEMPT-RT kernel ?

### ISSUE THREAD

**Issue by anslex** [Joshua-Riek/ubuntu-rockchip#237]
Hello,

It's more a question rather than an issue. 
How can one compile RT image ? 

Thanks!

**Comment by Joshua-Riek** [comment]
I don't know what an RT kernel is. Real-Time?

**Comment by Joshua-Riek** [comment]
I looked a little into Real-Time kernels, and this is not something I would work on. The current kernel is a mess forked from Android. You will need to wait for the mainline kernel to be fully supported before someone can attempt this with reasonable effort.

**Comment by anslex** [comment]
Hi, 
I totally understand, thank you for your response!
I will try to install RT patch when I receive the hardware

Best,

**Comment by wanyingwe** [comment]
> Hi, I totally understand, thank you for your response! I will try to install RT patch when I receive the hardware
> 
> Best,

Hello, Did you succeed? I have the same question.

**Comment by MattiaGrigoli** [comment]
@anslex have you done it? i'm working on it and i'm not finding anything that works
