### ISSUE TITLE
Orange Pi 5 Plus PWM Enabled by default?

### ISSUE THREAD

**Issue by smjltd** [Joshua-Riek/ubuntu-rockchip#238]
As per the documentation below

[orangepiwiki](http://www.orangepi.org/orangepiwiki/index.php/Orange_Pi_5_Plus#PWM_test_method)

it suggest to enable pwm by using `sudo orangepi-config`

is there a way to enable pwm, i can see there are overlays present in this path.
`ls /boot/firmware/dtbs/overlays`

but missing more than 2 pwmchipx
`ls /sys/class/pwm/`

**Comment by Joshua-Riek** [comment]
I don't have a config tool like orangepi-config yet. You must specify the device tree overlays related to PWM in the file /boot/firmware/ubuntuEnv.txt. Please see the below wiki page for an example and more information.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Device-Tree-Overlays

**Comment by smjltd** [comment]
Thank you

**Comment by ferrellsl** [comment]
Correct me if I'm wrong, but isn't the orangepi-config just a script? If so, it should be trivial to copy or replicate it. 
    On Saturday, July 1, 2023 at 07:15:11 AM MST, Joshua Riek ***@***.***> wrote:  
 
 


I don't have a config tool like orangepi-config yet. You must specify the device tree overlays related to PWM in the file /boot/firmware/ubuntuEnv.txt. Please see the below wiki page for an example and more information.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Device-Tree-Overlays
