### ISSUE TITLE
[Rock 5B] Boot from nvme

### ISSUE THREAD

**Issue by ac8085** [Joshua-Riek/ubuntu-rockchip#241]
Booting from nvme doesn't work for me even write image rock-5b-spi-image-gbf47e81-20230607.img into SPI.

**Comment by Joshua-Riek** [comment]
It should work fine. I would not use the official SPI image. Use the one included in the OS. Please see the wiki on how to flash the SPI.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Radxa-ROCK-5B#install-the-bootloader-to-the-spi-nor-flash

**Comment by Joshua-Riek** [comment]
I double-checked on my end, and booting from the NVMe works.

**Comment by ac8085** [comment]
Yes, it works with image you tell me.
Thank you.
