### ISSUE TITLE
Orange Pi 5b - Night light / redshift not working

### ISSUE THREAD

**Issue by ReidCole** [Joshua-Riek/ubuntu-rockchip#244]
I'm trying to use a blue light filter application like gnome's built-in night light or redshift, but I don't see any changes when moving the night light slider or setting the redshift color temperature. Any help is appreciated.

**Comment by Joshua-Riek** [comment]
I checked this out, and it's an issue with the wayland display manager and not something I can fix. However, it does work when switching the display manager to x11. But that introduces many new issues, as x11 is a mess regarding the GPU drivers on this device.
