### ISSUE TITLE
Orange Pi 5 onboard microphone is not working

### ISSUE THREAD

**Issue by bmecdev** [Joshua-Riek/ubuntu-rockchip#247]
no input device on orange pi 5, the onboard microphone is not detected.

              ![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/49051637/9b84a4b8-c275-4558-b574-2aeb480c8a95)

_Originally posted by @bmecdev in https://github.com/Joshua-Riek/ubuntu-rockchip/issues/198#issuecomment-1620857337_

**Comment by Joshua-Riek** [comment]
Right, another dev helped me get the audio jack working, which can be used for a headset and microphone input. But the onboard microphone has not been fixed yet.

**Comment by Joshua-Riek** [comment]
I don't plan on fixing this. Just use the audio jack.
