### ISSUE TITLE
M.2 Crashes

### ISSUE THREAD

**Issue by pbattin** [Joshua-Riek/ubuntu-rockchip#250]
Have an Orange Pi 5 Plus and I cannot get it to boot from the m.2 drive. 

During start it freezes and crashes a few times before loading the set up screen. But then it will also crash when setting up.

If it gets passed set up phase and it restarts, it will not boot properly and is showing errors on boot. 

The SD card flashed the same way loads just fine though. Tried different ways to install it and no luck. 

Any ideas what's special about installing the image on a m.2?

**Comment by Joshua-Riek** [comment]
It sounds like your board might not be getting enough power. Are you using a 5v 4a power supply?

**Comment by pbattin** [comment]
> It sounds like your board might not be getting enough power. Are you using a 5v 4a power supply?

Ahh, seems like I'm only using a 3.6A power supply right now. I'll try one with more than 4A

**Comment by pbattin** [comment]
> > It sounds like your board might not be getting enough power. Are you using a 5v 4a power supply?
> 
> Ahh, seems like I'm only using a 3.6A power supply right now. I'll try one with more than 4A

Updated the power supply and it resolved my issues it seems. Thanks for the quick reply!

**Comment by Joshua-Riek** [comment]
Awesome! Glad to hear it's working!
