### ISSUE TITLE
hope to introduce rtl8188EUS driver

### ISSUE THREAD

**Issue by SESProMax** [Joshua-Riek/ubuntu-rockchip#267]
I have a usb wifi adaptor comfast CF-WU810N. It can not work on this OS. It use rtl8188EUS, so I think its driver can be added in system.

**Comment by Joshua-Riek** [comment]
I will take a look, some wifi drivers are easier to implement than others.

**Comment by Joshua-Riek** [comment]
I should be able to add this driver to the kernel, and I see no issues at a glance. I will try to add this over the weekend.

**Comment by SESProMax** [comment]
Thankyou.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Joshua ***@***.***>
发送时间: 2023年7月21日 10:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Joshua-Riek/ubuntu-rockchip] hope to introduce rtl8188EUS driver (Issue #267)


I should be able to add this driver to the kernel, and I see no issues at a glance. I will try to add this over the weekend.

―

**Comment by Joshua-Riek** [comment]
I added the driver to the kernel https://github.com/Joshua-Riek/linux-rockchip/commit/555c135525e09e83fcf20ae3655fddeda5c68ac3. It should be working when I release the next kernel update.

**Comment by SESProMax** [comment]
Does this OS support OTA through apt？

发件人: Joshua ***@***.***>
发送时间: 2023年7月23日 23:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Joshua-Riek/ubuntu-rockchip] hope to introduce rtl8188EUS driver (Issue #267)


I added the driver to the kernel ***@***.***<https://github.com/Joshua-Riek/linux-rockchip/commit/555c135525e09e83fcf20ae3655fddeda5c68ac3>. It should be working when I release the next kernel update.

―

**Comment by Joshua-Riek** [comment]
Yes, this OS supports OTA updates.
