### ISSUE TITLE
Wazuh Install failing (not 64 bit?)

### ISSUE THREAD

**Issue by SignalMedic** [Joshua-Riek/ubuntu-rockchip#269]
https://documentation.wazuh.com/current/quickstart.html

Ran this install script and it failed, claiming that it must be run on a 64-bit system. 

Orange Pi 5, Samsung 512GB NVMe, 1.20 server booting from SSD.

**Comment by Joshua-Riek** [comment]
Maybe the x86_64 version was installed. Try to download the aarch64 versions for ubuntu.

https://documentation.wazuh.com/current/installation-guide/packages-list.html

**Comment by Joshua-Riek** [comment]
I look at the download script; it is only for x86_64 system, not arm64. 

```bash
# ------------ checks.sh ------------ 
function checks_arch() {

    arch=$(uname -m)

    if [ "${arch}" != "x86_64" ]; then
        common_logger -e "Uncompatible system. This script must be run on a 64-bit system."
        exit 1
    fi
}
```

**Comment by SignalMedic** [comment]
I'm in idiot. Thanks

**Comment by Joshua-Riek** [comment]
Nah, simple mistake!
