### ISSUE TITLE
Startup encounters installer crash

### ISSUE THREAD

**Issue by Esxxlx** [Joshua-Riek/ubuntu-rockchip#275]
Hello, I fork your project to adapt my board "rk3588-wkp-r4.dts". You use the construction script to complete the compilation according to the t6 adaptation method, and it runs smoothly.
![Screenshot 2023-07-24 16-07-11](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/104299793/504e956e-8902-4fd7-80a4-762dd0e886dc)

Now the problem is: after flashing the machine, start and run the installer, and after a while, it prompts that the installer crashes. I have tried various methods and have not found a solution. I hope you can help me solve the problem, 
thank you

**Comment by Joshua-Riek** [comment]
The model name defined in your device tree needs to be added to the flash-kernel package. I would be happy to add it if you can tell me the model name.

**Comment by Esxxlx** [comment]
Thank you very much, here are 2 devices in my hand.
```
	model = "WUKONG WRP R4";
	compatible = "wukong,wkp-r4", "rockchip,rk3588";
```
```
	model = "HINLINK H88K MAX";
	compatible = "hinlink,h88k-max", "rockchip,rk3588";
```

**Comment by Esxxlx** [comment]
Thank you so much! Report back to you after waiting a few hours and testing again

**Comment by Esxxlx** [comment]
Problem solved, thanks again for your help!
