### ISSUE TITLE
Support for RK3566?

### ISSUE THREAD

**Issue by a632878** [Joshua-Riek/ubuntu-rockchip#281]
Would love to see support for this chip. It is very limited in distros and functionality in the linux space.

**Comment by Joshua-Riek** [comment]
I may support a select few RK3566 boards, but I have not looked too deep into what is available. I must be careful as my computing and storage resources are limited. It currently takes 20GB and 4 hours per build on my server. I have been getting some donations, which have been a massive help as hardware and upgrades are expensive.
