### ISSUE TITLE
wired network dont work on rock5a

### ISSUE THREAD

**Issue by dongxuanlb** [Joshua-Riek/ubuntu-rockchip#284]
I flashed the latest version v1.21 img to emmc with rock5a, found that the wired network is failed to connet.

**Comment by dongxuanlb** [comment]
During system installation, the wired network appears to be connecting, but eventually fails. After the system is installed, enter the system, and the performance is the same.
The wireless network is normal. If you manually connect to the wired network, there will be a certain probability of success. No rule has been found so far.

**Comment by Joshua-Riek** [comment]
I did a test and did not find this issue. Please check your network connection and settings.
