### ISSUE TITLE
how to upgrade the os image?

### ISSUE THREAD

**Issue by IsQiao** [Joshua-Riek/ubuntu-rockchip#292]
I use the command to upgrade os, but os is down.
```
xz -dc ubuntu-22.04.2-preinstalled-desktop-arm64-orangepi-5.img.xz | sudo dd of=/dev/nvme0n1 bs=4k
sync
```
so, how to upgrade the os image?

**Comment by Joshua-Riek** [comment]
To update your os, you can simply enter the below commands. 
```
sudo apt update
sudo apt upgrade
```
There is no need to re-install your OS.
