### ISSUE TITLE
[Orange Pi 5-Plus][Release 1.21] docker macvlan can't run well

### ISSUE THREAD

**Issue by aisyun** [Joshua-Riek/ubuntu-rockchip#297]
run well:
`docker network create --driver macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=enP3p49s0 macnet`

can't run well: 
`docker run --restart always --name openwrt -d --network macnet --privileged 
sulinggg/openwrt:armv8 /sbin/init`

I have changed to armbian or orangePi releases are test well.

**Comment by Joshua-Riek** [comment]
I need more information here, simply saying that a docker command does not run well gives me little information on what the problem is.

**Comment by aisyun** [comment]
docker run --restart always --name openwrt -d --network macnet --privileged sulinggg/openwrt:armv8 /sbin/init
0cd8a0cd3aaa14444ba1366d95eb9df93d3df2b88017c950ec1d529b231dec76
docker: Error response from daemon: failed to create the macvlan port: operation not supported.

**Comment by aisyun** [comment]
> I need more information here, simply saying that a docker command does not run well gives me little information on what the problem is.

docker run --restart always --name openwrt -d --network macnet --privileged sulinggg/openwrt:armv8 /sbin/init
0cd8a0cd3aaa14444ba1366d95eb9df93d3df2b88017c950ec1d529b231dec76
docker: Error response from daemon: failed to create the macvlan port: operation not supported.

**Comment by Joshua-Riek** [comment]
Try running your commands with sudo? The macvlan driver is enabled in the kernel.

**Comment by aisyun** [comment]
> Try running your commands with sudo? The macvlan driver is enabled in the kernel.
thanks! it is runnig with modprobe the macvlan module.
