### ISSUE TITLE
ax210 loses its ip on rock-5b

### ISSUE THREAD

**Issue by iamryanchia** [Joshua-Riek/ubuntu-rockchip#298]
Hi, thanks for your help to make the ax210 work on rock-5b.

I have noticed another issue recently. The device  disconnects from wifi sometimes. If checking with `ip addr` command, the wireless network card has no ip address. Unfortunately, I haven't found any solutions to recover from this problem other than rebooting the device.

Do you have any suggestions for debugging? Thank you!

**Comment by iamryanchia** [comment]
I found it is caused by my router reboot. Is there any way to reconnect after the disconnection?

**Comment by Joshua-Riek** [comment]
You should be able to assign a static IP address if you login to your router and find the rock-5b device.

**Comment by iamryanchia** [comment]
Yes, i will give it a try. Thank you!
