### ISSUE TITLE
There is no sound in the rock5b headset

### ISSUE THREAD

**Issue by tickley** [Joshua-Riek/ubuntu-rockchip#301]
![IMG_20230808_183924(1)](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/113530471/71ba3e6d-4be3-48f1-83ce-1206fad97fec)
I think you can access and recognize the headset and then the headset has no sound, and it is also turned on in the Settings

**Comment by sunarowicz** [comment]
Joshua has already resolved that issue, see here: #291.

**Comment by Joshua-Riek** [comment]
This has been fixed already, closing.
