### ISSUE TITLE
HDMI sound not working on Orange Pi 5 Plus

### ISSUE THREAD

**Issue by Siliconthaumaturgy** [Joshua-Riek/ubuntu-rockchip#306]
I am unable to get HDMI sound working on Orange Pi 5 Plus.

When I open AlsaMixer, I can change "Card", but no value is displayed for "Chip".

The only "Card" where volume levels show up is "rockchip, es8388."  Other options are "rockchip, dp0", "rockchip-hdmi0", "rockchip-hdmi1", "rockchip-hdmiin"; these only show a setting

Changes to alsamixer settings do not save after exiting. 

I tried uninstalling and reinstalling Alsa and related utility packages, but the issue was not resolved.

Here is a screenshot showing what appears when I enter AlsaMixer.  Apologies for taking a picture of my monitor instead of through SSH.
![20230812_115930](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/140443633/31523e58-1a06-4860-997a-3c8f234b6031)

**Comment by Joshua-Riek** [comment]
Hdmi sound has been working fine for a while. Please check your monitor and that you did not screw up any of the audio config settings.

**Comment by Joshua-Riek** [comment]
HDMI sound is working fine for me, closing.
