### ISSUE TITLE
Custom Overlay Prevents boot

### ISSUE THREAD

**Issue by peytonicmaster6** [Joshua-Riek/ubuntu-rockchip#313]
I'm trying to use RPi cameras (currently just the V1 which uses an OV5647 sensor) with the Orange Pi board and I'm running into an issue with the overlays. I have added the camera module to the rk3588s-orangepi-5-camera files and created rk3588-ov5647-c files and copied them into the appropriate places in the /boot/ directory.

I modified the ubuntuEnv.txt file to include the camera overlay with the following line:
`overlays=orangepi-5-ov5647-c3`
 
The system refuses to boot up and the flashing green "heartbeat" LED remains off entirely. This occurs wether the camera is plugged in or not, so you should be able to test the overlay yourself without needing a camera. The overlay for the ov13855 camera works without any issues and I copied the format from that camera for the ov5647. I'm not entirely sure what is preventing the board from booting but I have some ideas.

 - The ov5647 i2c driver is not automatically loaded into the kernel like the ov13855 module is, I have to use mod probe after boot to get it loaded. The ov13855 driver also says it's a built-in driver while the ov5647 is not. 

 - In my overlay, status is set to "disabled" (I just copied the ov13855 overlay and changed the info around for the ov5647) but maybe this should be set to "okay"? I see in the rk3588-orangepi-5-plus-camera1.dts [file](https://github.com/orangepi-xunlong/linux-orangepi/blob/orange-pi-5.10-rk35xx/arch/arm64/boot/dts/rockchip/rk3588-orangepi-5-plus-camera1.dtsi#L123) that the gc5035 camera is set to "okay" instead of "disabled" like the ov13855 and ov13850. 

My overlays and instructions for how I managed installing drivers can be found [here](https://github.com/peytonicmaster6/opi-5-camera_drivers).

**Comment by Joshua-Riek** [comment]
You can use the UART header to connect to a serial console and find out what is happening. My guess is your overlay is bugged somewhere. Also /boot/firmware/dtbs/overlays is the correct path for your overlays.

**Comment by peytonicmaster6** [comment]
I'm not really sure as to what is causing the bugged overlay problem. I used the UART header as you suggested and I get the following error during the boot up process.

```
rockchip-mipi-csi2 mipi0-csi2: invalid resource
Unable to handle kernel NULL pointer dereference at virtual address 0000000000000
Mem abort info:
  ESR = 0x96000004
  EC = 0x25: DABT (current EL), IL = 32 bits
  SET = 0, FnV = 0
  EA = 0, S1PTW = 0
Data abort info:
  ISV = 0, ISS = 0x00000004
  CM = 0, WnR = 0
```

This error causes a whole bunch of outputs, which look to be register addresses and values. The lengthy output ends with  
```
Kernel panic - not syncing: Attempted to kill init! exitcode = 0x0000000b
SMP: stopping secondary CPUs
```

followed by a call trace for CPU, the output of the CPU and thermal registers, and then it finally ends with another kernel panic message. In a function system, instead of the rockchip-mipi-csi2 mipi0-csi2 line, there is the following line:
`rockchip-mipi-csi2: Async registered subdev`

I tried commenting out the lines I added to the rk3588-orangepi-5-camera overlays, recompiling, and copying the rk3588s-orangepi-5b and rk3588s-orangepi-5 into /boot/firmware/dtbs/, but I got the same error message. By commenting out the lines I added and recompiling, the overlay was returned to exactly how it was before I modified it, so I would have expected it to work without any problems. 

Could it be in my process for implementing the overlay? Here's an overview of how it's done.
1. Clone your linux-rockchip repo (I use the linux-5.10-gen-rk5.1 branch)
2. Modify the rk3588-orangepi-5-camera{1,2,3} overlays in arch/arm64/boot/dts/rockchip/
3. Create the camera specific overlays with the format rk3588-{camera-module}-c{1,2,3} in arch/arm64/boot/dts/rockchip/overlay/
4. Run "make menuconfig". I leave all the default settings here.
5. Compile the overlays using "make dtbs"
6. Copy the modified rk3588s-orangepi-5b.dtbo and rk3588s-orangepi-5.dtbo in arch/arm64/boot/dts/rockchip to /boot/firmware/dtbs/
7. Copy the camera module -c1, -c2, and -c3 overlays from arch/arm64/boot/dts/rockchip/overlay to /boot/firmware/dtbs/overlays/
8. Add the camera specific overlay in /boot/firmware/ubuntuEnv.txt, like so `overlays=rk3588-ov5647-c1`
9. Reboot

**Comment by peytonicmaster6** [comment]
Recompiling the kernel and installing fixes the issue, but it's a little tedious to have to recompile every time I need to make a change to the overlay :/
