### ISSUE TITLE
scrcpy causes system freezing

### ISSUE THREAD

**Issue by za-songguo** [Joshua-Riek/ubuntu-rockchip#314]
When I tried to connect to my Android pad (1920x1200) using `scrcpy`, after it printed the resolution information, the system froze and the green LED on my board stopped blinking.
The problem happened whether I was using a wired or wireless connection to `scrcpy`.

**Comment by Joshua-Riek** [comment]
I'm not familiar with scrcpy, but maybe it has some issue with panfork. Do you know if this works on Armbian without GPU drivers installed? Also do you have any system logs from when the system froze?

**Comment by za-songguo** [comment]
> I'm not familiar with scrcpy, but maybe it has some issue with panfork. Do you know if this works on Armbian without GPU drivers installed? Also do you have any system logs from when the system froze?

I have already tried it on Armbian with Panfork and it works well (using an Android Docker container, 1080x1920).
I don't know if it's the problem of the resolution.

**Comment by za-songguo** [comment]
> I'm not familiar with scrcpy, but maybe it has some issue with panfork. Do you know if this works on Armbian without GPU drivers installed? Also do you have any system logs from when the system froze?

When I tried to use scrcpy from snap instead of apt, it worked with some error messages:
```
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.0 MB/s (42151 bytes in 0.040s)
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
[server] INFO: Device: xxxx (Android 9)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1200x1920
```
I think the scrcpy from apt has some problems with the GPU driver.

**Comment by za-songguo** [comment]
> I'm not familiar with scrcpy, but maybe it has some issue with panfork. Do you know if this works on Armbian without GPU drivers installed? Also do you have any system logs from when the system froze?

I also tried the snap version of scrcpy on Armbian, which worked well, and I haven't tried the scrcpy from apt on it yet.

**Comment by za-songguo** [comment]
> I'm not familiar with scrcpy, but maybe it has some issue with panfork. Do you know if this works on Armbian without GPU drivers installed? Also do you have any system logs from when the system froze?

It seems that the snap version of scrcpy uses software decoding...

**Comment by Joshua-Riek** [comment]
I can't do anything about the scrcpy package from apt causing issues. The current GPU / VPU situation is not the best right now.

**Comment by za-songguo** [comment]
> I can't do anything about the scrcpy package from apt causing issues. The current GPU / VPU situation is not the best right now.

Thank you for your reply. Would the situation improve when the mainline kernel comes out?

**Comment by Joshua-Riek** [comment]
I have no idea what the gpu / vpu situation will be like for mainline.

I do have a few working mainline kernels and images that I have not posted because users do not understand how experimental and that it needs a lot of work.
