### ISSUE TITLE
Orange pi 5B no wifi on 1.23 release 

### ISSUE THREAD

**Issue by BloedeBleidd** [Joshua-Riek/ubuntu-rockchip#316]
Hello.
Just right now I downloaded 1.23 ubuntu for orange pi 5b and flashed the SD card with it.
After first boot everything went good. Right now I am looking on the settings and there is no WiFi available in the networking tab. On the emmc I have armbian installed in which WiFi is working well, so this is surely not a hardware problem.
Ethernet connection works fine.

What should I do now to manage to get WiFi connection?

**Comment by Joshua-Riek** [comment]
I'm aware of this issue. Please install the previous version and enter the below command to prevent the kernel from updating, as this was introduced in the latest kernel update, I need time to look deeper into this issue. However, there is already an issue open for this so this one will be closed. 
```
sudo apt-mark hold linux-image-5.10.160-rockchip
```
