### ISSUE TITLE
Tencent Aurora Box 5 Pro may be able to be launched through this project

### ISSUE THREAD

**Issue by lee86** [Joshua-Riek/ubuntu-rockchip#317]
By decompiling the boot.img of the official upgrade package, we can obtain the dts file.

This box have added 8150 network cards and rtl8852be wireless network cards (supporting Bluetooth) ,The soc is RK3588s .

Perhaps we can add this device to the support range?

The dts and dtb file
[rk3588s-tencent-5p.zip](https://github.com/Joshua-Riek/ubuntu-rockchip/files/12377247/rk3588s-tencent-5p.zip)

![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/25501580/e7ac1a9c-3269-401d-ba60-67cd9c6b8d99)
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/25501580/9d847c63-7c56-4007-9b47-ca0875bd878e)

I'm sorry for that I don't know how to compile the system. But I tried to replace the DTB of Orangepi-5b and modified some shell scripts, after compilation is completedand it really work

**Comment by Joshua-Riek** [comment]
I don't want to support Android TV boxes right now. They have limited use and can be difficult to maintain.

**Comment by avatar21** [comment]
> By decompiling the boot.img of the official upgrade package, we can obtain the dts file.
> 
> 
> 
> This box have added 8150 network cards and rtl8852be wireless network cards (supporting Bluetooth) ,The soc is RK3588s .
> 
> 
> 
> Perhaps we can add this device to the support range?
> 
> 
> 
> The dts and dtb file
> 
> [rk3588s-tencent-5p.zip](https://github.com/Joshua-Riek/ubuntu-rockchip/files/12377247/rk3588s-tencent-5p.zip)
> 
> 
> 
> ![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/25501580/e7ac1a9c-3269-401d-ba60-67cd9c6b8d99)
> 
> ![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/25501580/9d847c63-7c56-4007-9b47-ca0875bd878e)
> 
> 
> 
> I'm sorry for that I don't know how to compile the system. But I tried to replace the DTB of Orangepi-5b and modified some shell scripts, after compilation is completedand it really work

Glad to know that, it's a great news. you may try pushing to armbian community？
