### ISSUE TITLE
Orange Pi 5 network manager reset configuration after reboot

### ISSUE THREAD

**Issue by 1984kav** [Joshua-Riek/ubuntu-rockchip#320]
Orange Pi 5 Ubuntu desktop network manager reset configuration after reboot

**Comment by Joshua-Riek** [comment]
I need some more information on how to reproduce this issue and what settings are being reset.

**Comment by 1984kav** [comment]
I set up an Ethernet network connection profile - I specify static IP and MAC addresses.  After a reboot, the profile settings are reset.  This prevents me from fixing the IP address.  Thanks for your work.

**Comment by 1984kav** [comment]
> 

I set up an Ethernet network connection profile - I specify static IP and MAC addresses. After a reboot, the profile settings are reset. This prevents me from fixing the IP address. Thanks for your work.

**Comment by 1984kav** [comment]
On OrangePi 5 plus Ubuntu Desktop this bug does not exist.

**Comment by 1984kav** [comment]
Problem solved by reinstalling the system
