### ISSUE TITLE
Unable to download v1.23 images

### ISSUE THREAD

**Issue by s1n7ax** [Joshua-Riek/ubuntu-rockchip#321]
Links in https://github.com/Joshua-Riek/ubuntu-rockchip/releases for Orange Pi will result in 404

**Comment by Joshua-Riek** [comment]
I see. They can still be downloaded in the Assets section. I will update the hyperlinks to fix this once I get back home to my computer.

**Comment by Joshua-Riek** [comment]
Fixed, thanks for letting me know about this.
