### ISSUE TITLE
Orange Pi 5 Plus Onboard Microphone

### ISSUE THREAD

**Issue by Chrisz236** [Joshua-Riek/ubuntu-rockchip#323]
Is opi 5 plus onboard microphone still not working? Is there a way to fix it?

**Comment by Joshua-Riek** [comment]
No, it is not. I got it working on the Orange Pi 5, but it required a lot of specific alsa audio configs. However using these audio configs can seemingly break audio for other devices such as Bluetooth audio and the a headset plugged into the audio jack.

**Comment by Chrisz236** [comment]
Ah, never mind, I will just use a plugged microphone instead. Nice work buddy.
