### ISSUE TITLE
Orange Pi 5 network manager reset configuration after reboot

### ISSUE THREAD

**Issue by 1984kav** [Joshua-Riek/ubuntu-rockchip#328]
I set up an Ethernet network connection profile - I specify static IP and MAC addresses. After a reboot, the profile settings are reset. This prevents me from fixing the IP address. Thanks for your work.

**Comment by Joshua-Riek** [comment]
Please don't create duplicate issues. I have limited time right now and can not address everything right away. I will get to it when I can.
