### ISSUE TITLE
Missing software renderer driver

### ISSUE THREAD

**Issue by stevepringle** [Joshua-Riek/ubuntu-rockchip#331]
The swrast_dri.so library is missing from the libgl1-mesa-dri package, which means that applications such as vnc servers that use software graphics acceleration will not work.

**Comment by Joshua-Riek** [comment]
Mesa used for the RK3588 is currently a hack called panfork with limited capabilities, and I don't know if this library can be compiled. Or if it's just missing in the deb package.

**Comment by stevepringle** [comment]
If it and any dependant libraries could be compiled and added to the deb package that would be great :-)

**Comment by stevepringle** [comment]
This has now been fixed by JianFeng Liu and has been added to his panfork mesa ppa.
