### ISSUE TITLE
Screen keeps flickering on and off on installation

### ISSUE THREAD

**Issue by rxng** [Joshua-Riek/ubuntu-rockchip#335]
Using img ubuntu 22.04.3 desktop arm64 rock 5b. This successfully boots up on microsd in a rock 5b, however, the display monitor starts to flicker on and off non stop, on the ubuntu loading screen as well as the welcome dialog.

I have just tested armbian and official rock 5b images on the same exact setup, they are fine so it appears this is isolated to this.

**Comment by rxng** [comment]
Here is a video in case that's useful! Let me know if you need any more info, happy to help @Joshua-Riek 
https://github.com/Joshua-Riek/ubuntu-rockchip/assets/19649766/a61cd948-d994-47ba-87e3-fad480460d0c

**Comment by Joshua-Riek** [comment]
I use the same kernel as armbian, so this should not be an issue. Also, this kernel has limited monitor support. A lot of resolutions do not work right.

**Comment by rxng** [comment]
Interesting, running armbian jammy now and it's completely ok

**Comment by Joshua-Riek** [comment]
I did some testing and can not reproduce this issue. Please try the latest release.
