### ISSUE TITLE
Can we have jammy 22.04 with kernel 5.15 , so that the intelrealsense and its wrapper put in to use.

### ISSUE THREAD

**Issue by hemsinghb** [Joshua-Riek/ubuntu-rockchip#337]
I request Mr. Joshua to considering to upgrade kernel of rock 5b model to 5.15 , so that the intel librealsense SDK2.0 (v 2.54.1)  and its wrapper v4.51.1 can be put in to use with depth cameras D435i and D455 etc.

**Comment by Joshua-Riek** [comment]
The rk3588 was introduced in the 6.2 kernel, and I have internal images with the latest 6.5 kernel. However, people need to understand that only some things work, so they have not been released.

Using 5.15 would be impossible unless there is a BSP from Rockchip.

**Comment by hemsinghb** [comment]
Thank you for replay.
