### ISSUE TITLE
nano PC T6 couldn't start from nvme

### ISSUE THREAD

**Issue by E1t2han** [Joshua-Riek/ubuntu-rockchip#340]
I follow the step in your github ,first write the uboot to spi(/dev/mtdblock0),second write the image ubuntu-22.04.3-preinstalled-desktop-arm64-nanopc-t6.img.xz to nvem ,then shutdown，take out the SD card，power on，T6 box couldn't start from  nvem, still start from the emmc( Android TV system on emmc)

**Comment by E1t2han** [comment]
![Uploading IMG_20230829_231255.jpg…]()

**Comment by E1t2han** [comment]
Tonight I clear the EMMC, the box can start from nvme(ubuntu system on nvme),thanks Joshua-Riek

**Comment by Joshua-Riek** [comment]
Ah, right, the boot order is SD Card -> eMMC -> NVMe. I'm glad you have it working!
