### ISSUE TITLE
gstreamer low fps (1.7) when displaying hdmi-in stream

### ISSUE THREAD

**Issue by yrik** [Joshua-Riek/ubuntu-rockchip#342]
```
gst-launch-1.0 v4l2src device=/dev/video0 ! videoconvert ! fpsdisplaysink
```

Rock 5b 8GB

![IMG_8503](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/394729/3a1782c4-0418-42af-9770-2c14ef1b9d92)

**Comment by ironiris** [comment]
gst-launch-1.0 v4l2src device=/dev/video0 ! video/x-raw,format=NV12,width=3840,height=2160,framerate=60/1 ! autovideosink
