### ISSUE TITLE
launchpad build error in scripts/build-rootfs.sh 

### ISSUE THREAD

**Issue by hakotani-o** [Joshua-Riek/ubuntu-rockchip#344]
Thank you for your work.
I run "sudo ./build.sh --board=orangepi-5 -l" on Orange pi 5.
An error has occurred.

Get:5 https://ppa.launchpadcontent.net/jjriek/rockchip/ubuntu jammy InRelease [18.1 kB]
Get:6 https://ppa.launchpadcontent.net/jjriek/rockchip/ubuntu jammy/main arm64 Packages [4604 B]
Get:7 https://ppa.launchpadcontent.net/jjriek/rockchip/ubuntu jammy/main Translation-en [1732 B]
Fetched 24.4 kB in 4s (6279 B/s)
Reading package lists...
Repository: 'deb https://ppa.launchpadcontent.net/jjriek/rockchip/ubuntu/ jammy main'
More info: https://launchpad.net/~jjriek/+archive/ubuntu/rockchip
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/jjriek-ubuntu-rockchip-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/jjriek-ubuntu-rockchip-jammy.list
Adding key to /etc/apt/trusted.gpg.d/jjriek-ubuntu-rockchip.gpg with fingerprint 3CC0D9D1F3F0354B50D24F51F02122ECF25FB4D7
/bin/bash: line 13: conditional binary operator expected
Error: in ./scripts/build-rootfs.sh on line 111
Error: in ./build.sh on line 150

Thank you.

**Comment by Joshua-Riek** [comment]
Thanks for finding this, it has now been fixed.
