### ISSUE TITLE
Consider adding CONFIG_HID_MAGICMOUSE as a module?

### ISSUE THREAD

**Issue by elafargue** [Joshua-Riek/ubuntu-rockchip#346]
I noticed the kernel on `ubuntu-rockchip` does not set CONFIG_HID_MAGICMOUSE to compile as a module, would it be possible to enable this? I can open a PR if you guide me in the right direction, what would be the easiest way to do this (and is this the right repo ?)

**Comment by Joshua-Riek** [comment]
Enabled with commit https://github.com/Joshua-Riek/linux-rockchip/commit/c7bec1671c4a053304703280afb114745a1084c3, thanks!
