### ISSUE TITLE
Transfer the system from TF to NVME disk on Orange Pi 5 Plus

### ISSUE THREAD

**Issue by SubZero77** [Joshua-Riek/ubuntu-rockchip#347]
How to transfer the system from TF card to NVME M.2 disk on Orange Pi 5 Plus?
Command nand-sata-install don't working.

**Comment by Joshua-Riek** [comment]
This is not Armbian, so that command does not exist. You can use dd, however.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Orange-Pi-5-Plus#install-ubuntu-onto-your-nvme-from-linux
