### ISSUE TITLE
[Orange pi5]Can't boot from 1TB SSD (Samsung T7)

### ISSUE THREAD

**Issue by ghisooo** [Joshua-Riek/ubuntu-rockchip#350]
Hi, 
I tried diverse things, but I keep failing to boot from my Samsung T7 SSD( I tried both usb-c to c and usb-c to a cables)...

Would you happen to have any idea how to solve this problem?

**Comment by Joshua-Riek** [comment]
There is a bug in the bootloader that prevents booting from USB SSD devices. #131
