### ISSUE TITLE
rk3588 needs to enable RKISP1

### ISSUE THREAD

**Issue by DHDAXCW** [Joshua-Riek/ubuntu-rockchip#353]
Request to enable this configuration to solve mipi csi camera https://github.com/Joshua-Riek/linux-rockchip/blob/linux-5.10-gen-rkr5.1/arch/arm64/configs/rockchip_linux_defconfig#L4559

Before activation
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/74764072/4f659f73-f438-4964-b686-e57276a1676d)

After activation
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/74764072/18e0381c-9cd0-4493-b916-e71d36b9a41a)

Turn it on to solve the mipi csi problem
Thank you~

**Comment by DHDAXCW** [comment]
Before activation
![16940763038394](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/74764072/615070af-a816-421c-a839-5ef5eb8f1ae8)

**Comment by DHDAXCW** [comment]
After activation
![1694078882450](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/74764072/f5762461-5774-4df7-adf1-e58ae8c9bde6)

**Comment by Joshua-Riek** [comment]
Enabled with commit https://github.com/Joshua-Riek/linux-rockchip/commit/c7bec1671c4a053304703280afb114745a1084c3, thanks!
