### ISSUE TITLE
Kernel 6.5.0 pre-release

### ISSUE THREAD

**Issue by vtv3000** [Joshua-Riek/ubuntu-rockchip#357]
Hi. I cannot boot on orange pi5plus or Ethernet  not work and I cannot communicate via ssh

**Comment by Joshua-Riek** [comment]
I specifically asked for no issues to be open in regards to the 6.5.0 kernel as it is heavily a work in progress. 

I know the system boots. Use a serial console to interact with the device.

**Comment by vtv3000** [comment]
Hi
I understand about 6.5 - it’s hard work I promise you can make it :)

I have a question - do you have kernel 5.19 ? Or maybe instructions how
compiler this kernel ?

пн, 11 вер. 2023 р. о 16:39 Joshua Riek ***@***.***> пише:

**Comment by Joshua-Riek** [comment]
The RK3588 SOC was introduced into mainline Linux version 6.2, so using 5.19 would not be possible.

**Comment by vtv3000** [comment]
You say “mainline Linux version 6.2”

Why you make 6.5 ? Maybe 6.2 will be easy ?



пт, 15 вер. 2023 р. о 20:54 Joshua Riek ***@***.***> пише:

**Comment by Joshua-Riek** [comment]
The 6.5 kernel introduced many features for the RK3588 SOC, using 6.2 would be complex because fewer hardware features are supported.

**Comment by vtv3000** [comment]
Ok I understand . Thanks for you hard work


пт, 15 вер. 2023 р. о 21:04 Joshua Riek ***@***.***> пише:

**Comment by vtv3000** [comment]
Hi . I understand about hard work about 6.5 .
Can you compile last kernel v5 ?   May be 5.18 …or write instruction for
compile kernel on orange 5 plus  (not cross compile)

5.10 and 5.18 many differents for me .




пт, 15 вер. 2023 р. о 21:06 Владимир Талалаев ***@***.***> пише:

**Comment by Joshua-Riek** [comment]
The 5.x kernel is not compatible with the RK3588 SOC, so this is not possible. There is a 5.x BSP that uses an **Android** kernel which is not real Linux.

**Comment by vtv3000** [comment]
it is very sad. how are you doing with kernel 6 development?


пт, 22 вер. 2023 р. о 00:58 Joshua Riek ***@***.***> пише:
