### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by RichNeese** [Joshua-Riek/ubuntu-rockchip#360]
you have it so you can install on sd but how to clone your work once you have a working sd to the emmc or nvme and have it use mtd0 to boot ?

**Comment by Joshua-Riek** [comment]
You can use some dd commands to clone your sd to emmc or nvme. You can take a look at the wiki for your device for more details.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Radxa-ROCK-5B
