### ISSUE TITLE
Orange Pi 5 Ubuntu screen blank doesn't work

### ISSUE THREAD

**Issue by JayJay3** [Joshua-Riek/ubuntu-rockchip#362]
I set up my Orange pi 5 Ubuntu as follows;

Dim screen: on
Screen blank: 5 minutes
Automatic suspend: off
Power button behavior: Power off

But screen doesn't go blank after 5 minutes. Screen never goes blank. I tested automatic suspend. That works. But not screen blank.

**Comment by JayJay3** [comment]
I forgot to mention that it's "Gnome" interface. Also that mouse and screen freeze also "Gnome" version. Xfce version works OK. It's not power adapter problem! I think Gnome is new addition to OPi5. So it has bugs.

**Comment by Joshua-Riek** [comment]
I think you are confused and not using this distro as I previously stated. I assume you are using the official distros the Orange Pi company created, I have no relation to them, and I will not fix their distros. 

The GitHub repo below is the official build system from the Orange Pi company, you can try to express your issues there but I can almost guarantee you will not get any help.

https://github.com/orangepi-xunlong/orangepi-build

**Comment by JayJay3** [comment]
Sorry. I didn't know that. I will content with Xfce version for now. If I have to reinstall Ubuntu, I will try your version.

**Comment by JayJay3** [comment]
Does your distro support OpenGL ES version 3?
Although Orange Pi claims it supports OpenGL ES version 3, I cann't find any distro that supports ES version 3.

**Comment by Joshua-Riek** [comment]
Yes, it uses a hack called panfork for this. The implementation that Orange Pi uses is very broken.

**Comment by JayJay3** [comment]
I got new SD card and tried your version. It has more problems than Orange Pi versions. First, Chrome browser crashed. On next boot, asked to send crash report. After some reboots, Chrome worked. But keep asking password. I never seen browser asking account password. Then Ubuntu internal error occurred. Screen blank accompanies log out. After screen blank, Ubuntu keep asking password. So I gave up!

**Comment by Joshua-Riek** [comment]
Your power supply is insufficient, or you still are not using this distro. 

Rambling about an extensive list of issues will do nothing. You need to provide reproducible steps with meaningful information.
