### ISSUE TITLE
Upgrading Orange Pi 5 Plus to mainline kernel

### ISSUE THREAD

**Issue by adminy** [Joshua-Riek/ubuntu-rockchip#363]
This device with supposedly superior specs is getting left behind, is there anything that can be done to bump that version? Even at the expense of having it just boot without any of the devices working properly. As this gap is growing each day with plenty of features coming into the new kernel releases that improve many bugs and add many useful features.

**Comment by Joshua-Riek** [comment]
I have experimental releases with the 6.5.0 kernel, what exactly are you looking for?

**Comment by Joshua-Riek** [comment]
I have some 6.5.0 builds that finished a few hours ago, there is no HDMI output, so you need to use a serial console.

https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/6210593078

**Comment by mijk84** [comment]
If I had to guess, they are likely running into the issue I'm having where the LED is solid  green and there is zero activity from the device. For me this happens with any image that has the  mainline kernel.

**Comment by Joshua-Riek** [comment]
Use a serial console, to find out what the device is doing, the LED blinks for me and works with no issue.

**Comment by adminy** [comment]
I have a 5G modem and a wifi 6E device that I want to get working. They just need to have latest kernel for driver reasons. Thanks for the build link.
