### ISSUE TITLE
Consider enabling CONFIG_HID_APPLE as a module in the Linux kernel 

### ISSUE THREAD

**Issue by elafargue** [Joshua-Riek/ubuntu-rockchip#373]
Similar to #346 : I noticed that CONFIG_HID_APPLE is not compiled as a module. This HID kernel module adds support for the Apple magic keyboard in particular. If not present, some of the Apple keys don't work properly, making the magic keyboard awkward to use.

If you could add this, it would be awesome, thanks!

**Comment by Joshua-Riek** [comment]
Enabled: https://github.com/Joshua-Riek/linux-rockchip/commit/0dc7efff4d1c9fd9a2657924eca3de3aa1808472
