### ISSUE TITLE
(Orangpi5plus)Help!,I don't known how to enable UART or CAN

### ISSUE THREAD

**Issue by 2350015226** [Joshua-Riek/ubuntu-rockchip#380]
In the official tutorial, orangepi-config is used to enable the serial port and can.but i can't. 
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/57864581/73571190-2871-4d7e-93ff-6e19a81c5381)
![fdecc52cf0b12de36836a50f05fc93f0](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/57864581/1b849ee3-b26b-445d-a0ea-ef984bacc7d6)

**Comment by Joshua-Riek** [comment]
This is not an official distro from Orange Pi, and it does not have the orangepi-config program. However, you can still enable UART and CAN interfaces by using device tree overlays. You must specify the overlays you wish to enable as shown on the wiki page below.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Device-Tree-Overlays

**Comment by 2350015226** [comment]
> This is not an official distro from Orange Pi, and it does not have the orangepi-config program. However, you can still enable UART and CAN interfaces by using device tree overlays. You must specify the overlays you wish to enable as shown on the wiki page below.
> 
> https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Device-Tree-Overlays
I have tried your method, and now I can see my enabled device on the console, thank you. If you have the chance to come to Guangdong Province, I will definitely take you to eat the freshest seafood, haha, thanks again
