### ISSUE TITLE
Ethernet LEDs

### ISSUE THREAD

**Issue by p1xhub** [Joshua-Riek/ubuntu-rockchip#385]
Hello
A quick question about the Ethernet LED: why does only the green light blink, the orange one does not light up? On the official Orange Pi the green LED glows and the orange LED blinks... What is the difference?

**Comment by Joshua-Riek** [comment]
There are many differences between this distro and the one created by Orange Pi. I can't list them all or I would be here all day long and I'm too tired to type it up. The ethernet is working so I don't see this as any sort of issue.
