### ISSUE TITLE
Can I add the orangepi-config tool to Orange5Plus?

### ISSUE THREAD

**Issue by 124ffee** [Joshua-Riek/ubuntu-rockchip#387]
Can I add the orangepi-config tool to Orange5Plus?I want to control peripherals like lights directly through the orangepi-config tool, just like the official image.    This is the link to compile orangepi-config：https://github.com/orangepi-xunlong/orangepi-build/tree/next

**Comment by Joshua-Riek** [comment]
Sadly, you can not without heavy modification to the orangepi-config tool. The distro created by orangepi is an old Armbian fork, since my project is not Armbian there would be conflicts.
