### ISSUE TITLE
Rock 5A with Ubuntu Server v1.24: clock MHz scaling issue?

### ISSUE THREAD

**Issue by guynich** [Joshua-Riek/ubuntu-rockchip#395]
Comparing Indiedroid Nova and Rock 5A: both running Ubuntu Server v1.24.  I have a task with heavy CPU load running in the RK3588 `bigcores`.

- I'm seeing the Rock 5A with SOC heatsink reach critical temperature after a few minutes with highest `bigcore` temp of 119ºC just before reboot.  The `bigcore` freq changes from 2304 MHz  to **2208** MHz during the run.

- with same task the Indiedroid Nova does not reboot and the highest `bigcore` temperature is 93ºC.  The `bigcore` freq drops from 2256 down to **1608** MHz during the run.  This SBC has a big integrated heatsink.

- I also checked an OrangePi 5 with similar heatsink to Rock 5A: the OPi5 did not reboot and the highest `bigcore` temperature is 93ºC.  The `bigcore` freq drops from 2304 down to **1200** MHz during the run. 

Thus I'm suspicious of the CPU frequency/temperature governance of Rock 5A based on the observations.  Any suggestions for a fix?  Is this something that can be manually configured in a file somewhere?

* edited: added OPi5 and heatsink comments.

**Comment by Joshua-Riek** [comment]
Use proper cooling, and this will not be an issue.

**Comment by Joshua-Riek** [comment]
Governers are to preformance each boot, if you want to disable use:
```
systemctl enable cpu-governor-performance
systemctl enable gpu-governor-performance
```

**Comment by guynich** [comment]
I’ll check these commands - thanks Joshua:::On 2 Oct 2023, at 15:06, Joshua Riek ***@***.***> wrote:﻿
Governers are to preformance each boot, if you want to disable use:
systemctl enable cpu-governor-performance
systemctl enable gpu-governor-performance

**Comment by guynich** [comment]
Confirming I'm able to change the governer on Rock 5A to the different states, e.g.:
- conservative (example below)
- powersave
- ondemand
- performance
- schedutil
```
sudo -i
# See policy to see how CPUs are grouped.
echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo conservative > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo conservative > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
exit

cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 
```
Apart from `powersave` which sets the core clocks to 408MHz, none of these governors addresses the throttling issue: the core temperature of the Rock 5A rises to high levels and the clock frequencies do not get lowered to something like 1200MHz to control the thermal runaway.

I'm thinking this issue is to do with Rock 5A firmware and not under our control here.  Thanks.

**Comment by guynich** [comment]
I checked Radxa [releases](https://github.com/radxa-build/rock-5a/releases) specifically rock-5a_ubuntu_jammy_cli_b18.img.xz](https://github.com/radxa-build/rock-5a/releases/download/b18/rock-5a_ubuntu_jammy_cli_b18.img.xz) with Rock 5A and found CPU throttling works as expected with `performance` governor.  This resolves my issue.   Thanks!
