### ISSUE TITLE
support for orange pi 5 m.2 wifi module

### ISSUE THREAD

**Issue by mikavdwiel** [Joshua-Riek/ubuntu-rockchip#397]
Love the os, however i wonder if its possible to use the m.2 wifi module made by orange pi? I tried adding the dtbo file of the orangepi armbian build but that doesnt work. Not super experienced with arm operating systems so excuse me if this can be solved super easy.

**Comment by Joshua-Riek** [comment]
Take a look at the wiki, it's supported. 
https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Orange-Pi-5#pcie-wifi-60-module-ap6275p
