### ISSUE TITLE
1.27 stop supporting  4k in MPV

### ISSUE THREAD

**Issue by demosspro** [Joshua-Riek/ubuntu-rockchip#405]
Hello, i am testing 1.27 ver of ubuntu image. There is not support VPU accel of video decode. MPV player have freeze and lags, CPU utilization is hight.
i am using Orange pi 5 8gb + ssd 256gb 1gbit network.

**Comment by demosspro** [comment]
yep, i flash again 1.24 - video plaing smooth and mpv use the VPU acc.

**Comment by Joshua-Riek** [comment]
Ah, amazingfate updated mpv in his ppa to now use rkmpp. Please open `/etc/mpv/mpv.conf` and modify the line `hwdec=drm` to `hwdec=rkmpp`.
