### ISSUE TITLE
SATA SSD shown in OPOS but not in Ubuntu 

### ISSUE THREAD

**Issue by sdipto24** [Joshua-Riek/ubuntu-rockchip#414]
Hello,
Thanks for your contribution.
My OP5  was booted by SD card and by orangepi configurations I activated SATA SSD and orangepiEnv was shown like
![IMG20231017231321](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/148263354/b76f4260-3a99-4800-bc21-bf505f494b5b)
I successfully flash Ubuntu to SSD but when I edit overlays.txt to fdt_overlays=rk3588-ssd-sata.dtbo or fdt_overlays=rk3588-ssd-sata0.dtbo or fdt_overlays=rk3588-ssd-sata2.dtbo can't boot up from SSD.
It like
![IMG20231017231811](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/148263354/214bd149-b430-486a-9463-4cd25298908d)
![IMG20231017231822](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/148263354/c9d14f65-a345-4397-8eba-ec2aba0a6fce)
and nothing changes
Can you please tell any way
I also installed Ubuntu in another SD card but failed to up SATA SSD.

**Comment by Joshua-Riek** [comment]
Take a look at the GitHub wiki page. There are instructions.
