### ISSUE TITLE
RK3568 Support in this project

### ISSUE THREAD

**Issue by md2k** [Joshua-Riek/ubuntu-rockchip#420]
Hi @Joshua-Riek , is it possible to add Nanopi r5c rk3568 support?

**Comment by Joshua-Riek** [comment]
It's possible but not planned. I have limited time and resources.

**Comment by yaoquan** [comment]
Looking for rk3568 support here too!

**Comment by genothomas** [comment]
RK3568 support for NanoPi R5C would be appreciated 😊

**Comment by Joshua-Riek** [comment]
Support for new hardware requires funding for development.
