### ISSUE TITLE
Network in graphical sever

### ISSUE THREAD

**Issue by druid22d** [Joshua-Riek/ubuntu-rockchip#426]
when i install server the network works yet the system in graphical version of server does not recognize that the network is working.  i am using an orange pi 5b...when i boot everything works...then it gets to "waiting for network to configure" it waits 2 minutes and fails.

**Comment by Joshua-Riek** [comment]
Do you have ethernet connected?

**Comment by druid22d** [comment]
Yes. It works. It is connected and working. Yet the graphical portion
doesn't work.

**Comment by druid22d** [comment]
I guess the graphical portion doesn't recognize it for some reason. My
router doesn't seem the orange pi ever either. Which is weird cuz it gives
it an address.

**Comment by druid22d** [comment]
Also thank you for your quick response.

**Comment by Joshua-Riek** [comment]
Weird, it sounds like cloud-init is acting strange. But in the end, the internet still works? It's just that you must wait 2 minutes before you can log in?

**Comment by druid22d** [comment]
Yes correct. The graphical portion doesn't seem that the Internet is
working either.

**Comment by druid22d** [comment]
When I use workstation I have no problem with the network. Everything works
fine. I may just switch back to workstation. I can do everything I need
with that. I just wanted to make use of the extra included products with
server. I will just have to do a bit more work to get everything I need.
Lol. Jason Lamy

**Comment by Joshua-Riek** [comment]
Since networking works without issue, I don't think this is an issue with this project. Potentially something with cloud-init. Additionally, I did some testing and could not reproduce your problem.

**Comment by druid22d** [comment]
It could be an issue with my internet provider. Like I said. I'll probably
just switch back to workstation.

**Comment by druid22d** [comment]
Thank you again for your quick response and the great help. Jason Lamy

**Comment by druid22d** [comment]
is there a way to fix this without resorting to using workstation? or maybe it is the image i used?

**Comment by Joshua-Riek** [comment]
I could not reproduce this issue; maybe try downloading the latest release. Or try the desktop image, which will require a keyboard and mouse for the first use. However, it does use a different network manager, so the desktop image may solve the problem.

**Comment by druid22d** [comment]
I always use a keyboard etc. I haven't used a headless system yet. That is
my next project. I want to build a cluster for distributed computing. I
have always wanted my own "Super Computer ". Lol. Thanks again for your
help. Jason Lamy.

**Comment by druid22d** [comment]
I ended up switching to workstation. No problem now. I cannot understand
why it doesn't work in server. I have a regular PC that the same issue
happens with server. I believe that it is my internet provider. There is
some sort of issue with them. Thanks again. Jason Lamy

**Comment by druid22d** [comment]
maybe if i set a static IP then maybe it would work...I'll have to
flash server on a card and test it out with a static IP address. Maybe that
would fix the issue. my isp will give the orange pi an ip address but i
cannot see it on the router...very weird....may be good for torrenting....

**Comment by druid22d** [comment]
It must be my isp....i just installed ubuntu inside a vm on my windows
machine and got the same problem. i used a native version of ubuntu...so it
must be some issue here. i will have to call them and figure it
out....maybe i need to use a static IP address....
