### ISSUE TITLE
I can't install ROS2 on my orangepi5b and orangepiplus.

### ISSUE THREAD

**Issue by zhudisha** [Joshua-Riek/ubuntu-rockchip#433]
It's OK to install ROS2 when I using the V1.27 img
V1.27可以安装ROS2，但是v1.28安装报错如下

下列软件包有未满足的依赖关系：
 libavcodec-extra58 : 依赖: libavutil56 (= 7:4.4.2-0ubuntu0.22.04.1) 但是 7:4.4.2-0ubuntu0.22.04.1+rkmpp20230327 正要被安装
                      依赖: libswresample3 (= 7:4.4.2-0ubuntu0.22.04.1) 但是 7:4.4.2-0ubuntu0.22.04.1+rkmpp20230327 正要被安装
 libavformat-dev : 依赖: libavformat58 (= 7:4.4.2-0ubuntu0.22.04.1)
 libavutil-dev : 依赖: libavutil56 (= 7:4.4.2-0ubuntu0.22.04.1) 但是 7:4.4.2-0ubuntu0.22.04.1+rkmpp20230327 正要被安装
 libopencv-videoio4.5d : 依赖: libavformat58 (>= 7:4.4)
 libswresample-dev : 依赖: libswresample3 (= 7:4.4.2-0ubuntu0.22.04.1) 但是 7:4.4.2-0ubuntu0.22.04.1+rkmpp20230327 正要被安装
 libswscale5 : 依赖: libavutil56 (= 7:4.4.2-0ubuntu0.22.04.1) 但是 7:4.4.2-0ubuntu0.22.04.1+rkmpp20230327 正要被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

**Comment by Joshua-Riek** [comment]
Please provide exact and reproducible steps.
