### ISSUE TITLE
UPDATE TO 1.29 FROM 1.24

### ISSUE THREAD

**Issue by rusudanion** [Joshua-Riek/ubuntu-rockchip#436]
HELLO I HAVE OPI5 PLUS WITH 1.24 .Can i update to 1.29 version, WITHOUT LOSE ALL CONFIGURATION AND APP INSTALLED ?
IS ANY WAY TO MAKE AN BACKUP FROM 1.24 AND RESTORE TO 1.29 FRESH INSTALL?

THANKYOU.

**Comment by rusudanion** [comment]
hello thankyou.i use before this command line apt  dist-upgrade Is same ?

**Comment by Joshua-Riek** [comment]
Yeah it's the same

**Comment by rusudanion** [comment]
thankyou
