### ISSUE TITLE
Setting symbols in DTC_FLAGS for overlays

### ISSUE THREAD

**Issue by pavhofman** [Joshua-Riek/ubuntu-rockchip#438]
Hi,

This issue should go to https://github.com/Joshua-Riek/linux but issues do not seem enabled in that repo.

I built your kernel 6.6 and your ubuntu image, installed on rk3588s-radxa-cm5-io, everything smooth (I do not need GPU, using serial console and ssh). When trying to install an overlay in /boot/firmware/dtbs/overlays (path taken from boot.cmd) fdt apply complained about missing symbols in the DTB file.

When comparing with DTBs built by radxa BSP https://github.com/radxa-repo/bsp there were really no symbols in rk3588s-radxa-cm5-io.dtb . Quick search revealed Radxa patch the dts/rockchip Makefile with DTC_FLAGS_xxx= -@ parameter https://github.com/radxa-repo/bsp/blob/354f8257af6a403b953edf193dcd9475b0181d52/linux/rockchip/0100-vendor/0001-VENDOR-Add-Radxa-overlays.patch#L30-L45.

Upon adding the same code to my Makefile:
diff --git a/arch/arm64/boot/dts/rockchip/Makefile b/arch/arm64/boot/dts/rockchip/Makefile
index 9738cb369..a961c20b3 100644
--- a/arch/arm64/boot/dts/rockchip/Makefile
+++ b/arch/arm64/boot/dts/rockchip/Makefile
@@ -1,3 +1,4 @@
+DTC_FLAGS_rk3588s-radxa-cm5-io := -@

the built rk3588s-radxa-cm5-io.dtb contains the symbols and my overlay works OK.

I noticed you have patched that file for the newer boards (like my cm5-io). Perhaps the DTC_FLAGS should be added there too to allow using overlays.

Thanks a lot for your great work,

Pavel.

**Comment by Joshua-Riek** [comment]
Mainline Linux is experimental and a work in progress. If you have a patch for this feature that makes sense, I can apply it. Otherwise, I will eventually get to this.
