### ISSUE TITLE
qemu egl-headless not working

### ISSUE THREAD

**Issue by mijk84** [Joshua-Riek/ubuntu-rockchip#439]
I'm trying to use -display egl-headless in qemu but it says "drm device not found". Does this have to do with HDMI output not working?

**Comment by Joshua-Riek** [comment]
HDMI output works what do you mean?

**Comment by mijk84** [comment]
I haven't reimaged since last version and I've been using it headless any way. I don't understand why EGL isn't working. I've compiled qemu the same way I always have. There's no /dev/dri folder either.

**Comment by Joshua-Riek** [comment]
What kernel are you using??

**Comment by mijk84** [comment]
6.6.0-rc7

**Comment by Joshua-Riek** [comment]
There is no working hdmi or mesa yet. It's in development. So EGL will not work.
