### ISSUE TITLE
Kernel 6.6.0 - Higher thermals and kernel boot log errors

### ISSUE THREAD

**Issue by lucianor** [Joshua-Riek/ubuntu-rockchip#442]
1) Flashed the microSD card a while ago, then transferred to the NVMe
2) Running a stable Linux 5.10 system with packages up to date with apt-get upgrade 
3) Decided to try kernel 6.6.0 after your experimental release, but decided to build kernel myself with instructions from here: https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Building
and using `sudo ./build.sh --board=orangepi-5 -m`
4) used the deb file in the build folder and dpkg -i to my system
`dpkg -i linux-image-6.6.0_6.6.0-ga482e8129726-1_arm64.deb`
5) I was able to boot from NVMe with kernel 6.6 without issues, noticed is is running quite fast...  details here: https://www.reddit.com/r/OrangePI/comments/17ld7zd/orange_pi_with_joshua_riek_and_kernel_660_amazing/
6) however noticed that the thermals are about 8C higher.. is that normal / expected?
7) also a couple of errors on kernel on boot: https://pastebin.com/F6KSzVXJ
```
kern  :err   : [    1.497103] rtc-hym8563 2-0051: hctosys: unable to read the hardware clock
kern  :err   : [    2.077754] cpu cpu0: _parse_named_prop: Invalid number of elements in microvolt property (6) with supplies (1)
kern  :err   : [    2.078977] cpu cpu0: _of_add_opp_table_v2: Failed to add OPP, -22
kern  :err   : [    2.079531] cpu cpu0: OPP table can't be empty
```

Command outputs:
```
luciano@mercury:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
luciano@mercury:~$ uname -a
Linux mercury 6.6.0 #1 SMP PREEMPT Tue Oct 31 14:59:57 -03 2023 aarch64 aarch64 aarch64 GNU/Linux
luciano@mercury:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
mtdblock0    31:0    0    16M  0 disk
nvme0n1     259:0    0 238.5G  0 disk
├─nvme0n1p1 259:1    0   512M  0 part /boot/firmware
└─nvme0n1p2 259:2    0   238G  0 part /
luciano@mercury:~$ lspci
0004:40:00.0 PCI bridge: Rockchip Electronics Co., Ltd Device 3588 (rev 01)
0004:41:00.0 Non-Volatile memory controller: MAXIO Technology (Hangzhou) Ltd. NVMe SSD Controller MAP1202 (rev 01)
luciano@mercury:~$ lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Expected:** similar benchmarks, same avg CPU temperature and no significant kernel errors
**Actual:** improved benchmarks, increased CPU temperatures and kernel errors that may or may not be significant

Keep up with the great work!

**Comment by Joshua-Riek** [comment]
I would caution against swapping kernels out with the bsp build. There are hacks specifically for the bsp kernel.

I would prefer there not to be issue reports with the mainline kernel unless you have a fix. I will not spend any time on this.
