### ISSUE TITLE
Any ability to detect version of build script

### ISSUE THREAD

**Issue by ThomasKaiser** [Joshua-Riek/ubuntu-rockchip#448]
Please see https://github.com/ThomasKaiser/sbc-bench/blob/master/sbc-bench.sh#L3028-L3061 for reference.

In case you include the version of your build scripts in your images I would love to add this to `sbc-bench`.

**Comment by Joshua-Riek** [comment]
Sorry, but not yet. I've been meaning to add this but have been busy with other tasks.

**Comment by ThomasKaiser** [comment]
In case you implement this please drop me a note. Am closing this issue now (reopening with an example should do the job as well)
