### ISSUE TITLE
How to use this script “Created a script to install the currently running system onto another device”

### ISSUE THREAD

**Issue by 124ffee** [Joshua-Riek/ubuntu-rockchip#459]
Regarding the first item in the v1.29 update notes, how to use.Involves inputting what directly into the terminal?

**Comment by Joshua-Riek** [comment]
## ubuntu-rockchip-install
The command `ubuntu-rockchip-install` can copy your currently running system onto an NVMe, eMMC, or USB drive.
```
sudo ubuntu-rockchip-install /dev/mmcblk0
```

Please see https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/435.
