### ISSUE TITLE
Latency Issue with VNC Desktop and ssh on Orange Pi 5 Plus v1.29 - Fixed Bluetooth for the official Orange Pi 5 Plus WiFi + Bluetooth module Update

### ISSUE THREAD

**Issue by 124ffee** [Joshua-Riek/ubuntu-rockchip#462]
It seems like there's an issue with the VNC desktop on the latest v1.29 version on the Orange Pi 5 Plus. After starting the VNC desktop and leaving it for around 5 minutes, the network experiences significant latency, causing the VNC desktop to freeze entirely,SSH commands also suffer from considerable delays, for example, a delay of a few seconds before a typed 'i' appears (I can rule out a software issue). During this time, using the ping command shows delays as high as 560ms. This seems to have emerged after the update fixing Bluetooth for the official Orange Pi 5 Plus WiFi + Bluetooth module. Restarting the 'gnome-remote-desktop.service' with "systemctl --user restart gnome-remote-desktop.service" completely resolves this issue. Could this problem be fixed permanently?

**Comment by BaconSoong** [comment]
兄弟，作者为啥不理你啊？
