### ISSUE TITLE
Linux on ssd

### ISSUE THREAD

**Issue by Gazgiza** [Joshua-Riek/ubuntu-rockchip#466]
Is it possible to install the os on an ssd and have it as the main disk?

**Comment by Joshua-Riek** [comment]
Of course, how to do this depends on the board being used.

**Comment by Gazgiza** [comment]
How can I manage to do this?

**Comment by Joshua-Riek** [comment]
You need to provide way more information.

**Comment by Gazgiza** [comment]
I have an sd card with 64 gb on it an want my os to be installed on an ssd plugged in the m.2 slot but idk how to make this. There was something in the readme.md but it disapered.

**Comment by FreeWilly2022** [comment]
I was also looking for the directions on how to copy to an SSD, and I found them here:
https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/435

**Comment by paulwratt** [comment]
when you "boot" the linux kernel you have to pass an alternate / new _root device_ as the mount point. (`cmdline.txt` on a RPi, or **_boot options_** in a bootloader menu)

Alternately, once you have booted (from sd-card) you can `cd` into the root of the new device you want to use as the root filesystems, `mount --bind /dev (here/)dev` (for `/proc` & `/sys` too) the `chroot` - if you know where the SSD is going to be in the `/dev`ices then you can add _those commands_ to the end of your sd-card `init` boot procedure to automate the change (NOTE: both drives need to be using same / similar kernel)

**Comment by develperbayman** [comment]
honestly the easiest way i did it was use a ssd usb adapter and then just flashed the image also if it dont boot i used armbians orangepi-config to update the spi flash to boot then i flashed the image .....i know thats a round about way but it was pretty easy @ joshua-riek you should consider adding the orangepi-config script (i dont think its on this distro? never had to check lol)
