### ISSUE TITLE
Newbie Question on updates

### ISSUE THREAD

**Issue by gal-orlanczyk** [Joshua-Riek/ubuntu-rockchip#471]
Is there a way to get updates after starting from the image?

For example if you solved something and I don't want to start from scratch.

Sorry if this is a stupid question.

**Comment by Joshua-Riek** [comment]
You can receive most changes by updating your system with apt. There are a few exceptions, such as pre-installed programs and a few misc services. In general, I try to make all changes available to users and distribute them with my [Launchpad PPA ](https://launchpad.net/~jjriek/+archive/ubuntu/rockchip).

There is a unique case as a new Rockchip 6.1 kernel is coming out in about a month, all current users will be able to update their system and use this kernel. But this will not be an automatic update as I do not want to break perfectly running systems.  I'm sure the new kernel will have a lot of bugs that need to be flushed out, but users will still be able to get this kernel by entering `sudo apt install linux-rockchip-6.1` in a terminal. Please do note this is not available yet and will take a lot of development time.
