### ISSUE TITLE
The speed of upgrade is so slow, how to improve it?

### ISSUE THREAD

**Issue by BaconSoong** [Joshua-Riek/ubuntu-rockchip#473]
as picture shown, the speed is 8146B/s.
![截图 2023-11-18 22-38-30](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/35841217/16461233-f6af-44e7-a38b-d4edbd3f97eb)

**Comment by BaconSoong** [comment]
and how to check i have upgraded successfully?

**Comment by Joshua-Riek** [comment]
There should be ubuntu mirrors available for different regions, I'm unable to look up an exact list right now. But it should be easily doable.

**Comment by Joshua-Riek** [comment]
You can change the `/etc/sources.list` file to use a ubuntu mirror for your region.

For example, users in China may want to use `repo.huaweicloud.com` for better download speeds.
```
deb http://repo.huaweicloud.com/ubuntu-ports/ jammy main restricted universe multiverse
#deb-src http://repo.huaweicloud.com/ubuntu-ports/ jammy main restricted universe multiverse

deb http://repo.huaweicloud.com/ubuntu-ports/ jammy-security main restricted universe multiverse
#deb-src http://repo.huaweicloud.com/ubuntu-ports/ jammy-security main restricted universe multiverse

deb http://repo.huaweicloud.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
#deb-src http://repo.huaweicloud.com/ubuntu-ports/ jammy-updates main restricted universe multiverse

deb http://repo.huaweicloud.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
#deb-src http://repo.huaweicloud.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
```

More information: https://askubuntu.com/questions/39922/how-do-you-select-the-fastest-mirror-from-the-command-line

**Comment by BaconSoong** [comment]
thank u very much!
