### ISSUE TITLE
BCM bluetooth&wifi has still been not supported.

### ISSUE THREAD

**Issue by BaconSoong** [Joshua-Riek/ubuntu-rockchip#475]
i find official ubunut image that supports the BCM bluetooth & wifi. The correct kernel print is as picture shown:
![P31119-092447](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/35841217/89a4d56f-aba2-4cae-8d90-c6673b3bd9cf)
Here is the official dts & url.file:///home/i/Downloads/rk3588-rock-5b.dts
[https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr4.1/arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dts](url)

**Comment by Joshua-Riek** [comment]
What?

**Comment by BaconSoong** [comment]
#454 The problem is still, the above picture is the dmesg of official ubuntu that bluetooth&wifi works. So Cloud it be caused by dts?
