### ISSUE TITLE
NVME Not visible in RK1 Image

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [Joshua-Riek/ubuntu-rockchip#487]
Hello,

Trying to use the Turing Pi 2 with RK1 module image, having an issue where when doing a lspci or fdisk -a the NVME thats installed doesnt appear.  Checking out the DMESG i get a lot of weird traces as well, not sure if any of this is expected behavior.

attaching the log of the dmesg, see if anything else is needed 
[dmesg.txt](https://github.com/Joshua-Riek/ubuntu-rockchip/files/13481372/dmesg.txt)

One other curious question that you might or might not know, if i just used standard UBUNTU images for ARM would they work? the documentation on Turings site says fully supported but then i see Jeff Geerling referencing your code instead so it makes me believe they havent come up with a real supported solution as their OS Install documentation is blank and they are shipping GA RK1 modules today!

**Comment by Joshua-Riek** [comment]
> Trying to use the Turing Pi 2 with RK1 module image, having an issue where when doing a lspci or fdisk -a the NVME thats installed doesnt appear. Checking out the DMESG i get a lot of weird traces as well, not sure if any of this is expected behavior.

I see a lot of things crashing and have seen this before. From my understanding the OS iinstall is corrupted, please try to re-install. I'm not a fan of flashing with the UI method as it is slow and caused issues like this for me in the past (such as the UI showing that the install has finished before it actually has, i think this is fixed, but i cant be bothered to test right now).

> One other curious question that you might or might not know, if i just used standard UBUNTU images for ARM would they work? the documentation on Turings site says fully supported but then i see Jeff Geerling referencing your code instead so it makes me believe they havent come up with a real supported solution as their OS Install documentation is blank and they are shipping GA RK1 modules today!

You can not use a standard Ubuntu image for ARM with RK3588 devices.

Standard Ubuntu uses an UEFI bootloader and mainline Linux kernel. When it comes to the RK3588 SOC both of these are very far from being mature. So it requires a massively hacked up solution, I've been trying my best with what is aviable - we are stuck with u-boot and an android kernel that is a total mess to work with. I would say you may be able to run an offical Ubuntu for ARM image in 1-2 years, but expect problems to be encountered.

>  it makes me believe they havent come up with a real supported solution as their OS Install documentation is blank and they are shipping GA RK1 modules today!

I saw a preview of the documentation about 1 hour ago, it should be coming soon, but i dont have exact details.

**Comment by VDI-Tech-Guy** [comment]
Just curious what method of installing on the RK1 would you recommend if not the UI via the BMC?  

I did upgrade the firmware to v2.0.4 on the BMC but because there wasn't a SD Slot I just figured UI was the best path forward

**Comment by Joshua-Riek** [comment]
I use MASKROM mode, but the process is very hard to explain, and not user-friendly. This process will basically be flashing the RK1 over a USB cable. 

The link I have to the RK1 documentation covers this process. But I don't want to get into trouble by sharing that yet.

**Comment by VDI-Tech-Guy** [comment]
Gotcha, don't want u to get in trouble either, I'll try again via UI see if it fails less and report back

**Comment by VDI-Tech-Guy** [comment]
Do u happen to know why the rk1 doesn't want to boot from nvme by default either?

**Comment by Joshua-Riek** [comment]
The system can only boot from the eMMC, but during the boot process, U-Boot can find your NVMe drive and boot an operating system on it. This is the default behavior. 

The boot order is hardcoded in the bootloader, but with some u-boot command line editing, you can modify the exact order.

**Comment by VDI-Tech-Guy** [comment]
Tried with the UI again and it failed, still causing lots of errors/Panics so guess i need to wait to figure out whats going on, i'd assume your USB load method is a proper path to go just gotta wait for instructions....

is there anyone i could reach out to via Turing team to gain access to that pre-page?

**Comment by VDI-Tech-Guy** [comment]
nvm i saw in discord they are gonna bring the page online tomorrow

**Comment by Joshua-Riek** [comment]
The docs have been released.

https://docs.turingpi.com/docs/turing-rk1-flashing-os

**Comment by daniel-kukiela** [comment]
I'm curious to see if flashing with USB will succeed.
By the way, both flashing methods (using UI or USB cable) utilize maskrom mode.
The UI issue is described in the docs and will be fixed (showing 100% after ~2-3 minutes).
Flashing through UI is going to be faster in the future, much faster, and I would not discourage it. It's so much more convenient :)
Anyway, I'm curious to see the results so please either ping me here, and/or (better) on our Discord
