### ISSUE TITLE
docker-ce installation issue

### ISSUE THREAD

**Issue by dennismij** [Joshua-Riek/ubuntu-rockchip#504]
fresh installation of v 1.30, trying to install docker-ce, but got the following broken packages. Any advice? Many thanks

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 iptables : Depends: libip4tc2 (= 1.8.7-1ubuntu5) but 1.8.7-1ubuntu5.1 is to be installed
            Depends: libxtables12 (= 1.8.7-1ubuntu5) but 1.8.7-1ubuntu5.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Joshua-Riek** [comment]
Did you follow the instructions on Docker's website? It works for me.

https://docs.docker.com/engine/install/ubuntu/

```
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```
