### ISSUE TITLE
rock5a how to switch to Wayland?

### ISSUE THREAD

**Issue by eternal-Eason** [Joshua-Riek/ubuntu-rockchip#505]
Hello! My board is rock5a, burning the image (Ubuntu-22.04.3-preinstalled-Desktop-Ar64-Rock-5A) found that using the browser chromium, choppy animation, now using x11, how to switch to Wayland? thank you.

**Comment by eternal-Eason** [comment]
![47b503b36d5ecdafae346cb9e63e568](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/111413176/61e71ec9-b00d-43df-8093-185f042232ea)
Error message when first boot

**Comment by eternal-Eason** [comment]
How to debug this problem？

**Comment by Joshua-Riek** [comment]
X11 is very slow and choppy, Wayland is much better and the only supported environment at the moment.

You should try to re-install because the setup install failed.

**Comment by bagong** [comment]
But Chromium doesn't run in actuall Wayland, right? Or if one switches to it, hardware-support get's lost, right?

**Comment by eternal-Eason** [comment]
> X11 is very slow and choppy, Wayland is much better and the only supported environment at the moment.
> 
> You should try to re-install because the setup install failed.

Thank you for your response. The root file system I compiled had some issues, but after recompiling it, I won't encounter those errors again. Thank you.
