### ISSUE TITLE
How to enable i2c?

### ISSUE THREAD

**Issue by afatsum93** [Joshua-Riek/ubuntu-rockchip#506]
Hi, 

I am not very experienced in Linux systems, but I installed ubuntu 22.04 to my orange pi 5 and want to use i2c devices. 
when I do i2cdetect -y 0, I can not see my device. (I have tested it with a rpi and it works)

Can you help me with the procedure to enable i2c ?

Thanks

**Comment by Joshua-Riek** [comment]
You will need to enable the device tree overlay for i2c. They are located in /boot/firmware/dtbs/overlay/. 

Below is how to enable them.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Device-Tree-Overlays

**Comment by afatsum93** [comment]
Thanks a lot! It worked.
I added rk3588-i2c5-m3 to use pins 3 & 5 on my 5b.

**Comment by zahra-eft** [comment]
how do you do it?
