### ISSUE TITLE
rk3588 adaptation

### ISSUE THREAD

**Issue by liuzhe1947** [Joshua-Riek/ubuntu-rockchip#507]
HI Joshua-Riek

I have a rk3588 motherboard that was originally designed with the Android 12 system. I have extracted the device tree. Could you please adapt it to the Ubuntu system? Thank you.
This is the device tree file I extracted. 

Model:k20p-Main
CPU: Rockchip RK3588;
GPU: ARM Mali-G610 MP4 ;
OS: Android 12.0 OS;
DDR4 8GB+64GB
Support: 1000M LAN, 2.4G/5.8G +BT4.2;  (module RTL8821CS)

1.https://github.com/liuzhe1947/Rk3588-Information
2.https://wwmh.lanzoul.com/iQH471hew1fg code:5rd8
![微信图片_20231211145749](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/11643633/08af0d27-40f3-41d0-8897-3db62e95b447)
![微信图片_20231211145738](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/11643633/3cb2cbdf-9c5d-4b6f-949b-7720cf879fe9)

**Comment by Joshua-Riek** [comment]
I don't want to reverse-engineer an Android device tree for a random RK3588 board. This will take way too much time and effort.

**Comment by liuzhe1947** [comment]
Sorry, after my testing, this is a universal device tree. I have replaced the Armbian device tree with my own, and there is no problem booting it up.
