### ISSUE TITLE
Can I install XFCE from ubuntu server version?

### ISSUE THREAD

**Issue by solaris111** [Joshua-Riek/ubuntu-rockchip#511]
I'd like XFCE more than gome,and using Xubuntu on my latop.
I buy a roc-3588s-pc,and happy to see your project has support it.Is it possible to install XFCE which based ubuntu server?Can video accleration and opengl works well?

**Comment by Joshua-Riek** [comment]
You can install XFCE, but X11 is very bad on this platform. Hardware acceleration and OpenGL will perform poorly. 

Any improvement in this area must come from mainline Linux, which will take a lot of time and effort from the open-source community.
