### ISSUE TITLE
OrangePi 5 Module WiFi dont Work Ubuntu server

### ISSUE THREAD

**Issue by WINTX** [Joshua-Riek/ubuntu-rockchip#512]
I have an orange pi 5 with its nvme Wifi module but it doesn't work, if I type iwconfig nothing appears, I don't know if I'm doing something wrong. I use Ubuntu server and the latest version

thnx!

![imagen](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/9059217/056b1be6-87dd-46b7-8ae8-79dd4a2b3c74)

I ran the following command but nothing

`sudo sed -i 's/overlays=/overlays=ap6275p /g' /boot/firmware/ubuntuEnv.txt`

**Comment by dsburns** [comment]
@Joshua-Riek - Can confirm the same issue on my board.  I'm using the wifi module found here: https://a.co/d/52SdOc6

Does this require a specific overlay?

**Comment by Joshua-Riek** [comment]
it will work, does not need an overlay its pcie

**Comment by dsburns** [comment]
Sorry, I just realized.  I'm running an Orange PI 5 Plus.  I've tried two different modules and the OS doesn't recognize either.

**Comment by Joshua-Riek** [comment]
This gives me no information?
