### ISSUE TITLE
Ubuntu on Firefly Station M3

### ISSUE THREAD

**Issue by Stat10m3RK** [Joshua-Riek/ubuntu-rockchip#513]
Is it possible to install Ubuntu on Station M3 internal storage instead of having to boot it from a sd card every time? If yes, how we can do it?

**Comment by Joshua-Riek** [comment]
I think there is a device tree for it in the kernel, but I don't know the current u-boot state. 

If you want to do some hacking, it should not be very hard.

**Comment by Stat10m3RK** [comment]
I found this for Armbian: https://i12bretro.github.io/tutorials/0434.html. I wonder if it works with Ubuntu somehow.

**Comment by Joshua-Riek** [comment]
You should be able to use this image, its the same board from my understanding.

https://joshua-riek.github.io/ubuntu-rockchip-download/boards/roc-rk3588s-pc.html
