### ISSUE TITLE
problem about building kernel

### ISSUE THREAD

**Issue by BaconSoong** [Joshua-Riek/ubuntu-rockchip#514]
as picture shown，dpkg-buildpackage: 错误: debian/rules binary subprocess returned exit status 2.
![图片](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/35841217/98834cbe-c176-4559-8934-5afa07d97d9b)
help me, how could i process? the computer i used is amd64 architectural one.

**Comment by idkwhodatis** [comment]
this build is for arm64 arch
