### ISSUE TITLE
SSH / lan connection refused (orangepi 5)

### ISSUE THREAD

**Issue by seler69** [Joshua-Riek/ubuntu-rockchip#537]
Hello everyone!

im trying Joshua's ubuntu for frigate (miali GPU support for encoding video from my camera)

i have flashed my ssd drive with latest "desktop" ubuntu

sadly i dont have right now standard mouse/keyboard

i tried ssh but i get memo "connection refused"
i tryied "ssh root:192.168.1.35:22" ; "ssh ubuntu"192:168.1.35:22" ; "ssh 192.168.1.35:22"

any idea? im on win 10 (powershell and putty) gives the same resoult 
thanks!

///
i got hdmi cable and i see on my TV "system configuration window" so its booting properly!

**Comment by Joshua-Riek** [comment]
You will need to setup an account with a mouse and keyboard for the desktop version.
