### ISSUE TITLE
TPM support?

### ISSUE THREAD

**Issue by ChainsightLabs** [Joshua-Riek/ubuntu-rockchip#547]
Hi,
Firstly, just wanted to say thank you so much for your work on this project, it is greatly appreciated!
I was wondering if there is / plans to be support for TPM 2.0?
Thanks.

**Comment by Joshua-Riek** [comment]
TPM is not supported by the RK3588 hardware. You may be able to get it working by wiring it up yourself or getting a TPM PCIe card, but i have no idea if the software supports it.
