### ISSUE TITLE
Bluetooth Nova IndieDroid

### ISSUE THREAD

**Issue by zmrasim** [Joshua-Riek/ubuntu-rockchip#559]
Bluetooth not recognized Nova IndieDroid.

**Comment by Joshua-Riek** [comment]
This has been fixed with a firmware update.

**Comment by zmrasim** [comment]
Much appreciated .

Zafer Rasim, MD, FRCSC


The information transmitted is intended only for the addressee and may
contain confidential and/or privileged information. Any review,
retransmission, dissemination or other use of or taking any action in
reliance upon this information by persons or entities other than the
intended recipient is prohibited and may be unlawful. Please note that any
views, advice or opinions contained in this communication are those of the
sending individual and not necessarily those of the hospital. If you
received this in error please advise the sender and return it to the
address above and delete the material from any computer. Please note that
electronic mail, to, from, or within the hospital, may from time to time be
the subject of a request under the Freedom of Information Act.

A committee is a group that keeps minutes and loses hours.
Milton Berle
