### ISSUE TITLE
Widevine not supported

### ISSUE THREAD

**Issue by freezbeeee** [Joshua-Riek/ubuntu-rockchip#565]
Hello, I have see a video on youtube from leepspvideo and your ubuntu support Widevine on opi 5, on my opi 5 plus, I can't go on netflix, disney+, etc... hope you can fix that.

**Comment by Joshua-Riek** [comment]
It does work last I checked, does it not work for you?

**Comment by freezbeeee** [comment]
Do you need some files like logs ?

**Comment by Joshua-Riek** [comment]
You will need to spoof the browser, use the below command.
```
chromium-browser --user-agent="Mozilla/5.0 (X11; CrOS aarch64 15236.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
```

**Comment by freezbeeee** [comment]
damm that’s worked, big thanks for your job

**Comment by bryce-g** [comment]
Hello Josh, the spoof isn't working for Netflix and other widevine dependant streaming services. Any pro tips?

**Comment by nrpetonr** [comment]
confirm that browser spoofing does not work anymore.
