### ISSUE TITLE
Audio not working over USB-C

### ISSUE THREAD

**Issue by midarq** [Joshua-Riek/ubuntu-rockchip#569]
Hello,

despite having seen similar posts regarding this matter:

https://github.com/Joshua-Riek/ubuntu-rockchip/issues/184

https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/183

unfortunately, I do not get any audio output through USB-C. This issue is not present when I run JELOS on the same device, Please let me know if I can share any logs to give further insight into the problem.

**Comment by Joshua-Riek** [comment]
On what device?

**Comment by midarq** [comment]
Orange Pi 5B

**Comment by midarq** [comment]
I should add that this is a USB-C to HDMI connection.

**Comment by Joshua-Riek** [comment]
Works fine for me, closing.
