### ISSUE TITLE
Orange Pi 5 Mainline 6.7 SSH login incorrect

### ISSUE THREAD

**Issue by aidapsibr** [Joshua-Riek/ubuntu-rockchip#570]
I'm attempting to test out the 6.7 mainline kernel, but I can't seem to login over SSH. I've confirmed with multiple nvme SSD. SSH agent is running, IP acquired, waited several minutes for user provisioning and ubuntu/ubuntu doesn't auth.

Latest release works fine, just not mainline build.

### Build tested
https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7515530857

**Comment by Joshua-Riek** [comment]
It may take a few minutes for cloud-init to create the default user account. Please wait 1-2 minutes after the first boot and it should work just fine.

**Comment by aidapsibr** [comment]
This one was user error, apologies. I accidentally flashed the official image and didn't catch my error.

**Comment by aidapsibr** [comment]
I had a SM991 NVMe overheat and fry itself during the first flashing and I got a little flustered. heh

**Comment by Joshua-Riek** [comment]
Ah gotcha! I'm glad its working for ya!
