### ISSUE TITLE
how to patch kernel for rock 5b to enable ebpf?

### ISSUE THREAD

**Issue by ohyeah521** [Joshua-Riek/ubuntu-rockchip#576]
Hello, I want to modify the configuration information of rock5b's kernel. How can I modify the code to patch it?
```
CONFIG_KPROBES=y
CONFIG_KRETPROBES=y
CONFIG_IKHEADERS=y
```

**Comment by Joshua-Riek** [comment]
You can compile the kernel as shown on the wiki.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Kernel

**Comment by ohyeah521** [comment]
@Joshua-Riek  Thank you for your answer. I would like to know how to modify the kernel configuration information through workflows. Is it to modify the /config/kernels/bsp.conf file?

**Comment by Joshua-Riek** [comment]
Yes, you may need to remove the launchpad ppa or put your kernel package on hold so my updates do not overwrite your changes.

**Comment by ohyeah521** [comment]
@Joshua-Riek  thanks

**Comment by ohyeah521** [comment]
Is the following writing correct?
```
KERNEL_REPO=https://github.com/Joshua-Riek/linux-rockchip.git
KERNEL_BRANCH=linux-5.10-gen-rkr6
KERNEL_VERSION=5.10.160
KERNEL_CLONE_DIR=linux-rockchip
KERNEL_DEFCONFIG=rockchip_linux_defconfig
DPKG_BUILDPACKAGE=y
CONFIG_KPROBES=y
CONFIG_KRETPROBES=y
CONFIG_IKHEADERS=y
```

**Comment by Joshua-Riek** [comment]
Yes, I looked at your build and you need to rebase the ubuntu-rockchip repo. I was doing a test build as grub was just added as a ubiquity dependency. I force pushed over the commit reverting the change for now.

**Comment by ohyeah521** [comment]
@Joshua-Riek  Hello, I have encountered a new problem. I found in the .github/workflows/build.yml file.
```
run: sudo ./build.sh --board=orangepi-5 --kernel-only 
run: sudo ./build.sh --board=orangepi-5 - -rootfs-only
```
the default compiler is the orangepi-5 development board. Is this universal? Or do I need to modify it to my target development board, such as rock-5b?

**Comment by Joshua-Riek** [comment]
It does not matter, currently its a hack just to build the rootfs. After the rootfs is built it will be configured per board.
