### ISSUE TITLE
Failing to boot on Orange Pi 5 v1.32

### ISSUE THREAD

**Issue by juwonpee** [Joshua-Riek/ubuntu-rockchip#578]
Last version i tested working was 1.29
Possibly the same issue as [https://github.com/Joshua-Riek/ubuntu-rockchip/issues/533](url)

**Comment by Joshua-Riek** [comment]
Uhhh, do you have boot logs? I've tested this without issue.

**Comment by joshuataylor** [comment]
Also works with latest for me both desktop/server, NVME/SD.

**Comment by juwonpee** [comment]
> Uhhh, do you have boot logs? I've tested this without issue.

Sorry I dont have a uart device so the info i can provide is limited. Ill close this as it seems its specific to my machine.
