### ISSUE TITLE
i2c speed

### ISSUE THREAD

**Issue by afatsum93** [Joshua-Riek/ubuntu-rockchip#582]
Hi all, 

After enabling i2c and having it work correctly, I would like to ask what is the base clock speed(baudrate), and whether it is possible to increase the speed of the i2c bus. 
(100kHz/400kHz/1MHz... )

Thanks!

**Comment by Joshua-Riek** [comment]
This needs more information, what board and what i2c interface.?

**Comment by afatsum93** [comment]
Hi, sorry for the missing information.

I use OPi-5B 8gb and rk3588-i2c5-m3.

**Comment by afatsum93** [comment]
Hi, any update on this? 

Thanks a lot

**Comment by Joshua-Riek** [comment]
Im sorry but i do not have time to look up basic hardware info, do some research.
