### ISSUE TITLE
Obs cant start

### ISSUE THREAD

**Issue by Lolmc0587** [Joshua-Riek/ubuntu-rockchip#591]
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/59377673/b2b444f5-d6b3-4407-9112-ae5bd50a4978)
i already tried it on x11 too but not work

**Comment by Joshua-Riek** [comment]
Please see https://github.com/Joshua-Riek/ubuntu-rockchip/issues/375#issuecomment-1742050122
