### ISSUE TITLE
Orange Pi 3B - built in WiFi not working

### ISSUE THREAD

**Issue by lukaszsobala** [Joshua-Riek/ubuntu-rockchip#592]
Using the latest Ubuntu build (184), the built in WiFi is not recognized.

Might be related to the absence of the kernel module in the Ubuntu kernel (see: https://github.com/MichaIng/DietPi/issues/6659#issue-1922158975)

`sudo modprobe sprdwl_ng` did not fix the issue.

**Comment by Joshua-Riek** [comment]
Try latest build then update apt packages.

**Comment by Joshua-Riek** [comment]
Try latest build then update apt packages.

**Comment by lukaszsobala** [comment]
Thanks, apt upgrade alone helped (not tried before because of no Internet).

**Comment by Joshua-Riek** [comment]
I was missing firmware and was applied here:

https://github.com/Joshua-Riek/firmware

**Comment by defencedog** [comment]
@Joshua-Riek which of these firmware particularly relates to orangepi-3b? Because my WiFi is working however BT is not ... these modules if activated should get both operational or am I not correct?
