### ISSUE TITLE
Source code location for setting username and password at first startup

### ISSUE THREAD

**Issue by Z-Keven** [Joshua-Riek/ubuntu-rockchip#596]
Hello, I have a question. If I want to install the deb package after setting the username and password on the first system startup, where should I add the dpkg -i command in the source code?

**Comment by Z-Keven** [comment]
[libmali.zip](https://github.com/Joshua-Riek/ubuntu-rockchip/files/14122071/libmali.zip)
I tried installing these two libmali deb packages, which can solve the problem of green screen playing videos, not only for youtube. I have tested and found no other problems, but these two packages can only be installed after setting the user name and password when the system is started for the first time.

**Comment by DHDAXCW** [comment]
This will lose hardware acceleration and become llvm. Of course, there is no problem with llvm playing on the browser.
