### ISSUE TITLE
Add support for CM3

### ISSUE THREAD

**Issue by black-device** [Joshua-Riek/ubuntu-rockchip#597]
Would it be possible to add support for Ubuntu CLI builds on Radxa/Okdo CM3 Hardware, based on Rockchip's rk3566/3568?
Thanks!

**Comment by black-device** [comment]
Hello!, 
with the new release of the kernel and Ubuntu numbat, would it be possible to know if they have in mind to add compatibility at least for the server versions of Ubuntu on rk3566/rk3568?

Thank you!

**Comment by Dr3nz4r** [comment]
Would it be possible to also add the odroid m1 which is based on the rk3568b2?
