### ISSUE TITLE
Orange Pi 5 Plus v1.32 release randomly restarts

### ISSUE THREAD

**Issue by flyzet-prog** [Joshua-Riek/ubuntu-rockchip#608]
Hi, there.I have installed v1.32 Ubuntu 22.04.3 Desktop. with latest Frigate and Home Assistant Supervised installed on it.  I have random reboots   
and don't know what the root cause of this issue. Would be much appreciated if some one can help to resolve it. Where located the log and witch  one i have too check?
![Screenshot from 2024-02-03 17-37-30](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/8ed22af5-6f86-48f8-9e39-744806be69c1)

**Comment by Joshua-Riek** [comment]
What power supply are you using? Can you get boot logs from U-Boot with serial console?

**Comment by MarkhamLee** [comment]
I encountered this when using multi-port chargers that have 20, 40, and higher wattage outputs that never caused issues with my other devices and show up as PD on my USB cable that shows power output. Lower wattage outputs would cause reboots under load (like running Geekbench), higher wattage outputs would work fine for days and then randomly reboot. However, when using the official Orange Pi 5 or a MacBook power supply, I've had no issues. I.e., it not just power output it's how the power is managed

**Comment by flyzet-prog** [comment]
> U-Boot

I use Apple USB-C Power Adapter 20W. Sorry for dumb question can you tell me location of lof and command to show up?
Thank you for your reply

**Comment by flyzet-prog** [comment]
> What power supply are you using? Can you get boot logs from U-Boot with serial console?

I use Apple USB-C Power Adapter 20W. Sorry for dumb question can you tell me location of lof and command to show up?
Thank you for your reply

**Comment by flyzet-prog** [comment]
> I encountered this when using multi-port chargers that have 20, 40, and higher wattage outputs that never caused issues with my other devices and show up as PD on my USB cable that shows power output. Lower wattage outputs would cause reboots under load (like running Geekbench), higher wattage outputs would work fine for days and then randomly reboot. However, when using the official Orange Pi 5 or a MacBook power supply, I've had no issues. I.e., it not just power output it's how the power is managed

Hm, i will certainly  try Macbook 30 W charger. Now i use Apple USB-C Power Adapter 20W

**Comment by Joshua-Riek** [comment]
The Orange Pi 5 Plus does not support PD chargers... You need to use a STATIC 5v 4a power supply.

Closing issue.
