### ISSUE TITLE
Update QT6 VERSION 6.5.3 OR NEWED

### ISSUE THREAD

**Issue by InfernalWolf666** [Joshua-Riek/ubuntu-rockchip#620]
Mr. Joshua Rika.  I'm trying to build the Duck station game emulator, but it requires version QT 6.5.3, and QT6 6.2 is installed.  in the future please update the version.  I tried to build QT6 6.6.1, it built, but was installed in a different way.  it's too complicated for me to understand.  I tried copying the files with replacement .  but alas.

**Comment by Joshua-Riek** [comment]
Ubuntu 22.04 only provides QT 6.2.4 and Ubuntu 24.04 will provide QT 6.4.2. I would look for a previous version of the game emulator, or you will need to backport the required QT version yourself.

Source: https://launchpad.net/ubuntu/+source/qt6-base
