### ISSUE TITLE
Orange Pi 5 - Build fails due to missing packages for Noble

### ISSUE THREAD

**Issue by lucianor** [Joshua-Riek/ubuntu-rockchip#622]
Command: sudo ./build.sh --board=orangepi-5 --project=preinstalled-server --release=noble --kernel=mainline

While building an image with noble, the WiringPi packages are not available and therefore the image packaging stops.

This is due to line 27 of config/boards/orangepi-5.conf not having a switch for Ubuntu versions for installing WiringPi.

After commenting that line, I was able to build it. Keeping it here for reference and for an easy fix for a low severity issue.

**Comment by Jonathan-Chayna** [comment]
So now you have Ubuntu noble on Orange Pi 5 with GPU working?

**Comment by Joshua-Riek** [comment]
Yeah, I should have work-in-progress builds on GitHub actions soon.
