### ISSUE TITLE
build.sh Usage: $0 --board=[orangepi-5] --project=[preinstalled-desktop] --release=[jammy] --kernel=[bsp]

### ISSUE THREAD

**Issue by hakotani-o** [Joshua-Riek/ubuntu-rockchip#624]
Hi Joshua-Riek, thank you for your greate work.

1 I think build.sh --kernel=[rockchip-5.10] , for example.

2 ubuntu-rockchip/config/projects/preinstalled-desktop.sh

  I think mkdir -p "${chroot_dir}/etc/NetworkManager".

    # Networking interfaces
    (
        echo "[main]"
        echo "plugins=ifupdown,keyfile"
        echo "dhcp=internal"
        echo ""
        echo "[ifupdown]"
        echo "managed=true"
        echo ""
        echo "[device]"
        echo "wifi.scan-rand-mac-address=no"
    ) > "${chroot_dir}/etc/NetworkManager/NetworkManager.conf"

Thank you.

**Comment by Joshua-Riek** [comment]
What is the issue?

**Comment by hakotani-o** [comment]
Hi Joshua-Riek.
Sorry for the poor English.
thank you for your reply.

I see Usage and
 run  sudo ./build.sh --board=orangepi-5 --project=preinstalled-desktop --release=jammy --kernel=bsp -l
Error: "bsp" is an unsupported kernel.

about preinstalled-desktop.sh , It's my misunderstanding. Sorry.

Thank you.

**Comment by ohyeah521** [comment]
try this command:
`sudo ./build.sh --board=rock-5b --project=preinstalled-desktop --kernel=rockchip-5.10 --release=jammy`

**Comment by hakotani-o** [comment]
Hi ohyeah521.
Thank you for speaking with me right away.
I now try it.
Thank you.
