### ISSUE TITLE
Add support for youyeetoo R1

### ISSUE THREAD

**Issue by yytCharles** [Joshua-Riek/ubuntu-rockchip#625]
Is there any chance to make Ubuntu support for youyeetoo R1?
Hardware can be provided.

https://wiki.youyeetoo.com/r1

**Comment by SuperKali** [comment]
Hi @Joshua-Riek,

I have this board, and I would be happy if you could integrate it into the project. I am available to run tests or to understand the process of implementing an operating system.

Best regards.

**Comment by kiam001** [comment]
https://github.com/OpenSource-YYT

**Comment by kiam001** [comment]
https://github.com/orgs/OpenSource-YYT/discussions/1
