### ISSUE TITLE
Orange Pi 5B -The issue of being unable to enter the system after burning an image onto an SD card.

### ISSUE THREAD

**Issue by davidzong1** [Joshua-Riek/ubuntu-rockchip#632]
The SD card was burned with the ubuntu-22.04.3-preinstalled-desktop-arm64-orangepi-5b.img.xz image, and the serial log output ends during the WiFi driver initialization. 

The log is as follows:
Driver, version 101.10.361.20 (wlan=r892223-20220701-3)
[ 16.748480] drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd compiled on Feb 22 2024 at 00:06:51
[ 16.748480]
[ 16.748890] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 3, size 139264
[ 16.748941] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 4, size 0
[ 16.826106] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 7, size 35072
[ 16.826178] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 0, size 1776
[ 16.830161] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 5, size 65536
[ 16.836164] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 19, size 65712
[ 16.836215] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 20, size 262144
[ 16.836247] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 22, size 65536
[ 17.163055] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 9, size 32896
[ 20.438974] [dhd] STATIC-MSG) dhd_wlan_mem_prealloc : sectoin 9, size 32896

**Comment by Joshua-Riek** [comment]
This is the expected behavior, the desktop image requires a keyboard and monitor to setup a user account through the install wizard.

**Comment by davidzong1** [comment]
Thank you
