### ISSUE TITLE
Wiki for orangepi5 is out of date. SATA setting is not work.

### ISSUE THREAD

**Issue by SESProMax** [Joshua-Riek/ubuntu-rockchip#646]
The way of flashing image to SATA SSD is not work anymore, please update.
After adding overlay=sata, system still can not find ssd.

**Comment by Daavidaviid** [comment]
For me this: https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Orange-Pi-5-Plus
Work perfeectly

**Comment by SESProMax** [comment]
plus doesn't have sata option. Pi5 has. But it can’t find sata sad, after editing the env file.

在 2024年3月17日，07:59，David Guerin ***@***.***> 写道：

﻿

For me this: https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Orange-Pi-5-Plus worked perfectly

**Comment by Daavidaviid** [comment]
Well I don't know what you're trying to achieve but for me it worked with my orange pi 5. I did it today

**Comment by SESProMax** [comment]
I have followed wiki, added 'overlays=sata' to /boot/firmware/ubuntuEnv.txt, then reboot. This is no sata ssd in disk list. Did I do something wrong or miss some details.
________________________________
发件人: David Guerin ***@***.***>
发送时间: 2024年3月17日 12:18
收件人: Joshua-Riek/ubuntu-rockchip ***@***.***>
抄送: watchout ***@***.***>; Author ***@***.***>
主题: Re: [Joshua-Riek/ubuntu-rockchip] Wiki for orangepi5 is out of date. SATA setting is not work. (Issue #646)


Well I don't know what you're trying to achieve but for me it worked with my orange pi 5. I did it today

―
