### ISSUE TITLE
Orange pi 5 plus 16GB , obs not starting

### ISSUE THREAD

**Issue by stallion25** [Joshua-Riek/ubuntu-rockchip#648]
installed according to instruction : https://obsproject.com/download#linux

stallion@opi5z:~$ echo "$XDG_SESSION_TYPE"
wayland
stallion@opi5z:~$ obs
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted
stallion@opi5z:~$ sudo obs
[sudo] password for stallion: 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted
stallion@opi5z:~$ 

Looks like it is not OBS but image error

Regards for your work Joshua !

**Comment by Lolmc0587** [comment]
https://github.com/Joshua-Riek/ubuntu-rockchip/issues/375#issuecomment-1742050122
