### ISSUE TITLE
 Build Ubuntu 24.04 with Rockchip Linux 6.1 Build #267 is not working on Orange Pi 5

### ISSUE THREAD

**Issue by Jonathan-Chayna** [Joshua-Riek/ubuntu-rockchip#653]
Build Ubuntu 24.04 with Rockchip Linux 6.1 Build 267 is not working on Orange Pi 5. It just shows that it's booting but after that it fails (shows emergency option)

Sorry but i will give the boot details after

**Comment by Joshua-Riek** [comment]
The build for ubuntu 24.04 is a hacked together image for initial testing. It boots for me and you likely have a corrupted SD card or download.
