### ISSUE TITLE
Orangepi 5 Plus sound issue on 1.33 update(5.10 kernel)

### ISSUE THREAD

**Issue by flyzet-prog** [Joshua-Riek/ubuntu-rockchip#660]
Hi everyone. I can't use sound card, no sound when plugin headphone jack or with HDMI(when i plugin jack it does recognize headphone or headset). If i play some video on youtube or MPV player it's just stuck and i see loading logo, like waiting for audio, but it's should play even if no audio devices connected. This issue from the box, on clean system. Today i tried to install on SD card new [kernel 6.1](https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/8254903632). And sound works properly without any problem, HDMI, jack, even bluetooth audio. Maybe some one can help to resolve this or i  can try to reinstall some drivers,libraries, etc. Much appreciated for any reply.
![Screenshot from 2024-03-13 16-37-22](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/8a6b1968-b4f6-4db4-8345-2b214713343b)
![Screenshot from 2024-03-13 16-36-46](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/80a9615f-ee50-4297-99c9-72c26f85635c)

**This is Screenshots from kernel 6.1**

![Screenshot from 2024-03-13 13-09-51](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/9db4820f-ff54-4083-a34f-3e76825dd8a2)
![Screenshot from 2024-03-13 13-08-36](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/92593c14-197f-4112-a1ca-442307a1d1c8)
![Screenshot from 2024-03-13 13-09-10](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/8f2e011f-d177-4623-9702-f28ff970994d)
![Screenshot from 2024-03-13 13-07-29](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/32bf206e-2d1b-4dda-b23b-f302c899688a)
![Screenshot from 2024-03-13 13-07-51](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/5964e8fd-fcd5-4c0d-bc4f-df3ad3585548)
![Screenshot from 2024-03-13 13-09-00](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/73076482/ed3ee82f-1ee7-48c4-a6cd-11ebe8fd4916)

**Comment by Joshua-Riek** [comment]
Have you installed the 6.1 kernel on Ubuntu 22.04 and that is a problem? Sound should be working with 6.1 on Ubuntu 24.04, I've not test Ubuntu 22.04 or plan to support it with the 6.1 kernel.

**Comment by flyzet-prog** [comment]
> Have you installed the 6.1 kernel on Ubuntu 22.04 and that is a problem? Sound should be working with 6.1 on Ubuntu 24.04, I've not test Ubuntu 22.04 or plan to support it with the 6.1 kernel.

I'v installed 6.1 on SD card and booted from it and sound wokrs properly. But with Ubuntu 24.04 kernel 5.1 i have issue, installed like main system on NVME. and sound dosen't work it's spinning circle while playing video on youtube. When i plug mini jack and chose headphones,  the same issue. Can you please suggest me some module to reload or reinstall it which related to sound card? Thank you for your time.

**Comment by Joshua-Riek** [comment]
I'm confused on what system your running that has an issue.. Please tell me what ubuntu version and kernel that has a problem.

**Comment by flyzet-prog** [comment]
My kernel is 5.10.160-rockchip and Ubuntu 22.04.4 LTS

**Comment by flyzet-prog** [comment]
> My kernel is 5.10.160-rockchip and Ubuntu 22.04.4 LTS

My kernel is 5.10.160-rockchip and Ubuntu 22.04.4 LTS

**Comment by Joshua-Riek** [comment]
Sound works perfectly on that system, you likely broken some audio config. Please try and re-install the OS.

**Comment by flyzet-prog** [comment]
> Sound works perfectly on that system, you likely broken some audio config. Please try and re-install the OS.
OK. I will. Any way thank you for your reply
