### ISSUE TITLE
1.33 and pimox

### ISSUE THREAD

**Issue by stallion25** [Joshua-Riek/ubuntu-rockchip#662]
tried install proxmox/pimox, getting lots of missing packets not installable

The following packages have unmet dependencies:
 ceph-fuse : Depends: libfmt7 (>= 7.1.3+ds1) but it is not installable
 libpve-rs-perl : Depends: perlapi-5.32.1 but it is not installable
                  Depends: libssl1.1 (>= 1.1.1) but it is not installable
 libpve-u2f-server-perl : Depends: perlapi-5.32.1 but it is not installable
 librados2-perl : Depends: perlapi-5.32.1 but it is not installable
 lxc-pve : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 proxmox-backup-client : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 proxmox-backup-file-restore : Depends: libssl1.1 (>= 1.1.0) but it is not installable
                               Recommends: proxmox-backup-restore-image but it is not installable
 proxmox-websocket-tunnel : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 pve-cluster : Depends: perlapi-5.32.1 but it is not installable
 pve-qemu-kvm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
                Depends: libproxmox-backup-qemu0 (>= 1.3.0) but it is not going to be installed
                Depends: liburing1 (>= 0.7) but it is not installable
                Conflicts: qemu-system-common but 1:6.2+dfsg-2ubuntu6.17 is to be installed
                Conflicts: qemu-system-x86
                Recommends: numactl but it is not going to be installed
 vncterm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Deiiji** [comment]
Pimox is debian 10 or 11 based, ubuntu is more trixie ... I did it worked but I compiled my own repo for that
