### ISSUE TITLE
Is zswap built into the kernel?

### ISSUE THREAD

**Issue by SimplyCorbett** [Joshua-Riek/ubuntu-rockchip#671]
Is zswap built into the kernel and an option with the orange pi 5 plus?

I'm not sure how these boards do on compression as I just got mine but lz4 is generally fairly fast.

**Comment by SimplyCorbett** [comment]
zram works.

**Comment by DiegoBM** [comment]
How could you identify it as working? I cannot see any references to zram or zswap neither on dmesg, nor zramctl, nor /proc/swaps
I'm usign ubuntu server 2.3.2 btw, there doesn't seem to be any swap or zram there
