### ISSUE TITLE
Luckfox support

### ISSUE THREAD

**Issue by shenko** [Joshua-Riek/ubuntu-rockchip#688]
Hi, I just got a LuckFox Pico Mini M

rockchip RV1103

I signed up to forum, to ask where to find 'update.img' because its not specified,
I want ubuntu. Once my account is approved, should I point to this repo?

thanx

Luckfox Pico Mini B RV1103 Linux Micro Development Board, Integrates ARM Cortex-A7/RISC-V MCU/NPU/ISP Processors，onboard 64MB memory, with 128MB FLASH

**Comment by Joshua-Riek** [comment]
I do not support this device, I believe you are in the wrong place.
