### ISSUE TITLE
Orange Pi 5 Pro support

### ISSUE THREAD

**Issue by dai-j** [Joshua-Riek/ubuntu-rockchip#694]
Hello, 

Orange Pi 5 Pro is now available. It seems to change quite a bit comparing to the original Orange Pi 5/5B. Wondering if you have any plans to support this new board?

http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-Pro.html

Thanks for your awesome work so far!

**Comment by Joshua-Riek** [comment]
Yes, this will be supported, but I need the hardware first.
