### ISSUE TITLE
Ubuntu server builds? (request)

### ISSUE THREAD

**Issue by juwonpee** [Joshua-Riek/ubuntu-rockchip#695]
I want to use my orange pi as a headless server with a minimal memory footprint but the manufacturer provided images either has a really wierd configuration that I have to work around and chinese repositories that can be unreliable at times. 
Would it be possible for ubuntu server builds to be added?

Thanks a lot for your work!

**Comment by Joshua-Riek** [comment]
I have ubuntu server builds with standard repositories. I do not understand the request.
