### ISSUE TITLE
OrangePi 5 Plus Ubuntu 24.04 LTS Beta MPV has bad performance

### ISSUE THREAD

**Issue by HZFrodo** [Joshua-Riek/ubuntu-rockchip#703]
With Ubuntu 24.04 LTS Beta, 1080P HLS stream drops frames.

Maybe this patch was missed when Ubuntu 24.04 LTS Beta released?

https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/638#discussioncomment-9087653

![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/25219792/71f80715-524c-4a72-8085-aa513c7a8bfd)

Thank you for your great works.

**Comment by nyanmisaka** [comment]
Yes. Some video containers such as m3u8/mpegts require that patch to trigger hardware acceleration. This is a quirk in MPV.

**Comment by Joshua-Riek** [comment]
This patch https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/638#discussioncomment-9087653, was not yet included. I can try and include it later today, could you provide a link to the video file you tested so I can easily reproduce the issue? I have a lot of bugs to work on.

**Comment by HZFrodo** [comment]
> This patch [#638 (reply in thread)](https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/638#discussioncomment-9087653), was not yet included. I can try and include it later today, could you provide a link to the video file you tested so I can easily reproduce the issue? I have a lot of bugs to work on.

@Joshua-Riek 
I just cannot wait the fixed MPV package since I am so excited with your release ;)
And I reverse-engineered the MPV ELF binary to force check the AV_CODEC_HW_CONFIG_METHOD_INTERNAL flag as https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/638#discussioncomment-9087653 says, MPV works well now, no any performance issue.
You can apply the patch and release a new MPV ;)

**Comment by Joshua-Riek** [comment]
Build is running now on Launchpad, it should be downloadable from apt in a few hours.

https://launchpad.net/~jjriek/+archive/ubuntu/rockchip-multimedia/+build/28054068

**Comment by HZFrodo** [comment]
> Build is running now on Launchpad, it should be downloadable from apt in a few hours.
> 
> https://launchpad.net/~jjriek/+archive/ubuntu/rockchip-multimedia/+build/28054068

New MPV installed via apt, tested some video files and some live streams, all good, we can close this issue now.
