### ISSUE TITLE
Radxa zero 3W does not boot

### ISSUE THREAD

**Issue by oikosbg** [Joshua-Riek/ubuntu-rockchip#706]
Radxa zero 3W does not boot or there is no HDMI output

**Comment by Joshua-Riek** [comment]
What Ubuntu version?

**Comment by oikosbg** [comment]
Ubuntu 24.04 LTS Beta is not booting on Radxa zero 3W

Ubuntu 22.04 boot fine on Radxa zero 3w

**Comment by Joshua-Riek** [comment]
I see, will look into it, thank you for reporting the problem.

**Comment by Joshua-Riek** [comment]
I tested the latest build and it works fine.

https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/8808046061

**Comment by ArduCrow** [comment]
I have just tried to flash ubuntu_jammy_xfce_b6 and get no hdmi output/no boot. The green LED gives a double flash every second.

**Comment by Joshua-Riek** [comment]
The ubuntu_jammy_xfce_b6 image is built by Radxa directly, I have no involvement with it.
