### ISSUE TITLE
LibreOffice Will Not Launch

### ISSUE THREAD

**Issue by JFLim1** [Joshua-Riek/ubuntu-rockchip#711]
LibreOffice will not launch either by clicking on the "LibreOffice Writer" icon or launch from terminal.

```
jfl@localhost:~$ libreoffice --writer
Warning: failed to launch javaldx - java may not function correctly
ERROR 4 forking process
jfl@localhost:~$ libreoffice
Warning: failed to launch javaldx - java may not function correctly
ERROR 4 forking process
jfl@localhost:~$ 
```

**Comment by Joshua-Riek** [comment]
May be a side effect of the desktop installer not working as the system can not properly setup.

**Comment by Joshua-Riek** [comment]
Because of the installer issues I'm removing the Desktop image for the Ubuntu 24.04 Beta. I have to wait a few days for Ubuntu to update their packages, I can not do it manually myself.

**Comment by JFLim1** [comment]
Hi @Joshua-Riek,

FYI, found a temporary solution to launch LibreOffice from command line:

`/usr/lib/libreoffice/program/soffice.bin`

**Comment by JFLim1** [comment]
Hi @Joshua-Riek,

A feedback.  Successfully install the new Ubuntu 24.04 v2 beta1 30 minutes ago.  The installer crash seems to be resolved with this new image.

LibreOffice will still refuse to launch by click on the "libreoffice icon" on the panel.  Same error:

```
jfl@jfl-opi5plus:~$ libreoffice
Warning: failed to launch javaldx - java may not function correctly
ERROR 4 forking process
```
Will launch with:

`/usr/lib/libreoffice/program/soffice.bin
`
