### ISSUE TITLE
Question: Availability and Features of Panfrost Driver in Ubuntu Versions

### ISSUE THREAD

**Issue by Yusepp** [Joshua-Riek/ubuntu-rockchip#713]
Hello,

I am reaching out to gather some information regarding the **Panfrost driver**, specifically its integration and capabilities within Ubuntu distributions hosted in this repository.

### Background
Recently, it has been announced that the Panfrost driver, which now includes support for the **Mali-G610 GPU**, has been successfully merged into the mainline Linux kernel. This is particularly exciting as it promises improved support and performance for devices using this GPU.

### Questions
1. **Inclusion of Panfrost Driver:**
   - Are there any current Ubuntu versions in this repository that come with the Panfrost driver pre-installed?
   - If so, which versions should I look at?

2. **Driver Capabilities:**
   - Does the Panfrost driver in these versions support the Vulkan API, or is it limited to OpenGL?
   - Are there any additional configurations or updates required to enable Vulkan support if it is available?

I appreciate the work being done here and am looking forward to integrating these developments into my Orange Pi 5B. Your guidance will be very helpful!!!

**Comment by Joshua-Riek** [comment]
> Recently, it has been announced that the Panfrost driver, which now includes support for the Mali-G610 GPU, has been successfully merged into the mainline Linux kernel. This is particularly exciting as it promises improved support and performance for devices using this GPU.

While this is a step in the right direction mainline Linux has **many** features not supported for RK3588 devices, so I'm not really focused on it. And besides the Panthor driver is not very good performance wise and has a lot of bugs. 

> Are there any current Ubuntu versions in this repository that come with the Panfrost driver pre-installed?

Technically the driver is no longer Panfrost but Panthor, there where efforts to backport the driver to the 6.1 BSP kernel, but I'm not going deal with it until the performance and bugs are worked out. While the driver "works" I would argue it's not usable or ready for standard users. 

Sadly we are currently stuck with a hostile fork of mesa called Panfork. I don't want to get into the details about the history of it's development, but it's that is a userspace hack that is no longer maintained. However, this is what I include in my ubuntu images as it's really the only GPU driver that works properly.

 > Does the Panfrost driver in these versions support the Vulkan API, or is it limited to OpenGL?

None of the drivers support Vulkan, but there is work on PanVK for Vulkan support, however based on the Panthor driver's state I would have little expectation.
