### ISSUE TITLE
24.04 BETA ROCK5A - Logitech MX Master 3 Mouse Doesn't Work

### ISSUE THREAD

**Issue by MyVizDrake** [Joshua-Riek/ubuntu-rockchip#726]
Rock 5A and 6.1 Kernel. USB Dongle based Logitech MX Master 3 Mouse doesn't work at all. Logitech M510 works fine.

I can provide whatever additional information is requested.  Just let me know!

**Comment by MyVizDrake** [comment]
No issues!  Just documenting issues as requested.  Appreciate your efforts and look forward to the day when I can use this on my Rock5A !

**Comment by Xeue** [comment]
I saw this initally, but at some stage my one started working...

**Comment by MyVizDrake** [comment]
@Xeue yeah, no luck for me ... still not working.  I'll wait patiently and see if we can resolve the A8 Bluetooth issue in which case I will use a Bluetooth Mouse / Keyboard.

**Comment by Joshua-Riek** [comment]
Should work with the noble release, please re-open if still an issue.

**Comment by MyVizDrake** [comment]
I had to change the channel on the mouse itself for it to work but it is in fact working.  Moving on! :-)
