### ISSUE TITLE
24.04 BETA ROCK5A - Radxa A8 Module Issues

### ISSUE THREAD

**Issue by MyVizDrake** [Joshua-Riek/ubuntu-rockchip#727]
Rock 5A w/ Radxa Wireless A8 and Kernel 6.1

WLAN seems to be OK (can nslookup or dig a domain) but cannot ping. Error says 

ping: socket: operation not permitted
ping: => missing cap_net_raw+p capability or setuid

Bluetooth is disabled and cannot be enabled so I cannot connect my alternate keyboard / mouse..

while testing WLAN via Software Update, it was checking / downloading ports and then the entire system locked up.

Can provide whatever additional information / logs as requested.

**Comment by Joshua-Riek** [comment]
Can you put the output of dmesg into a text file and upload it here? Also, what is the output of the command `ip a`?

**Comment by MyVizDrake** [comment]
As requested
[dmesg.txt](https://github.com/Joshua-Riek/ubuntu-rockchip/files/15065310/dmesg.txt)
[ip_a.txt](https://github.com/Joshua-Riek/ubuntu-rockchip/files/15065311/ip_a.txt)

**Comment by Joshua-Riek** [comment]
Ok so, I found a work around, on the command line enter the below commands.
```
sudo modprobe -r btusb
sudo modprobe btusb
```
Running these commands should not be required for bluetooth to work properly, but this is a start at least.

**Comment by MyVizDrake** [comment]
I did a quick test and it didn’t work but I am not convinced that I wasn’t the cause. Will revisit this in the next day or so …
 Appreciate it! 
On Fri, Apr 26, 2024 at 16:14, Joshua Riek - notifications at github.com ***@***.***&gt; wrote:              Forwarded by SimpleLogin to ***@***.*** from "Joshua Riek " with Re: [Joshua-Riek/ubuntu-rockchip] 24.04 BETA ROCK5A - Radxa A8 Module
 Issues (Issue #727) as subject
                        Ok so, I found a work around, on the command line enter the below commands.
sudo modprobe -r btusb
sudo modprobe btusb

Running these commands should not be required for bluetooth to work properly, but this is a start at least.

**Comment by MyVizDrake** [comment]
Tried it again and it definitely did not work  Made more difficult as I have no available mouse since my Logitech MX MAaster 3 doesn't work either.  Just kicked off apt upgrade in the hope that maybe something will change. I doubt it will work, but .... :-)

Let me know if I need to get anything else off of here to troubleshoot!

**Comment by Joshua-Riek** [comment]
Should work with the noble release, please re-open if still an issue.

**Comment by Joshua-Riek** [comment]
Try to enter the command `sudo modprobe btusb` and it should work.

**Comment by MyVizDrake** [comment]
I tried sudo modprobe -r btusb .... sudo modprobe btusb and just tried sudo modprobe btusb again at your direction .... nothing is showing up in the Gnome Bluetooh settings window.  It's not that it can't see the two devices I care about, it also can't see all of the other USB devices that Android image could see.  That being said, my ArchLinux install that actually has a working DSI display can't see any BT devices either ...

**Comment by MyVizDrake** [comment]
The BT device is available and running from what I can see ..>

![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/88993550/fa6a9c52-4bfa-4a11-8d60-730728a85ab1)
