### ISSUE TITLE
Cannot install libgl1-mesa-dri:armhf on Ubuntu 24.04

### ISSUE THREAD

**Issue by lukaszsobala** [Joshua-Riek/ubuntu-rockchip#728]
This package depends on `libllvm14` which is unavailable on Ubuntu Noble.

The closest available package in `libllvm14t64`. I could change the name of the dependency in the control file of the deb package and it installed correctly, but I am not sure if it works. libgl1-mesa-dri:armhf seems to be a dependency of Steam.

**Comment by Joshua-Riek** [comment]
Some libs where renamed due to the 32-bit time problem. Let me take a look at the dependencies of panfork and see what I can do.

**Comment by Joshua-Riek** [comment]
Ah I see the problem, I must re-build package to pull in the dependency name change.

**Comment by lukaszsobala** [comment]
> Ah I see the problem, I must re-build package to pull in the dependency name change.

Yes, the dependency name changed. Thanks!

**Comment by Joshua-Riek** [comment]
Hmm waiting for dependeny to update, it may take a few days for the Launchpad server to sync.

https://launchpad.net/~jjriek/+archive/ubuntu/panfork-mesa/+build/28129053

**Comment by lukaszsobala** [comment]
6 days and counting, is there a way to check how long to go?

**Comment by Joshua-Riek** [comment]
I've been trying to fix it for a few days with no luck. I'm going to try a hack next to fix things. The armhf package somehow finds libllvm14 instead of libllvm14t64 and libllvm14 no longer exists. 

I will try manually adding the dependency for libgl1-mesa-dri as shown below. 
```
Package: libgl1-mesa-dri
Section: libs
Architecture: any
Depends:
 libc6,
 libdrm-nouveau2,
 libdrm-radeon1,
 libdrm2,
 libexpat1,
 libgcc-s1,
 libglapi-mesa,
 libllvm14t64,
 libsensors5,
 libstdc++6,
 libxcb-dri3-0,
 libzstd1,
 zlib1g,
 mali-g610-firmware
```

**Comment by lukaszsobala** [comment]
It seems that is basically what I did (but using the "control" file in DEBIAN in the uncompressed deb package)

**Comment by Joshua-Riek** [comment]
Did it compile on your end?

**Comment by lukaszsobala** [comment]
I did not compile it at all but did more or less this: https://forums.linuxmint.com/viewtopic.php?t=35136

**Comment by Joshua-Riek** [comment]
I was able to get the package to build on a testing ppa for Launchpad. I will upload to my main ppa and should be available in a few hours.

**Comment by Joshua-Riek** [comment]
Its now on Launchpad and should work:

https://launchpad.net/~jjriek/+archive/ubuntu/panfork-mesa/+packages
