### ISSUE TITLE
wpa_supplicant

### ISSUE THREAD

**Issue by rgborn** [Joshua-Riek/ubuntu-rockchip#739]
the system is trying to start wpa_supplicant and fails with Failed to start wpa_supplicant.service: Unit wpa_supplicant.service not found.

**Comment by Joshua-Riek** [comment]
This is benign since the system uses Netplan. 

I assume you're referring to Ubuntu 24.04.

**Comment by rgborn** [comment]
Yes, 24.04 I am desperately trying to get my wifi interface to connect to my wifi network!

**Comment by rgborn** [comment]
Here is my  entry in the /etc/netplan/50-cloud-init.yaml file

network:
	version: 2
	ethernets:
		zz-all-en:
			match:
				name: "en*"
			optional: true
			dhcp4: true
		zz-all-eth:
			match:
				name: "eth*"
			optional: true
			dhcp4: true
	wifis:
		wlP2p33s0:
			optional: true
			access-points:
				"SSID":
					password: "XXXXXX"
			dhcp4: true

**Comment by rgborn** [comment]
Of course he indents are proper even though they don't show, and the SSID and Password have the correct entries in them.

**Comment by rgborn** [comment]
journalctl output.

and-networkd [960]: enP4p65s0: Reconfiguring with/run/systemd/network/10-netiplan-zz-all-en.network. md-networkd [960]: enP3p49s0: Reconfiguring with/run/systemd/network/10-netplan-zz-all-en.network.
and-networkd [960]: wlP2p33s0: Reconfiguring with/run/systemd/network/10-metiolan-wlP2p33s0.network. [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: Invalid env data
[998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data md-networkd [960]: wlP2p33s0: Link UP
md-networkd [960]: wlP2p33s0: Configuring with /run/systemd/network/10-metolan-w1P2p33s0.network.
md-networkd [960]: enP3p49s0: Configuring with/run/systemd/network/10-netplan-zz-all-en.network. md-networkd [960]: enP4p65s0: Configuring with/run/systemd/network/10-neho lan-zz-all-en.network.
[998]: udevmon.go: 149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data : retolar-ovs-cleanup.service OpenVSwitch configuration for cleanup was skipped because of an unmet condition check (ConditionFile
md[1] [ 998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
md[1]: Started lan-wpa-w1P2p33s0.service HPA supplicant for Er wlP2p33s0. Main process exited, code=exited, status=203/EXEC
md[1]
: B-wpa-wlP2p33s0.service:
emd[1]
: a-upa-wlP2p33s0.service: Failed with result 'exit-code'. Unable to parse uevent, err: cannot parse libudev event:
[998]:
udevmon.go:149: udev event error: [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: Unable to parse uevent, err: cannot parse libudev event: invalid env data invalid env data
[998]: udevmon.go:149: udev event error: [
invalid env data
invalid env data
998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: 998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data invalid env data
[ [998]:
udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
d [998]: udevmon.go:149: udev
d [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data d [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
d [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
d [998]: udevmon.go:149: udev event ad [ 998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
ad [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data cannot parse libudev event: invalid env data
od [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: od [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data Unable to parse uevent, err: cannot parse libudev event: invalid env data
od [998]: udevmon.go:149: udev event error: od [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
od [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
pd [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
pd [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
od [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: invalid env data
pd [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: Invalid env data
pd[998]:
pd [998]: udevmon.go:149: udev event error: Unable to parse uevent, err: cannot parse libudev event: Invalid env data
udevmon.go:149: udev event error: Unable to parse udevmon.go:149: udev event error: Unable to parse
uevent, err: cannot parse uevent, err:
apd [998]:
apd[998]: udevmon.go: 149: udev event error: Unable to parse uevent, err:
quant por: Unable to perse event, err:
libudev event: cannot parse libudev event: invalid env data cannot parse libudev event: invalid env data
invalid env data
cannot parse libudev event: invalid env data

**Comment by brussell-ac** [comment]
> This is benign since the system uses Netplan.
> 
> I assume you're referring to Ubuntu 24.04.

In 24.04, netplan 1.0 still requires the wpasupplicant package installed to be able to connect to wireless networks. As this package has been removed, I don't believe it is possible with the latest 24.04 images to connect to WiFi's using netplan out of the box - needing to manually transfer over the package, or connect via Ethernet first.

Perhaps CloudInit doesn't need the supplicant (?), but for those people using netplan, could you please add the wpasupplicant package back into the build image?
