### ISSUE TITLE
Enable `CONFIG_KSM` in kernel for `ksmtuned` support. 

### ISSUE THREAD

**Issue by bgulla** [Joshua-Riek/ubuntu-rockchip#745]
Looking for KSMTuned support in future releases. 

<img width="824" alt="image" src="https://github.com/Joshua-Riek/ubuntu-rockchip/assets/2697267/97fa9152-c823-4c3a-996e-629609ac6ff0">

**Comment by Joshua-Riek** [comment]
I enabled it for the Ubuntu 24.04 beta, I will enable it in the 5.10 kernel that comes with Ubuntu 22.04 tonight.

**Comment by Joshua-Riek** [comment]
Its been enabled on Ubuntu 22.04.
