### ISSUE TITLE
Ubuntu 24.04 Beta crashes after reboot

### ISSUE THREAD

**Issue by cantalupo555** [Joshua-Riek/ubuntu-rockchip#753]
When I'm using this Beta image on the memory card (/dev/mmcblk0) I haven't had any problems, I can restart several times.

The problem happens when I'm using NVMe (/dev/nvme0n1).
It installs normally, but if I restart the machine Ubuntu 24.04 Beta simply does not start.

Has anyone else gone through this?

**Comment by Joshua-Riek** [comment]
Did you update the SPI? Almost 99% of crashing / boot issues is because of a bad power supply or the SPI is not updated.

**Comment by cantalupo555** [comment]
Thanks for the feedback.  In reality, my problem is not the power supply, how can I update the SPI?  Would it be /dev/mtdblock0?

**Comment by Joshua-Riek** [comment]
Please review the below WiKi page for Ubuntu 24.04:

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Ubuntu-24.04-LTS#install-u-boot-to-the-spi-flash

**Comment by Joshua-Riek** [comment]
Awesome, enjoy!
