### ISSUE TITLE
Rock 3

### ISSUE THREAD

**Issue by woiza** [Joshua-Riek/ubuntu-rockchip#756]
Hi,
is there a reason why Rock 3 boards are not supported?

https://wiki.radxa.com/Rock3

**Comment by Joshua-Riek** [comment]
This is a hobby project, and my interest is primarily in RK3588 boards. I dont want to invest potentially hundreds of hours of development on something that does not interest me.

If money is involved in something I'm not  interested in, I'd be happy to have a conversation.
