### ISSUE TITLE
failed to build 24.04 images

### ISSUE THREAD

**Issue by clsx524** [Joshua-Riek/ubuntu-rockchip#771]
Hi, I am trying to build the image on my own without any modification to the code. This is run on ubuntu 24.04.

I ran `sudo ./build.sh --server-only --board=turing-rk1 --project=server --release=noble --kernel=rockchip-6.1` and it stopped with following errors
```
...
################### END debootstrap.log ################
P: Begin unmounting filesystems...
P: Saving caches...
mount: rootfs/dev: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
Error: in ./scripts/config-image.sh on line 54
Error: in ./build.sh on line 263
```

Does anyone know how to fix this?

----------
I am debugging the code and it failed at this line
```
mount dev-live -t devtmpfs "$mountpoint/dev"
```
which seems expecting a directory at $chroot_dir/dev. The chroot directory was created after decompressing file ubuntu-24.04-preinstalled-server-arm64.rootfs.tar.xz but my file doesn't contain dev directory.
There are errors before debootstrap, not sure if relevant. No other errors found in the logs
```
P: If the following stage fails, the most likely cause of the problem is with your mirror configuration or a caching proxy.
P: Running debootstrap...
P: Bootstrap will be foreign
/usr/sbin/debootstrap: 1840: cannot create /opt/build/chroot/test-dev-null: Permission denied
E: Cannot install into target '/opt/build/chroot' mounted with noexec or nodev
P: Begin unmounting filesystems...
P: Saving caches...
################# BEGIN debootstrap.log ################
```

**Comment by jtmack6** [comment]
Hi Xin,

Thanks for pointing out the debootstrap error coming from `lb`. 

Figured I would post this in you didn't find a workaround or anyone else runs into this. 

Setup:

24.04 with ZFS... 

I noticed this wasn't set on my volume:

```
zfs get devices /opt
NAME                   PROPERTY  VALUE    SOURCE
rpool/opt  devices   off       local
```

from zfsprops:

```
devices=on|off
         Controls whether device nodes can be opened on this file system.  The default value is on.  The values on and off are equivalent to the dev and nodev mount options.
```

Ran`zfs set devices=on /opt` and `lb` and `debootstrap` could do it's thang.
