### ISSUE TITLE
[24.04] Radxa A8 Module Bluetooth Issues

### ISSUE THREAD

**Issue by MyVizDrake** [Joshua-Riek/ubuntu-rockchip#782]
Originally from [here](https://github.com/Joshua-Riek/ubuntu-rockchip/issues/727) during the Beta
>I tried sudo modprobe -r btusb .... sudo modprobe btusb and just tried sudo modprobe btusb again at your direction .... nothing is showing up in the Gnome Bluetooh settings window. It's not that it can't see the two devices I care about, it also can't see all of the other USB devices that Android image could see. That being said, my ArchLinux install that actually has a working DSI display can't see any BT devices either ... I even turned BT off and back on again ..

Device seems to be available.

![327543878-fa6a9c52-4bfa-4a11-8d60-730728a85ab1](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/88993550/d82fdce9-4800-4f64-b52f-4a4dd7945ec2)

From [Kwankiu's ArchLinux-Installer](https://github.com/kwankiu/archlinux-installer/wiki/General#troubleshooting)
>Note: it seems like there may be issues with bluetooth on linux-radxa-rkbsp5-git (5.10.160), consider using linux-rockchip-joshua (5.10.160) if you need bluetooth.

 I am fairly certain I have the Radxa 5.10.160 kernel on that one (which so far is the only one I can get my Radxa 10FHD Display to work).

No rush. You're doing great work!

**Comment by Joshua-Riek** [comment]
I backported RTW89 from Linux 6.1 to provide improved performance and compatibility https://github.com/Joshua-Riek/linux-rockchip/commit/8285966d2a5693c7b461f30d3e822d06a18f7342. I will be honest that I have no intent to debug the wireless driver at this time, too much effort on my part.

**Comment by MyVizDrake** [comment]
Understood ... :-)

**Comment by MyVizDrake** [comment]
@Joshua-Riek closing this ... once I blacklisted all of these modules in blacklist.conf instead of blacklist it works.

> blacklist pgdrv
> blacklist btusb
> blacklist btrtl
> blacklist btbcm
> blacklist btintel

Fell victim to autocomplete and didn't notice it didn't do the complete file name.
On to my DSI display.

Thanks again!
