### ISSUE TITLE
Override cloud-init Configuration

### ISSUE THREAD

**Issue by jsantosa-minsait** [Joshua-Riek/ubuntu-rockchip#785]
Hi,

just a simple question. There is a way to override cloud-init configuration instead using the default files at `overlay/boot/firmware/*` without rebuilding the whole image. Just for the first startup.

I have tried to copy `user-data`, `network-config` and `meta-data` files into `/mnt/boot/firmware` folder after copying the image to the nvme drive but those files are override with `overlay/boot/firmware`. So there is no changes taken from my overrides.

Thanks in advance

Best regards,
Javier

**Comment by nilo85** [comment]
Is it server image? There is a fat32 partition where you can replace the files and they are used at first boot

**Comment by jsantosa-minsait** [comment]
> Is it server image? There is a fat32 partition where you can replace the files and they are used at first boot.
> 
> works for me, but not tried booting fork nvme, booting from emmc but suspect it should be universal

Thanks @nilo85 

Haven't seen that partition when flashing the image... and yer, it's the server one.

**Comment by nilo85** [comment]
I think it’s only there on the 24.04 version though, so it could be it’s missing on the 22.04 if that is what you are using

**Comment by jsantosa-minsait** [comment]
> I think it’s only there on the 24.04 version though, so it could be it’s missing on the 22.04 if that is what you are using

Thanks a lot @nilo85 
It works just fine on both distributions!! 

Regards
Javier
