### ISSUE TITLE
Ubuntu 24.04 (Orange Pi5B) Error show cpu (neofetch)

### ISSUE THREAD

**Issue by ArtemS2** [Joshua-Riek/ubuntu-rockchip#786]
In the beta version there was a display of processor cores, but in the release version it disappeared somewhere. (neofetch)
![1](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/69766464/fa3075ca-c959-4a57-b410-c44a5d04a576)

**Comment by cantalupo555** [comment]
Orange Pi 5 👇
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/12485871/1b262576-4009-454d-8b79-95e546c90d46)

**Comment by Joshua-Riek** [comment]
I see that python3 is not in the dependency list of Neofetch, it's required for multiple CPU detection. 

Thanks for reporting this, I've updated the package, it may take a few hours to be downloadable via apt.

https://launchpadlibrarian.net/729343706/neofetch_7.1.0-4+2_7.1.0-4+3.diff.gz
