### ISSUE TITLE
Errors when turning off. Ubuntu 24.04 Orange PI5B

### ISSUE THREAD

**Issue by ArtemS2** [Joshua-Riek/ubuntu-rockchip#787]
Errors when turning off.  This doesn’t seem to be critical, but it’s annoying.

![2](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/69766464/582cff78-cf06-4123-a2ab-583ce4b0cff1)

**Comment by Joshua-Riek** [comment]
Does this cause an actual problem such as the system not being able to power down??

**Comment by ArtemS2** [comment]
There are no particular problems with this, I was just confused by the error indication. The system turns on quickly when needed.

**Comment by Joshua-Riek** [comment]
Since it does not cause any problems, I likely will not look into this. 

Because the system is shutting down it starts to unload multiple kernel drivers including bluetooth and wifi, this is most likely why you are seeing this message.
