### ISSUE TITLE
NanoPC T6 HDMI0 Audio Left Channel stop working

### ISSUE THREAD

**Issue by Spirarementum** [Joshua-Riek/ubuntu-rockchip#790]
First allow me to thank you for the great work, time, and devotion.

**Issue:**
The left HDMI0 Channel stopped working today.
Both audio channel works on the HSMI1.
The only thing that changed was a system update and a manual reboot.

I am fishing here trying to diagnose the problem...Could this be linked to the last system update ?

Let me know if I can provide more info to help pinpoint the problem.

**Comment by wmport** [comment]
Everything works, check your hdmi cable

**Comment by Joshua-Riek** [comment]
What OS are you running?

**Comment by Spirarementum** [comment]
Just tested the cable.
Also tested on another monitor to rule out the hardware.
The HDMI0 left audio output from the NanoPC T6 stopped working right after the last update (yesterday).
Running Ubuntu 22.04LTS

**Comment by wmport** [comment]
I launched 22.04 on an SD card, with the latest update, on hdmi0 and hdmi1 all audio channels work.

**Comment by Spirarementum** [comment]
Thank you.
Again I have to compliment you on your work....Ubuntu 22.04 is working flawlessly on the nanopc-t6 :)
