### ISSUE TITLE
Bluetooth & Wifi conflict

### ISSUE THREAD

**Issue by chief-kh** [Joshua-Riek/ubuntu-rockchip#791]
Hello guys.
I don't know if I'm posting in a right repo...
I have such hardware/software:
Lenovo laptop with RTL8852BE adapter. OS: Xubuntu (updated to version 24.04 these days).
Issue description:
When I turn off bluetooth wifi works like a charm. But when I turn on bluetooth and connect to a speaker (JBL Flip 4) wifi works some time (5-10 minutes) and then just stops sending/receiving any packets to the router. It does not disconnect but just stops any network activity. After reconnect to wifi router everything works fine for another 5 minutes and stops after
> uname -a

`Linux my-laptop 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
dmesg & lspci output:
[dmesg.log](https://github.com/Joshua-Riek/ubuntu-rockchip/files/15281985/dmesg.log)
[lspci.log](https://github.com/Joshua-Riek/ubuntu-rockchip/files/15281986/lspci.log)

If you have any ideas of how to fix this issue I will be really appreciate.
Thanks

**Comment by Joshua-Riek** [comment]
This is a fork of Ubuntu specifically for Rockchip devices. 

You will want to report this upstream.
