### ISSUE TITLE
uinput module in Kernel 6.1 BSP

### ISSUE THREAD

**Issue by cantalupo555** [Joshua-Riek/ubuntu-rockchip#792]
I'm trying to use ydotool on Ubuntu 24.04, but the uinput module is missing.

```
sudo modprobe uinput
lsmod | grep uinput
```

It appears not to be available in Kernel 6.1 BSP.

Would it be possible to resolve this?

Thanks.

**Comment by Joshua-Riek** [comment]
I see `CONFIG_INPUT_UINPUT=y` is enabled in the kernel config.
