### ISSUE TITLE
NVMe installaion error with v2.1.0

### ISSUE THREAD

**Issue by adr-bed** [Joshua-Riek/ubuntu-rockchip#798]
Hello!
I get error for script `ubuntu-rockchip-install` when trying to install the system to the nvme drive. The error appears on a fresh installation of Ubuntu Server v2.1.0 for Rock 5B:

```
Creating partition table for /dev/nvme0n1.
Creating filesystem on partitions /dev/nvme0n1p1 and /dev/nvme0n1p2.

findmnt: unknown column: SOURCES
Error: in /usr/bin/ubuntu-rockchip-install on line 187
```

**Comment by Joshua-Riek** [comment]
Which OS version? Ubuntu 24.04 or Ubuntu 22.04?

**Comment by adr-bed** [comment]
> Which OS version? Ubuntu 24.04 or Ubuntu 22.04?

24.04

**Comment by ErcinDedeoglu** [comment]
hit same problem.

> apt update
> apt upgrade

now working as expected. thanks!

**Comment by lucvanbraekel** [comment]
I encountered the same problem today when executing ubuntu-rockchip-install on Ubuntu server 22.04 for Orange Pi 5.
Yesterday I executed the same for 24.04 and everything went fine there.

**Comment by Joshua-Riek** [comment]
This has been fixed, update the system with apt.
