### ISSUE TITLE
Missing partition table

### ISSUE THREAD

**Issue by ohyeah521** [Joshua-Riek/ubuntu-rockchip#802]
build command:
`sudo ./build.sh --board=rock-5b --release=jammy --project=server --kernel=rockchip-5.10`

There were no errors during the process, and the image file was generated, but when opening the image with balenaEtcher, it prompted that there was no partition table.

**Comment by ohyeah521** [comment]
@Joshua-Riek this is build log
[build-20240606171049.log](https://github.com/user-attachments/files/15629928/build-20240606171049.log)
[build-20240606174936.log](https://github.com/user-attachments/files/15629938/build-20240606174936.log)

<img width="601" alt="2024-06-06_212910" src="https://github.com/Joshua-Riek/ubuntu-rockchip/assets/1449374/9ceafd3e-14d0-4f99-9ba0-f8e2fa81c7cf">

**Comment by ohyeah521** [comment]
@Joshua-Riek  Maybe this is the reason. The file name generated after compilation is ubuntu-22.04-preinstalled-server-arm64.rootfs.tar. The file in the compressed package is not img, but the content in the picture below.
<img width="775" alt="2024-06-07_102519" src="https://github.com/Joshua-Riek/ubuntu-rockchip/assets/1449374/b4cd3152-e223-4d9c-92f7-3ef57af55c05">

**Comment by Joshua-Riek** [comment]
That is the expected behavior.
