### ISSUE TITLE
display anomaly and system freeze and crash

### ISSUE THREAD

**Issue by wild-coffee** [Joshua-Riek/ubuntu-rockchip#804]
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/51909356/6d04203a-f551-4adb-b560-35c531dbdfc3)
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/51909356/f8e7e0a8-aea1-457f-b135-50cea317572f)

ubuntu 24.04 v2.1 orange pi 5/5 plus

display anomaly and system freeze and crash

**Comment by Joshua-Riek** [comment]
Please provide re-producible steps.
