### ISSUE TITLE
NanoPC T6  LTS 's microchip USB hub not work in Ubunto 24.02 and 22.04 img

### ISSUE THREAD

**Issue by Xiaofenggoex** [Joshua-Riek/ubuntu-rockchip#810]
Nano PC T6  has two version: NanoPC T6 and NanoPC T6 LTS, LTS has a microchip USB 2.0 hub. 

![20240520035331](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/107853381/0c7b96d5-8ea1-49e8-a7a1-0a7443e3ab17)

![20240518164604](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/107853381/eb3afc57-c5d6-428f-b4be-7a874f85653e)
![20240518164534](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/107853381/d75fc843-65d1-4936-8270-72addf3081c1)

**Comment by wmport** [comment]
all works
I did not have auto-mounting of usb drives, but only when installing the OS using the updated wiki.
![Screenshot from 2024-05-18 14-21-23](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/159494449/df18ffdc-96dd-4e5c-b7af-d0fb5b58550f)

**Comment by Xiaofenggoex** [comment]
i know ...

U_BOOT_FDT="device-tree/rockchip/rk3588s-nanopc-t6-lts.dtb"
