### ISSUE TITLE
 Roc-rk3588s-pc boot fail, uboot fdtfile rk3588s-roc-rk3588s-pc.dtb != kernel rk3588s-roc-pc.dtb

### ISSUE THREAD

**Issue by wxzmz** [Joshua-Riek/ubuntu-rockchip#811]
./build.sh --board=roc-rk3588s-pc --release=jammy --project=server
or v2.1.0

**boot fail**
uboot ttl log:

Retrieving file: /boot/vmlinuz-5.10.0-1004-rockchip
39258624 bytes read in 3177 ms (11.8 MiB/s)
append: root=UUID=1ceb7760-62f8-46b5-b46f-a8236a72691f rootwait rw console=ttyS2,1500000 console=tty1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
Retrieving file: /lib/firmware/5.10.0-1004-rockchip/device-tree/rockchip/rk3588s-roc-rk3588s-pc.dtb
** File not found /lib/firmware/5.10.0-1004-rockchip/device-tree/rockchip/rk3588s-roc-rk3588s-pc.dtb **
Skipping l3 for failure retrieving fdt

**Find the cause:**
roc-rk3588s-pc uboot patch is
https://github.com/Joshua-Riek/ubuntu-rockchip/blob/main/packages/u-boot-radxa-rk3588/debian/patches/0010-board-add-roc-rk3588s-pc-support.patch

dts file  arch/arm/dts/rk3588s-roc-rk3588s-pc.dts
+++ b/arch/arm/dts/rk3588s-roc-rk3588s-pc.dts
+CONFIG_DEFAULT_DEVICE_TREE="rk3588s-roc-rk3588s-pc"
..........

**1.in uboot**
build/u-boot-radxa-rk3588/include/configs/rk3588_common.h
"fdtfile=" FDTFILE \

build/u-boot-radxa-rk3588/include/configs/rockchip-common.h
#define FDTFILE "rockchip/" CONFIG_DEFAULT_DEVICE_TREE ".dtb" "\0"

start up,uboot env
fdtfile=rockchip/rk3588s-roc-rk3588s-pc.dtb

**2.kernel**
/boot/extlinux/extlinux.conf
fdtdir /lib/firmware/5.10.0-1004-rockchip/device-tree/

/lib/firmware/5.10.0-1004-rockchip/device-tree/rockchip/rk3588s-roc-pc.dtb

**rk3588s-roc-rk3588s-pc.dtb != rk3588s-roc-pc.dtb**

ubooting log:

append: root=UUID=1ceb7760-62f8-46b5-b46f-a8236a72691f rootwait rw console=ttyS2,1500000 console=tty1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
Retrieving file: /lib/firmware/5.10.0-1004-rockchip/device-tree/rockchip/rk3588s-roc-rk3588s-pc.dtb
** File not found /lib/firmware/5.10.0-1004-rockchip/device-tree/rockchip/rk3588s-roc-rk3588s-pc.dtb **

boot fail

3.**My Modify as follows**:
 0010-board-add-roc-rk3588s-pc-support.patch

Line 668 
@@ -0,0 +1,25 @@ modify
@@ -0,0 +1,27 @@
Line 694 add
+#undef FDTFILE
+#define FDTFILE "rockchip/rk3588s-roc-pc.dtb" "\0"

**last:**
`--- a/0010-board-add-roc-rk3588s-pc-support.patch	2024-05-18 08:13:36.000000000 +0800
+++ b/0010-board-add-roc-rk3588s-pc-support.patch	2024-05-18 14:19:15.000000000 +0800
@@ -665,7 +665,7 @@
 index 0000000000..38b837349a
 --- /dev/null
 +++ b/include/configs/roc-rk3588s-pc.h
-@@ -0,0 +1,25 @@
+@@ -0,0 +1,27 @@
 +/*
 + * SPDX-License-Identifier:     GPL-2.0+
 + *
@@ -691,6 +691,8 @@
 +
 +#endif
 +#endif
++#undef FDTFILE
++#define FDTFILE "rockchip/rk3588s-roc-pc.dtb" "\0"
 -- 
 2.25.1`

[0010-board-add-roc-rk3588s-pc-support.patch](https://github.com/Joshua-Riek/ubuntu-rockchip/files/15363421/0010-board-add-roc-rk3588s-pc-support.patch)

**Comment by Joshua-Riek** [comment]
fixed, thanks.
