### ISSUE TITLE
How to install version 24.04 on the orange pi 5 installed on the SSD (M.2 SATA)?

### ISSUE THREAD

**Issue by douglasdock** [Joshua-Riek/ubuntu-rockchip#813]
If anyone can, I would like to answer a question.
In order for me to be able to boot directly from the SSD, I need to install Ubuntu 24.04 on the SD and execute the "u-boot" commands:

sudo u-boot-install-mtd
sudo u-boot-install /dev/mmcblk0

I'm trying to install and boot using "debian" installed on the SD, but even after installing using "balenaEtcher" of the latest version (ubuntu-24.04-preinstalled-desktop-arm64-orangepi-5) and entering the " OrangePi config / System / Install / Install/Update the bootloader on SPI Flash" and I don't have the M.2 SSD boot

If anyone can help me I will be grateful

**Comment by FreeWilly2022** [comment]
Based on the image you are using, I assume you have a Orange Pi 5 base model. If you don't, then you are using the wrong image. This is Ubuntu, not Debian, so I don't understand that part of your question. The OPi5 has a SPI flash, so you need to copy the image to the SSD using:

sudo ubuntu-rockchip-install /dev/nvme0n1

and u-boot to the SPI flash using:

sudo u-boot-install-mtd

**Comment by douglasdock** [comment]
Hello friend, thanks for the answer and I believe I understood.
I'll try to fix it here and I'll give you feedback

**Comment by douglasdock** [comment]
Hello, I installed "ubuntu 24.04" on the SD card and now I wanted to boot to SSDM2, however when I execute the command:

sudo ubuntu-rockchip-install /dev/nvme0n1

It is returned that it does not have the SSD, with the following information:

"/usr/bin/ubuntu-rockchip-install: block device '/dev/nvme0n1' not found"

I installed "GParted" and I can't find the SSD, on the company's official "Debian" system I know how to activate the SSD, but here I don't have the "Orangepi-config" command.

Would anyone know how to activate the SSD?

Thank you very much

Note: congratulations on the work

**Comment by thanhtantran** [comment]
Hello,

Orange Pi 5 default support M.2 NVME then if you use M.2 SATA the system will not recognize it.

**Comment by douglasdock** [comment]
Hello everything is fine?
It is possible to use the M.2 SSD.
It was discussed here:
https://github.com/Joshua-Riek/ubuntu-rockchip/issues/817
