### ISSUE TITLE
USB inputs don't work in Ubuntu 24.04 on Orange Pi5

### ISSUE THREAD

**Issue by douglasdock** [Joshua-Riek/ubuntu-rockchip#826]
USB inputs don't work in Ubuntu 24.04 on Orange Pi5
When I put any storage device in any USB port it cannot mount.   The storage drives appear, but you cannot access them.  The keyboard and mouse work normally.

**Comment by FreeWilly2022** [comment]
@douglasdock - I wanted you to get an answer, so I got on my Orange Pi 5 running Ubuntu 24.04 desktop, put a USB drive in the USB 3 and USB 2 ports, and it showed up on the desktop and I could open the drive. I then copied the files from the drive to my desktop. So basically I cannot reproduce your issue. Maybe you could check how you have the USB drive formatted, and google if its supported by Linux.

**Comment by douglasdock** [comment]
Good morning, I still can't access the files on the USB:

![Captura de tela de 2024-05-26 10-02-24](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/103003849/f1cb21cf-04b8-4be1-b128-aab4f3115fd8)

![Captura de tela de 2024-05-26 10-04-59](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/103003849/658307c9-43ac-4014-ba4c-7efb64b26dbe)


![Captura de tela de 2024-05-26 10-05-33](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/103003849/834b945b-6adc-40b4-8afa-f9afc694c376)


If anyone can help me fix this error, I would be grateful.

**Comment by FreeWilly2022** [comment]
@douglasdock - this does not appear to be a problem with the operating system. Either your USB drive is damaged or it is not formatted in a way that Linux can read it. Since this is an os github, you probably will get better help asking an ubuntu forum, or googling an answer. Here is a place you can start looking:

https://ubuntu.com/support/community-support

**Comment by douglasdock** [comment]
Hi, thanks for the response.
Unfortunately there is no problem with the device, as they work on other IOS of the orange pi 5

Android 12
![Screenshot_20240527-024314](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/103003849/6a179f02-e1c5-4837-b8bd-4366e1189a1e)

I will try other options and if I have any news I will report it, thank you very much for your attention and work

**Comment by douglasdock** [comment]
Just to inform. I couldn't get the system to recognize the penddrive or SSD that were in NTFS, I converted the drives to fat32 and it recognized normally.
I looked for solutions on the internet and the following commands came to me:

sudo apt install nfs-kernel-server
sudo apt install nfs-common
sudo apt install ntfs-3g

But even after installing and updating it still didn't open, the solution was to convert to FAT

**Comment by Joshua-Riek** [comment]
The usb ports work, try new usb devices.
