### ISSUE TITLE
Will adapt Radxa ROCK 5C？

### ISSUE THREAD

**Issue by zhemed** [Joshua-Riek/ubuntu-rockchip#829]

**Comment by Joshua-Riek** [comment]
Yup, working on it now.

**Comment by majin2020** [comment]
> Yup, working on it now.

Great news :)

**Comment by drsrinathsridhar** [comment]
Just wanted to confirm the 24.04 image works great on the Rock 5C. Microphones connected to the audio jack didn't work in the 5.xx kernel, but the 6.10 kernel fixes this.

Thanks for all you do @Joshua-Riek !

**Comment by johnrichardrinehart** [comment]
> Just wanted to confirm the 24.04 image works great on the Rock 5C. Microphones connected to the audio jack didn't work in the 5.xx kernel, but the 6.10 kernel fixes this.
> 
> Thanks for all you do @Joshua-Riek !

Do you mean 6.1 kernel? I'm trying to get this working on 6.11 and I haven't seen anyone with a working kernel build beyond 6.1, yet.

**Comment by drsrinathsridhar** [comment]
yes, 6.1.

**Comment by johnrichardrinehart** [comment]
@Joshua-Riek You investigate getting this working on 6.11? I started and run into all manner of issues. Huge blocker around clock initialization super early on.

**Comment by Joshua-Riek** [comment]
If it's a huge blocker, figure it out. It's quite easy to adapt a device tree for mainline linux. I'm pretty much done with user bugs and issues. For over a year, I've hated this project and forced myself to deal with this shit.

**Comment by johnrichardrinehart** [comment]
> If it's a huge blocker, figure it out. It's quite easy to adapt a device tree for mainline linux. I'm pretty much done with user bugs and issues. For over a year, I've hated this project and forced myself to deal with this shit. 

I hear you. I wasn't trying to make a demand/expectation. I just wanted to know if I was wasting my time in the case where you already tackled the problems I'm seeing. 

I don't know your situation, but if you hate working on this then you might just archive it and call it a day. No shame in that. 

Thanks for getting back to me!

**Comment by juergenpf** [comment]
I would also recommend to archive this project. This would be a clear statement, that there is no more support to expect and this is a dead end and people should look for alternatives or start their own project.

**Comment by Joshua-Riek** [comment]
Just because I don't care anymore does not mean I'll be gone forever. This is my project, and i will do as i wish. I do not owe anyone an explanation for my actions.
