### ISSUE TITLE
rock 5B, use 2404 LTS v2.1.0,  after apt install kodi ，when relogin or restart into "kodi-wayland", then no mouse or keyboard can be usable, either wired nor wireless.

### ISSUE THREAD

**Issue by kkein** [Joshua-Riek/ubuntu-rockchip#833]

**Comment by nguyenhunga5** [comment]
@kkein you can try this command: sudo usermod -a -G input,video

**Comment by kkein** [comment]
> nguyenhunga5
Yes, it works~
Thanks a lot.  " sudo usermod -a -G input,video yourusername "  , solve  my problems.
