### ISSUE TITLE
Ethernet disconnects in the morning when I wake up

### ISSUE THREAD

**Issue by ghost** [Joshua-Riek/ubuntu-rockchip#836]
Webserver down and unable to access Ethernet at the exact same time every morning. (Around 7-8am).

I have to physically unplug and plug ethernet back in to get it working again.

Ubuntu 22.04 jammy with kernel 5.10. I'll be hunting down the logs in a few hours.

Orange Pi 5 plus 16gb RAM

(base) khan@khan-desktop:~$ lshw -c network
WARNING: you should run this program as super-user.
  *-network                 
       description: Ethernet interface
       product: RTL8125 2.5GbE Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0003:31:00.0
       logical name: enP3p49s0
       version: 05
       serial: c0:74:2b:fe:41:23
       size: 100Mbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8125 driverversion=9.009.00-NAPI-RSS duplex=full ip=192.168.20.20 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
       resources: irq:151 ioport:1000(size=256) memory:f3200000-f320ffff memory:f3210000-f3213fff
  *-network
       description: Ethernet interface
       product: RTL8125 2.5GbE Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0004:41:00.0
       logical name: enP4p65s0
       version: 05
       serial: c0:74:2b:fe:41:22
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8125 driverversion=9.009.00-NAPI-RSS latency=0 link=no multicast=yes port=twisted pair
       resources: irq:164 ioport:100000(size=256) memory:f4200000-f420ffff memory:f4210000-f4213fff

**Comment by khanumballz** [comment]
Have tried tracking down the logs, haven't found anything unusual.

I have set a static IP and restarted the router. Never had this problem on other distros or boards/pc's

**Comment by khanumballz** [comment]
Update: Static IP does not fix this either.

No internet at the exact same time in the morning unless reboot. So weird
