### ISSUE TITLE
ubuntu 24.04 hdmi input

### ISSUE THREAD

**Issue by vtv3000** [Joshua-Riek/ubuntu-rockchip#840]
hi . i freesh install image ubuntu-24.04-preinstalled-desktop-arm64-orangepi-5-plus.img.xz   , install v4l-utils . But  v4l2-ctl --list-devices
Cannot open device /dev/video0, exiting.

**Comment by JFLim1** [comment]
Some info on this: https://github.com/Joshua-Riek/ubuntu-rockchip/issues/606

**Comment by vtv3000** [comment]
i understend hdmi input disable  by default because  CPU Load Avg >1 ????

**Comment by Joshua-Riek** [comment]
yes, see #606
