### ISSUE TITLE
Orange Pi 5 Plus - Q.   Running SPI and EMMC using WIKI commands for 24.04 - do they erase first?

### ISSUE THREAD

**Issue by thewonderer73** [Joshua-Riek/ubuntu-rockchip#858]
Hi,

I've been using an older version of Armbian on my OPi 5+ but decided to upgrade to 2.10 from this repo.

I saw there were 2 commands for installing to SPI and EMMC (which my board has).

I manually wiped the SPI which contained the Armbian uboot  and the EMMC too.

I ran the command for SPI to be flashed
ubuntu@ubuntu:~$ sudo u-boot-install-mtd

For the EMMC I ran the command below.

ubuntu@ubuntu:~$ sudo ubuntu-rockchip-install /dev/mmcblk0

This worked successfully.

My question is, do these 2 commands wipe the data that is present on the SPI and EMMC or do I need to manually wipe them if I decide to do a fresh install when a newer version comes out?

Not directly related to this post, but when I got 24.04 on my Pi5+ and run apt-get update it failed with a repository error.  I will post a different issue when I get time to do a fresh install and check my SD card version of v.2.10

Thanks for all the great work!

**Comment by Joshua-Riek** [comment]
Both of those commands will erase the eMMC and SPI, but you do not need to re-install your system. All changes and updates will be available through a simple apt update command. I will typically only release new versions as I support new hardware.

> Not directly related to this post, but when I got 24.04 on my Pi5+ and run apt-get update it failed with a repository error. I will post a different issue when I get time to do a fresh install and check my SD card version of v.2.10

Sometimes the apt repositories hosted by Canonical return errors, this typically happens during server downtime or maintenance. '
