### ISSUE TITLE
Hope Get Waydroid Support (Panthor GPU Kernel Driver Needed) for Orange Pi 5 Plus Kernel 6.1

### ISSUE THREAD

**Issue by KylinDemons** [Joshua-Riek/ubuntu-rockchip#866]
After I tested, waydroid is not avaliable in ubuntu-24.04-preinstalled-desktop-arm64-orangepi-5-plus, just can't launch.
but I find it has a limited support in Armbian_24.5.1_Orangepi5-plus_noble_vendor_6.1.43_gnome-oibaf_desktop, which has Panthor GPU Kernel Driver installed. I tested it, waydroid worked normally.
Although we need to compile a special version of LineageOS image which include the mesa driver, I think we should workout the Panthor GPU Kernel Driver, BINDERFS and PSI kernel support.
Here are some useful information about these:
[Waydroid for rk3588 with armbian edge (Panthor, kernel 6.8)](https://forum.armbian.com/topic/38184-waydroid-for-rk3588-with-armbian-edge-panthor-kernel-68/)
[Armbian linux-6.8.7 Panthor mpp hdmirx waydroid Release v0.1](https://github.com/WillzenZou/armbian_fork_build/releases/tag/willzen-armbian-24.5.0)
[android_external_mesa3d](https://github.com/WillzenZou/android_external_mesa3d)
[rk3588-panthor-v0.2](https://github.com/WillzenZou/linux-orangepi/releases/tag/rk3588-panthor-v0.2)

**Comment by Joshua-Riek** [comment]
I'm not sure how much testing you have done with the Panthor driver but it's still in a rough shape, so I have absolutely no intent on including it within this distro until there are major improvements. If i where to include the Panthor driver, users would mass report issues and I would be overwhelmed, I struggle enough maintaining this project. Additionally I have already released Ubuntu 24.04, a change like this would be released under a new Ubuntu version such as 24.10, however I don't want to port 24.10 in the first place.

**Comment by ageevp** [comment]
Waydroid works like a charm Ubuntu 24.04!
Waydroid Ubuntu 24.10 works if you upgrade 
Ubuntu 24.04 by do-release-upgrade.
PS.
$ uname -r
6.1.0-1025-rockchip

Pure  waydroid install  is not working.

**Comment by riegaz** [comment]
@ageevp could you elaborate a bit? I just tried to run waydroid on 24.04 after updating (apt-get upgrade) and waydroid runs but it is really laggy. Should it work with hardware acceleration out of the box or did I brake something by updating?

**Comment by riegaz** [comment]
@KylinDemons thanks I wasn't aware. Does it work with the latest 24.04 build on 6.1.75 kernel on an Orange Pi 5 Max?

I just tried to launch it and it doesn't.

**Comment by KylinDemons** [comment]
> @KylinDemons thanks I wasn't aware. Does it work with the latest 24.04 build on 6.1.75 kernel on an Orange Pi 5 Max?
> 
> It seems to be installed by default and the docker is running but using scrcpy it connects without showing a screen.

With kernel 6.1, you need to manually compile the kernel according to the project instructions, as most kernel 6.1 cannot be used directly out of the box.

**Comment by riegaz** [comment]
> With kernel 6.1, you need to manually compile the kernel according to the project instructions, as most kernel 6.1 cannot be used directly out of the box.

Thanks, so as this project uses the right kernel I have to enable these, right? Is there a detailed instruction somewhere for people who don't recompile kernels so often?

CONFIG_PSI=y
CONFIG_ANDROID_BINDERFS=y

Sorry, I'm not very familiar with it.

With the 22.02 image from here it would work out of the box as it uses the 5.10 kernel?

**Comment by KylinDemons** [comment]
> > With kernel 6.1, you need to manually compile the kernel according to the project instructions, as most kernel 6.1 cannot be used directly out of the box.
> 
> Thanks, so as this project uses the right kernel I have to enable these, right? Is there a detailed instruction somewhere for people who don't recompile kernels so often?
> 
> CONFIG_PSI=y CONFIG_ANDROID_BINDERFS=y
> 
> Sorry, I'm not very familiar with it.
> 
> With the 22.02 image from here it would work out of the box as it uses the 5.10 kernel?

6.1 kernel patch for redroid is here. You need to manually apply these patches to the kernel source code and re-compile it. After testing, Armbian based 6.1 kernel can start Redroid normally after being patched. Additionally, the 5.10 kernel can use Redroid-rk3588 directly out of the box with GPU acceleration.

**Comment by KylinDemons** [comment]
> > With kernel 6.1, you need to manually compile the kernel according to the project instructions, as most kernel 6.1 cannot be used directly out of the box.
> 
> Thanks, so as this project uses the right kernel I have to enable these, right? Is there a detailed instruction somewhere for people who don't recompile kernels so often?
> 
> CONFIG_PSI=y CONFIG_ANDROID_BINDERFS=y
> 
> Sorry, I'm not very familiar with it.
> 
> With the 22.02 image from here it would work out of the box as it uses the 5.10 kernel?

6.1 kernel patch for redroid is here. You need to manually apply these patches to the kernel source code and re-compile it. After testing, Armbian based 6.1 kernel can start Redroid normally after being patched. Additionally, the 5.10 kernel can use Redroid-rk3588 directly out of the box with GPU acceleration.
[0001-dma-buf-Add-Android-required-dma_buf-devices.patch](https://github.com/user-attachments/files/17965126/0001-dma-buf-Add-Android-required-dma_buf-devices.patch)

**Comment by riegaz** [comment]
> 6.1 kernel patch for redroid is here. You need to manually apply these patches to the kernel source code and re-compile it. After testing, Armbian based 6.1 kernel can start Redroid normally after being patched. Additionally, the 5.10 kernel can use Redroid-rk3588 directly out of the box with GPU acceleration.
> [0001-dma-buf-Add-Android-required-dma_buf-devices.patch](https://github.com/user-attachments/files/17965126/0001-dma-buf-Add-Android-required-dma_buf-devices.patch)

I would use this as the 6.1 kernel source? https://github.com/Joshua-Riek/linux-rockchip or the one from https://github.com/CNflysky/linux-rockchip?

**Comment by KylinDemons** [comment]
> > 6.1 kernel patch for redroid is here. You need to manually apply these patches to the kernel source code and re-compile it. After testing, Armbian based 6.1 kernel can start Redroid normally after being patched. Additionally, the 5.10 kernel can use Redroid-rk3588 directly out of the box with GPU acceleration.
> > [0001-dma-buf-Add-Android-required-dma_buf-devices.patch](https://github.com/user-attachments/files/17965126/0001-dma-buf-Add-Android-required-dma_buf-devices.patch)
> 
> I would use this as the 6.1 kernel source? https://github.com/Joshua-Riek/linux-rockchip or the one from https://github.com/CNflysky/linux-rockchip?

With this patch file, it is reasonable to compile on any source code in version 6.1 with rk3588. The kernel source code provided by the latter(https://github.com/CNflysky/linux-rockchip) has already been patched and comes from Armbian. I don't know if it is suitable for Joshua Riek's Ubuntu. But you can try compiling the kernel and installing it yourself based on the patch file with Joshua Riek's source code.

**Comment by riegaz** [comment]
> With this patch file, it is reasonable to compile on any source code in version 6.1 with rk3588. The kernel source code provided by the latter(https://github.com/CNflysky/linux-rockchip) has already been patched and comes from Armbian. I don't know if it is suitable for Joshua Riek's Ubuntu. But you can try compiling the kernel and installing it yourself based on the patch file with Joshua Riek's source code.

Steps:
1. git clone https://github.com/Joshua-Riek/linux-rockchip.git
2. cd linux-rockchip
3. git checkout noble
4. patch -p1 < 0001-dma-buf-Add-Android-required-dma_buf-devices.patch
then I get this output:
![image](https://github.com/user-attachments/assets/c37f59ce-7b5c-48cc-a16f-af36b2eb80c0)
Which I enter "n":
5. fakeroot debian/rules clean binary-headers binary-rockchip do_mainline_build=true

![image](https://github.com/user-attachments/assets/e8c73c74-c5db-43ec-8947-c94b5ff8693e)

Which I acknowledge with "y".

However during the build these errors come up:

![image](https://github.com/user-attachments/assets/a2036bea-7649-4c34-9cef-5e5738c12b33)

**Comment by riegaz** [comment]
I just was able to get it working. I'm surprised that it works so well and the docker itself is not eating much ressources.

Just as a sidenode. I tried to create a docker with a resolution of 4k and it works great when I access via scrcpy from another machine. However, the rk3588 runs into performance issues if you try to run both on the same machine. Would have been great if one could output the docker's image directly on the local screen without the need for scrcpy.

Not sure if this works.

**Comment by OW1TY2** [comment]
May I ask what's your choice when patching?
> I just was able to get it working. I'm surprised that it works so well and the docker itself is not eating much ressources.
> 
> Just as a sidenode. I tried to create a docker with a resolution of 4k and it works great when I access via scrcpy from another machine. However, the rk3588 runs into performance issues if you try to run both on the same machine. Would have been great if one could output the docker's image directly on the local screen without the need for scrcpy.
> 
> Not sure if this works.
