### ISSUE TITLE
CM5 - Boots but without USB support

### ISSUE THREAD

**Issue by DarkevilPT** [Joshua-Riek/ubuntu-rockchip#871]
Kernel the USB2 seems screwed at “device” mode, even with the echo host command used on the OPI5, it doesnt work, it still stuck at “device” mode

![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/3583885/816f3a9f-2045-4b10-bf18-5a6b0bb72757)

**Comment by Joshua-Riek** [comment]
Fixed with https://github.com/Joshua-Riek/linux-rockchip/commit/fb45cb497d99b458e0b2d955315a1924483ef5a5. I should release an updated kernel package in a few days with this fix.

**Comment by DarkevilPT** [comment]
Joshua... Big Thank you man ! 💪🏻🌟🍺
