### ISSUE TITLE
Orange Pi 5 Pro USB 3.0 port does not work on 24.04

### ISSUE THREAD

**Issue by jinglong485** [Joshua-Riek/ubuntu-rockchip#875]
usb 3.0 port on orange pi 5 pro does not work. attached is result of dmesg | grep usb.
[dmesg.log](https://github.com/user-attachments/files/15813820/dmesg.log)

**Comment by Joshua-Riek** [comment]
see https://github.com/Joshua-Riek/ubuntu-rockchip/issues/814
