### ISSUE TITLE
jellyfin-ffmpeg6

### ISSUE THREAD

**Issue by DorianMazur** [Joshua-Riek/ubuntu-rockchip#877]
How to install jellyfin-ffmpeg6 ?

**Comment by nyanmisaka** [comment]
The `jellyfin-ffmepg6` package is part of the jellyfin server, therefore it will be installed automatically..
https://jellyfin.org/downloads/server

If you need to install it separately, you can download it and use `dpkg -i` or `apt install` to install it.
https://github.com/jellyfin/jellyfin-ffmpeg/releases
