### ISSUE TITLE
How to enable Ralink RT5370 wireless adapter in rt2800usb kernel module?

### ISSUE THREAD

**Issue by alextrezvy** [Joshua-Riek/ubuntu-rockchip#880]
This adapter in Orange Pi 5 was disabled for whatever reasons:
`modinfo rt2800usb | grep '5370'`

```
cat  /boot/config-5.10.160-rockchip | grep 'RT53XX'
CONFIG_RT2800PCI_RT53XX=y
# CONFIG_RT2800USB_RT53XX is not set
```

Hence, suddenly I can't use my adapter that worked for 10+ years.
It should be possible to compile "rt2800usb" module from sources, but I don't know how to do it without compiling the whole kernel. And compiling the whole kernel seems overkill and errorprone.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

**Comment by alextrezvy** [comment]
Same issue in 24.04.

**Comment by Joshua-Riek** [comment]
The kernel comes from an Android source I could not mass enable wireless drivers due to a large amount of kernel errors during compiling. So I need to manually enable wireless drivers as problems come up or per user request. However recompiling the whole kernel is required.

Id be happy to enable this driver, ill get back to you when it's enabled.

**Comment by Joshua-Riek** [comment]
This has been enabled in both kernels, I will update you when the kernel packages are upgraded this weekend.
https://github.com/Joshua-Riek/linux-rockchip/commit/41576ace65693da86345159bc658b4b5de52aa58
https://github.com/Joshua-Riek/linux-rockchip/commit/5be2a12f42e589cbdfd9da079ca1a7c33684c202

**Comment by Joshua-Riek** [comment]
Update your system with apt and reboot, the driver has been added and kernel package uploaded.

**Comment by alextrezvy** [comment]
It works! Thank you very much!
PS: wish to make a small donation, but don't know how to do it due to sanctions. Do you accept litecoin or zcash?

**Comment by Joshua-Riek** [comment]
Much appreciated, currently I only accept donations through GitHub itself.

https://github.com/sponsors/Joshua-Riek
