### ISSUE TITLE
After apt upgrade, Chromium version114 crash on rock5b，24.04 cannot run chromium; 22.04 can run chromium，then crash when play youtube video。

### ISSUE THREAD

**Issue by kkein** [Joshua-Riek/ubuntu-rockchip#889]

**Comment by Joshua-Riek** [comment]
I'm almost 100% sure this is user error. You are likely using a bad power supply or DDR + SPL miss match where DMC is disabled. In that case look at the wiki to update U-Boot on the SPI.

https://github.com/Joshua-Riek/ubuntu-rockchip/wiki/Ubuntu-24.04-LTS#install-u-boot-to-the-spi-flash

**Comment by Joshua-Riek** [comment]
I tested this and can not reproduce the problem.

**Comment by kkein** [comment]
Thanks a lot. 
I found the error is caused by the power supply.  And I  also update the u-boot , then fix it.
