### ISSUE TITLE
APT Initramfs-tools error

### ISSUE THREAD

**Issue by cody8764** [Joshua-Riek/ubuntu-rockchip#899]
I was using Ubuntu normally but I then did an apt upgrade. I suddenly got an error every time I used apt saying: 

Processing triggers for initramfs-tools (0.142ubuntu25.1) ...
update-initramfs: Generating /boot/initrd.img-6.1.0-1017-rockchip
Unsupported platform 'Orange Pi 5 Plus'.
run-parts: /etc/initramfs/post-update.d//flash-kernel exited with return code 1
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned 
error exit status 1
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

How do I fix this error so that I can use apt normally again?

**Comment by Joshua-Riek** [comment]
For some reason you installed `flash-kernel`. Purge the package.

**Comment by cody8764** [comment]
Thanks, It solved my issue!

**Comment by alexorex** [comment]
I deployed 22.04 Server, upgraded, then installed minimal Gnome and got the same "Unsupported platform 'Orange Pi 5 Plus'" error having installed mpv, which was resolved after purging the flash-kernel.
Can't the package be somehow forbidden in O-Pi distro version?
Thanks for the solution anyway!
