### ISSUE TITLE
No overlay folder after system upgrade

### ISSUE THREAD

**Issue by mrslowfloww** [Joshua-Riek/ubuntu-rockchip#900]
After the latest system upgrade (to 6.1.0-1018), there's no overlay folder in /lib/firmware/6.1.0-1018-rockchip/device-tree/rockchip . So can't use GPIO, display or anything else that requires overlay files. 

(Orange Pi 5 Plus)

**Comment by Joshua-Riek** [comment]
Crap, looking into it now

**Comment by Joshua-Riek** [comment]
Should be fixed with https://github.com/Joshua-Riek/linux-rockchip/commit/bd004a7dc104f12c13557baf92058d51b0febb8a. 

Im uploading the kernel now, but i wont be able to upload the meta package until tonight after work.

**Comment by mrslowfloww** [comment]
> Should be fixed with [Joshua-Riek/linux-rockchip@bd004a7](https://github.com/Joshua-Riek/linux-rockchip/commit/bd004a7dc104f12c13557baf92058d51b0febb8a).
> 
> Im uploading the kernel now, but i wont be able to upload the meta package until tonight after work.

It's alright. I temporarily switched back to 6.1.0-1017 until it will be resolved.

**Comment by Joshua-Riek** [comment]
The update has been released, and this should be fixed now.
