### ISSUE TITLE
build jammy rootfs-only, an error will appear

### ISSUE THREAD

**Issue by ohyeah521** [Joshua-Riek/ubuntu-rockchip#903]
I found that after executing the command sudo ./build.sh --suite=jammy --flavor=server --rootfs-only, an error will appear.

Logfile: https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/9728778019/job/26849896896

<img width="366" alt="2024-07-02_095209" src="https://github.com/Joshua-Riek/ubuntu-rockchip/assets/1449374/11f6b8ad-02ae-49fa-ad16-5c56701bc239">

**Comment by Joshua-Riek** [comment]
livecd rootfs returns a 1 exit code which indicates an error, but this can be ignored

**Comment by ohyeah521** [comment]
thanks
