### ISSUE TITLE
fdt: Reserverd memory:failed to reserve menory for node 'drm-logo@0':base 0x0000000000000000,size 0 MiB

### ISSUE THREAD

**Issue by m2kall** [Joshua-Riek/ubuntu-rockchip#907]
你好，上次你说的需要更新内核，我尝试了下更新到6.1.0-1019. 软件打开经常会卡顿，fork资源不可用等情况。
于是查看了以下内容，跟这个有关联吗？
请帮我看看好吗，谢谢🙏
![截图 2024-07-03 11-16-23](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/42733818/6a8bf189-ea74-400a-a86f-6e90c222725f)

**Comment by Joshua-Riek** [comment]
drm-logo is for a splash screen image on boot, but this is not used. 

What software lags?

**Comment by m2kall** [comment]
Terminal and browser
I don't know English, so the description using Google Translate may not be very good. So I recorded 3 videos to recreate the scene.
part1. When the traffic proxy software is not used, the browser will turn white in sections (this whitening situation only occurs in this version of Chrominu, not in other versions), and after opening other tasks, the browser will have no service. Sometimes there is no service even if no service is opened.
part2. After using the traffic proxy software clash, the browser has no service more frequently, sometimes the folder cannot be opened, the browser cannot enter text, and the terminal will often bash:fork:retry: resource is temporarily unavailable (this situation often occurs when I did not install the traffic proxy software before)
part3. In the third video, I restarted this orange pi 5-pro and opened these services, without using any traffic proxy. The browser also has no service.

I originally recorded several segmented videos, but the files are too large to upload

https://github.com/Joshua-Riek/ubuntu-rockchip/assets/42733818/0dd61338-9b97-475e-8066-310a3bdbe104


![截屏2024-07-04 01 01 55](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/42733818/c3929f8e-d0a6-4822-b533-8611e3814f83)
![截屏2024-07-04 01 03 34](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/42733818/85cb0924-25a4-45ec-88c5-645755d7217d)
![截屏2024-07-04 01 04 23](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/42733818/46d7c648-1e0e-4952-b16c-754da4eacc34)
![截屏2024-07-04 01 04 36](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/42733818/bad84254-e9a1-4e61-a5f8-a9a1a11ba7ce)

**Comment by cliangtime** [comment]
我也遇到了一样的问题，请问是怎么解决的呀

**Comment by m2kall** [comment]
> 我也遇到了一样的问题，请问是怎么解决的呀

后面我忘了怎么操作的，现在我的系统挺稳定的。

![Image](https://github.com/user-attachments/assets/9966a097-c580-492f-a89c-2b67108fa820)

我现在的系统是这样，有大半年没折腾了，你下载最新的镜像试试。
