### ISSUE TITLE
Rootfs opensource for LubanCat4 RK3588s

### ISSUE THREAD

**Issue by shingoxy** [Joshua-Riek/ubuntu-rockchip#914]
Hi, anywhere I could find the open souce of ubuntu rootfs for LubanCat4? 20.04 version will be fine.

Thanks~

**Comment by Joshua-Riek** [comment]
Ubuntu 20.04 is not supported.

**Comment by shingoxy** [comment]
Thanks @Joshua-Riek , if I changed to your version 22.04 or 24.04, could I get the rootfs directly? Thanks~

**Comment by shingoxy** [comment]
> The rootfs can be downloaded from all GitHub action builds:
> 
> * https://github.com/Joshua-Riek/ubuntu-rockchip/actions/workflows/nightly.yml
> 
> Direct download links:
> 
> * [ubuntu-22.04-preinstalled-desktop-arm64-rootfs](https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/9831289481/artifacts/1675870374)
> * [ubuntu-22.04-preinstalled-server-arm64-rootfs](https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/9831289481/artifacts/1675826002)
> * [ubuntu-24.04-preinstalled-desktop-arm64-rootfs](https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/9831289481/artifacts/1676046419)
> * [ubuntu-24.04-preinstalled-server-arm64-rootfs](https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/9831289481/artifacts/1675927144)

Thanks~That's really helpful, and where could I get the kernel. I am doing some develop with new cameras.

**Comment by Joshua-Riek** [comment]
Kernel source code is below, on branch noble and jammy.
https://github.com/Joshua-Riek/linux-rockchip
