### ISSUE TITLE
Headphones doesn't work on Orange Pi 3B.

### ISSUE THREAD

**Issue by qqdasb** [Joshua-Riek/ubuntu-rockchip#920]
uname -a : Linux name-desktop 6.1.0-1016-rockchip #16-Ubuntu SMP Thu Jun  6 00:11:54 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
dmesg : 
[dmesg.txt](https://github.com/user-attachments/files/16200674/dmesg.txt)
sound card:es7202

**Comment by Gi-0n** [comment]
@qqdasb Were you able to solve it, can you explain to me how to do it?
