### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by SimplyCorbett** [Joshua-Riek/ubuntu-rockchip#932]
I just updated my cluster and one of the servers is having issues with apparmor. Is this a problem on your end or is it just ubuntu being ubuntu?

Using orange pi 5 plus on the latest version with 24.04.

https://gist.github.com/SimplyCorbett/d7fae5dc548ac28d13726fb0badde7a6

**Comment by Joshua-Riek** [comment]
Apparmer is masked during the build process due to these errors. I need to look into Apparmor more to figure out how to properly fix.

But you can try:
```bash
sudo systemctl mask apparmor
```

**Comment by SimplyCorbett** [comment]
I didn't enable apparmor so it's weird its not masked already. I'll run that command, thanks!
