### ISSUE TITLE
为什么24在orangepi5上启动不了啊

### ISSUE THREAD

**Issue by SESProMax** [Joshua-Riek/ubuntu-rockchip#937]
我尝试了sd卡和USB启动，都不成功。状态灯一直是红灯常亮。

**Comment by Deiiji** [comment]
What do you use to burn your image? With Etcher it work well.

**Comment by SESProMax** [comment]
> What do you use to burn your image? With Etcher it work well.

I used dd command. etcher failed to flash.

**Comment by SESProMax** [comment]
Has this OS changed boot logic? It doesn't need to edit boot file to boot from ssd?

**Comment by Deiiji** [comment]
Is maybe where problem is... download another image

**Comment by Deiiji** [comment]
I think, sata overlay still been needed but I am not sure as I use NVMe

**Comment by mario-huang** [comment]
把xz格式的解压，得到img。用Etcher写到tf卡上，插卡，启动，两分钟不到能看到画面。
