### ISSUE TITLE
add new board armsom-aim7-io

### ISSUE THREAD

**Issue by armsom-team** [Joshua-Riek/ubuntu-rockchip#945]
Joshua, good evening, we have completed the armbian adaptation of aim7, can you update linux and related configurations and provide a usable firmware?
Our server environment seems to be unable to compile ubuntu-rockchip

https://github.com/armbian/build/pull/6987

**Comment by Joshua-Riek** [comment]
Hey! I will be adding support for the AIM7 tonight, and im sorry for the delay. I have been very busy!

**Comment by armsom-team** [comment]
OK, thank you for your support. We also have sige1 supported on armbain. If possible, we need to test your firmware.https://github.com/armbian/build/pull/6546
