### ISSUE TITLE
Bug Report: Signal messenger database error 

### ISSUE THREAD

**Issue by fyptog** [Joshua-Riek/ubuntu-rockchip#966]
### What happened?

For the last few days Signal messenger gives a "Database error", and needs to be reset, restarted and re-linked every time the app is started. There are 4 orange pi5 computers being used as personal desktops in my household (standalone solar house) and all are having the same problem. very frustrating. 
No sign of Signal problems on our PCs with MX linux, or PopOS (snap).

### Kernel version

6.1.0-1021-rockchip

### SBC model

Orange Pi 5

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

### Relevant logs

dialog to copy error is answered with rejected - and a rejection log is offered instead 
Unhandled Promise Rejection

Error: Not initialized
    at MainSQL.close ([REDACTED]/ts/sql/main.js:104:13)
    at BrowserWindow.<anonymous> ([REDACTED]/app/main.js:690:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:511:9)

**Comment by Joshua-Riek** [comment]
It may be worth opening an issue with the Signals application, though i did find https://github.com/signalapp/Signal-Desktop/issues/5721, can you try starting the program with `--disable-gpu`?

**Comment by fyptog** [comment]
Still the same Database Error.
Thanks anyway.

**Comment by fyptog** [comment]
This is it - https://github.com/snapcrafters/signal-desktop/issues/300

**Comment by Joshua-Riek** [comment]
Closing as this is not an issue with Ubuntu Rockchip.
