### ISSUE TITLE
Bug Report: Orange pi 5 cannot boot at second time onwards

### ISSUE THREAD

**Issue by Virusker** [Joshua-Riek/ubuntu-rockchip#975]
### What happened?

After installation, I rebooted but only got red light

### Kernel version

5.10.0-1011.11-rockchip

### SBC model

Orange pi 5

### What operating system are you seeing this problem on?

Ubuntu 22.04 LTS (Jammy Jellyfish)

**Comment by Joshua-Riek** [comment]
You probably did not let the disk buffers sync, leading to a corrupt filesystem. 

Also, there is no way I can debug this without full boot logs from a uart console.

**Comment by Virusker** [comment]
Sorry, please explain what you mean disk buffers sync

**Comment by Joshua-Riek** [comment]
I really don't have time to explain disk buffers. Please reinstall, and before rebooting, let the system wait for 1 or 2 minutes.
