### ISSUE TITLE
Feature Request: How should I modify the .config file for Linux-Rockchip to compile the kernel?

### ISSUE THREAD

**Issue by pwy583** [Joshua-Riek/ubuntu-rockchip#999]
### Feature Description

How should I modify the .config file for Linux-Rockchip to compile the kernel？There is no .config file in the Linux-Rockchip directory. When I add a .config file and use a script to compile, it gives me an error. How should I solve this problem? I also tried modifying the .config file in the debian directory under the Linux-Rockchip directory, but when I compile using the build.sh script, it reverts to the original configuration, which doesn't match the changes I made.

**Comment by Joshua-Riek** [comment]
Please read https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel.

```bash
# shellcheck disable=SC2046
export $(dpkg-architecture -aarm64)
export CROSS_COMPILE=aarch64-linux-gnu-
export CC=aarch64-linux-gnu-gcc
export LANG=C

# Compile the kernel into a deb package
fakeroot debian/rules clean binary-rockchip do_mainline_build=true
```
